### ISSUE TITLE
OutOfRange should be renamed Overflow

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#103]
Discussing #102... the whole "OutOfRange" concept should be renamed throughout the gem as a lot more appropriate "Overflow". Here are the changes needed:

- [x] The `Pagy::OutOfRangeError` should be renamed more properly `Pagy::OverflowError`
- [x] The `out_of_range` extra should be renamed `overflow` extra
    - [x] rename the `@out_of_range` as `@overflow`
    - [x] `out_of_range?` as `overflow?`
    - [x] `OutOfRange` module as `Overflow`
    - [x] `:out_of_range_mode` as `:overflow`
- [x] Search and replace throughout the docs 
- [x] ~~Create aliases to avoid breaking legacy apps~~ (not needed because of mayor version bump)

**Comment by espen** [comment]
So this will result in OverflowError for 0 and invalid input (string)?

**Comment by ddnexus** [comment]
Well... the renaming will consistently explain that it is an `OverflowError` (i.e. bigger than max) and not a `OutOfRangeError` (i.e. bigger than max but also smaller than min), so it will address the inconsistency that has been exposed in #102.

As I thought I explained in #102 - I don't see any reason to natively handle the `ArgumentError` of `:page` being a non-integer string any different than a mere `ArgumentError`. 

`page: "foo"` should raise a `ArgumentError:  expected :page in 1..123; got "foo"` as for `items: "foo"`. The special `OverflowError` is for a naturally occurring situation that is actually not an `ArgumentError` in the sense that is not a wrong argument type, but may be just be the consequence of deletion of records after pagination rendering.

I still didn't merge the change, so maybe you can find some compelling reason against my last comments in #102.
