### ISSUE TITLE
Keyset pagination

### ISSUE THREAD

**Issue by espen** [ddnexus/pagy#106]
Have you considered [keyset](https://use-the-index-luke.com/no-offset) pagination? It would result in much better database performance.

I see there is [order_query](https://github.com/glebm/order_query) but I haven't tried it. Looking briefly at the code it would definitively complicate things. Perhaps it could be used as a plugin?

What are your thoughts on this?

**Comment by espen** [comment]
I guess what is needed is an attribute for which column to use as a key to order. With an input for last seen value to be used when querying the next page. That sounds simple enough but looking at the order_query source I'm not so sure. I will try it out and see if it can be handled directly in pagy or whether it must be more versatile and relay it to order_query as an extra in pagy.

**Comment by ddnexus** [comment]
Thanks!

**Comment by ddnexus** [comment]
see #136

**Comment by ddnexus** [comment]
Long time since this one.

The [Pagy::Keyset pagination](https://ddnexus.github.io/pagy/docs/api/keyset/) arrived in all its glory in v9.

Yeah... long time... I know 😁
