### ISSUE TITLE
Unable to use :params and :anchor

### ISSUE THREAD

**Issue by bihanichandresh** [ddnexus/pagy#113]
I'm trying to user :params and :anchor with pagy without any luck. I've updated to 1.2.1 just to verify if there's some bug. The anchor is not applied nor the params are merged. Also tried using **"pagy_get_vars"** without any luck.

`pagy(Model.all, params: { a: 'a' }, anchor: '#your_anchor')`

What am I missing here?

**Comment by ddnexus** [comment]
Not sure I understand what you mean.

You can take a look at the tests [here](https://github.com/ddnexus/pagy/blob/e8acde36a1c2df58e35ec3697e4fb994192f65d9/test/pagy/frontend_test.rb#L148-L170).
Here is also a [practical example](https://www.imaginarycloud.com/blog/how-to-paginate-ruby-on-rails-apps-with-pagy) about how to use that.

**Comment by bihanichandresh** [comment]
I did follow the example you're referring to but it did not work for me.

Let me elaborate the issue,

1. I tried passing arbitrary params `params: { a: 'a' }`, but `params[:a] returns nil` in view.
2. `page_param: :test` did not prepend `test` to url.
3. `anchor: "#test"` did not prepend the anchor tag to url.

Set of queries I tried:

1. `@pagy, @users = pagy(User.all, page_param: :test)`
2. `@pagy, @users = pagy(User.all, params: { a: 'a' }, anchor: '#test')`

I've imported `Pagy::Backend` in ApplicationController & `Pagy::Frontend` in Application Helper.

Pagy.rb file
`require 'pagy/extras/bootstrap'`
`require 'pagy/extras/searchkick'`
`Rails.application.config.assets.paths << Pagy.root.join('javascripts')`
`Pagy::VARS[:items] = 10`
`Pagy::VARS[:breakpoints] = { 0 => [1, 2, 2, 1] }`

_Am I doing something wrong?_

**Comment by ddnexus** [comment]
It sounds like you are expecting the `pagy.vars[:params]` to get merged with your application `params` right away. That's not the case. If you click on a pagination link then your request will contain the `"a"` param, as a regular param from the url. Please, check the url of the generated links in the nav and you should have it there.

**Comment by ddnexus** [comment]
> page_param: :test did not prepend test to url

it is not supposed to "prepend" test to url, it is supposed to use the param test in place of the usual "page".

**Comment by ddnexus** [comment]
Closing this as invalid non-issue.
Please, read the doc and examples, and if you still don't get it working, please ask in the Gitter chat.
