### ISSUE TITLE
Using in HAML

### ISSUE THREAD

**Issue by mechnicov** [ddnexus/pagy#124]
I use HAML in my project.
So I can't add something like `<%== pagy_nav(@pagy) %>`

1. I tried `= pagy_nav(@pagy)`. It returns 

```
<nav class="pagy-nav pagination" role="navigation" aria-label="pager"><span class="page prev disabled">&lsaquo;&nbsp;Prev</span> <span class="page active">1</span> <span class="page"><a href="/users/1?page=2" rel="next" >2</a></span> <span class="page"><a href="/users/1?page=3" >3</a></span> <span class="page"><a href="/users/1?page=4" >4</a></span> <span class="page"><a href="/users/1?page=5" >5</a></span> <span class="page gap">&hellip;</span> <span class="page"><a href="/users/1?page=17" >17</a></span> <span class="page next"><a href="/users/1?page=2" rel="next" aria-label="next">Next&nbsp;&rsaquo;</a></span></nav>
```

2. I tried `== pagy_nav(@pagy)`. It returns
```
pagy_nav(@pagy) 
```

3. I tried `= = pagy_nav(@pagy)`. It returns syntax error.

What's right syntax for HAML?

**Comment by nicoalonsop** [comment]
I am having the same problem. I solve it with html_safe
`= pagy_nav(@pagy).html_safe`

**Comment by ddnexus** [comment]
I don't remember the specific syntax for haml, but yu can also use 

```
= pagy_nav(@pagy).html_safe
```

**Comment by tbcooney** [comment]
`!= pagy_nav(@pagy)` or `!= pagy_info(@pagy)`

**Comment by MatyasBalcar** [comment]
= pagy_nav(@pagy).html_safe, worked for me
