### ISSUE TITLE
Webpacker integration

### ISSUE THREAD

**Issue by cseelus** [ddnexus/pagy#128]
Now that Rails is gradually switching away from Sprockets and moving to Webpack (as everyone seems to do these days …), is there a way Pagy can and will support this?

One way to go would be a separate NPM module for Pagy, though there might be better ways to pull this off.

**Comment by ddnexus** [comment]
Hi Chris,
I am currently working on many very old apps, that's one of the reason [pagy 2](https://github.com/ddnexus/pagy/tree/v2.0-dev)  will be ruby 1.9+ compatible)... and I am not very up-do-date with the webpacker gem.

I would really like to use a simpler mechanism to include `pagy.js`, than creating a NPM package, which doesn't make so much sense for a 99% ruby project with little support from classic/compatible/old javascript... not to mention that it would require to maintain 2 packages.

Isn't there any helper for `webpacker` to just import the javascript file form a local path? We have the `pagy.js` in `Pagy.root.join('javascripts', 'pagy.rb'). Cannot we directly include that path?

**Comment by cseelus** [comment]
Good morning Domizio,

unfortunately there is no helper whatsoever, as far is I know. Using a dedicated NPM package (with just the assets) is whats most gem authors do to make their gems compatible with Webpacker, the official Asset Pipeline replacement for Rails, see discussion here: https://github.com/rails/webpacker/issues/488#issuecomment-309403015

Authors of gems from Rails core also seem to do this, for example:
- [Rails Action Cable](https://www.npmjs.com/package/actioncable)
- [Rails Active Storage](https://www.npmjs.com/package/@rails/activestorage)
- [Rails UJS](https://www.npmjs.com/package/rails-ujs)
- …

I see if I find a robust way to directly include the Pagy assets though and get back to the discussion here, if it works out.

**Comment by ddnexus** [comment]
Chris,
this [webpacker erb support](https://github.com/rails/webpacker#erb) looks promising! I didn't try it but it looks like with `erb` in javascript, we can just pull the file and include it wherever. Could you give it a try?

**Comment by ddnexus** [comment]
The simplest thing may be having the possibility to use:
```yaml
resolved_path: [..., <%= Pagy.root.join('javascripts') %>]
```
in the `"config/webpacker.yml"` (that can be renamed as "config/webpacker.yml.erb" and trigger an `erb` rendering). The patch required for the `Webpacker::Configuration#load` method would be very simple: just checking the suffix and rendering the file with `erb` first, if the suffix includes `".erb"`.

I have no time to prepare the environment now, but if you could share a minimal app repo with webpacker already installed and configured, I could write the patch and try it.

Thanks

**Comment by cseelus** [comment]
Sure. I copied a [Rails sample App with Webpacker enabled](https://github.com/maxivak/webpacker-rails-example-app), that I found on Github, stripped all unnecessary stuff I could find and updated everything. Hope this helps:

https://github.com/cseelus/rails-webpacker-sample

**Comment by ddnexus** [comment]
That's great! Thank you Chris.
I will see if that idea could work, and if it does, I may create a PR for webpacker.

**Comment by cseelus** [comment]
For now I've copied the Pagy JS file and added an `export default` to `import Pagy from '…'` in my pagination.js (where I add Keyboard support) and I'm good to go.

As Rails 6.0 will use Webpacker as default for JS stuff (instead of the trusty old Asset Pipeline), long term a dedicated NPM package might be the most standard/user friendly approach. 

I have to say that for the application I migrated to Webpacker, every single frontend dependency from the Rails gems for this app was available on NPM, which really surprised me.

**Comment by ddnexus** [comment]
I am busy with other stuff now, but I think I could experiment with the possible solution during this weekend.

**Comment by cseelus** [comment]
No need to hurry ;-)

As I said, I copied the Pagy.js file manually and it works quite well for now. 
Rails 6.0 final is still a few months away, so quite some time until a bunch of other people will need a Webpacker solution for Pagy.

**Comment by ddnexus** [comment]
Chris, I sent you an email to your git-address a few days ago... did you have any chance to read it?

**Comment by cseelus** [comment]
Yes of course, I answered it. I just sent you another mail, please check your GMail inbox ;-)

**Comment by ddnexus** [comment]
Hi Chris,
I played a bit with the simplest option and it looks like it works:
```sh
$ bundle exec webpacker:install:erb
```
file "pagy.js.erb"
```erb
<%= Pagy.root.join('javascripts', 'pagy.js').read %>
```
"application.js"
```js
import Pagy from './pagy.js.erb'
window.pagy = Pagy
```
Not sure that is the right way to expose the `Pagy` namespace, but it works.
The advantage is that when you upgrade the pagy gm, the `pagy.js` will be the right one.

**Comment by ddnexus** [comment]
Or even simpler:

file `app/javascript/src/javascripts/pagy.js.erb`

```
<%= Pagy.root.join('javascripts', 'pagy.js').read %>
global.Pagy = Pagy
global.PagyInit = PagyInit
```
file `app/javascript/packs/application.js`

```js
import '../src/javascripts/pagy.js.erb'
```

**Comment by cseelus** [comment]
Yes, using the erb loader is something I wanted to try anyhow, looks very clean!

**Comment by cseelus** [comment]
Not shure about the performance impact of using the erb loader though, will test that soon …

**Comment by ddnexus** [comment]
The impact is negligible for a file that size and no interpolation. Besides it affects only the build, so it's only involved at compile time, and probably just the first time, since the file will not change, but even if it would re-build it at every build... it's negligible and not affecting the production env.

I am going to add the instruction to the doc and close this ticket. Feel free to reopen it if there will be a better solution in the future. Thanks.
