### ISSUE TITLE
Untested methods

### ISSUE THREAD

**Issue by bquorning** [ddnexus/pagy#13]
It would be nice to have a more comprehensive test suite. The following methods aren’t covered by the current tests:

 - `Pagy::Frontend#pagy_nav`
 - `Pagy::Frontend#pagy_url_for`
 - `Pagy::Frontend#pagy_link_proc`
 - `Pagy::Backend#pagy`
 - `Pagy::Backend#pagy_get_vars`
 - `Pagy::Backend#pagy_get_items`

**Comment by ddnexus** [comment]
Yeah, it would be nice... and it would be even better having a PR contributed by some good soul... ;)

**Comment by gamafranco** [comment]
So, we're done to just this issue? 👏 👏 👏

**Comment by ddnexus** [comment]
Thanks to the great guys who contributed with PRs and with reporting issues and feature requests, we just got out the v0.8.0 which has a few more useful features, it is a bit faster and uses even a bit less memory! 

I've just run the benchmarks and I was not expecting that even after adding new stuff the performance got improved!

**Comment by ddnexus** [comment]
Pagy::Frontend methods are all tested. Missing Pagy::Backend methods.

**Comment by gamafranco** [comment]
🎉 🎉 🎉 🎉 🎉
