### ISSUE TITLE
Related gem for API pagination

### ISSUE THREAD

**Issue by twnaing** [ddnexus/pagy#132]
The following gem is relevant for [this section of documentation, How to - adding HTTP headers](https://github.com/ddnexus/pagy/blob/master/docs/how-to.md#adding-http-headers)

[Paginate Responder](https://github.com/jgraichen/paginate-responder) - A Rails pagination responder with link header support. It includes integration with pagy and other pagination gems.

**Comment by ddnexus** [comment]
Thanks. I will add it. However, I may also implement a little helper that you can use to add your own headers without the need of other gem dependencies.
