### ISSUE TITLE
Overflow: empty_page doesn't work

### ISSUE THREAD

**Issue by VladislavShved** [ddnexus/pagy#135]
`pagy, tags = pagy(tags, items: Tag.per_page, page: params[:page], overflow: :empty_page)`

I have set `overflow` param to `:empty_page`, but I still get exception if I pass page > page_count.

I think that because of it 
`@page <= @last or raise(OverflowError.new(self), "expected :page in 1..#{@last}; got #{@page.inspect}")`

**Comment by ddnexus** [comment]
Did you also `require 'pagy/extras/overflow'`?

**Comment by VladislavShved** [comment]
> Did you also `require 'pagy/extras/overflow'`?

Yes, I've tryied, but the same

**Comment by ddnexus** [comment]
That is really weird then. Please, ensure:

1. `require 'pagy/extras/overflow` in the pagy initializer
2. remove the redundant default variables (just to make things simpler) `pagy, tags = pagy(some_scope)`
3. restart the app

If you still get the error, then please, share your complete pagination-related code, error and backtrace.

**Comment by VladislavShved** [comment]
> That is really weird then. Please, ensure:
> 
> 1. `require 'pagy/extras/overflow` in the pagy initializer
> 2. remove the redundant default variables (just to make things simpler) `pagy, tags = pagy(some_scope)`
> 3. restart the app
> 
> If you still get the error, then please, share your complete pagination-related code, error and backtrace.

It's work for me! Thanks!
