### ISSUE TITLE
Pagy and scoped Searchkick

### ISSUE THREAD

**Issue by ThiagoCasao** [ddnexus/pagy#137]
Hi guys.

Thank you for a really good gem.

I am using Searchkick and pagination with Pagy. Everything works great, but when I use a scoped Searchkick, that returns the exactly data I want, pagy ignores it, and display all pages, even no data is returned.

The behavior is that Pagy is ignoring the scope.

I tried some configurations but none worked.

Need help to solve this.

Thanks in advance,

Thiago

Example:

`#escopes returns one record`
`@brands = Brand.search(term,
                           scope_results: ->(r) { r.from_organization(current_user.organization_id) },
                           page: params[:page],
                           per_page: 20,
                           order: { _score: :desc, name: :asc } )`
`#pagy shows n pages, to only one record displayed`
`@pagy = Pagy.new_from_searchkick(@brands, items: 20, page: params[:page])`

Image

![image](https://user-images.githubusercontent.com/3341391/54048399-725d0f00-41b8-11e9-8b13-2f5e84f7edc4.png)

**Comment by ddnexus** [comment]
I don't know how the `:scope_results` is supposed to work, but it looks like what you report has something to do with https://github.com/ankane/searchkick/issues/1088 ?

**Comment by ThiagoCasao** [comment]
Hi.

`:scope_results` apply Active Record scope on returned data from Elastic. This works fine in Searchkick.

In my case, I am suppose to separate record by tenants,  through `from_organization` scope. So, the data is showed correctly only by the correct tenant. However, Pagy paginates all the dataset returned from Elastic, ignoring the scope.

I saw the response from @ankane in  ankane/searchkick#1088 but I disagree. This is annoyng to my users, because they need to navigate much more to see they desired records.

Thank You.

**Comment by ddnexus** [comment]
I kind of disagree too, however it looks like there is nothing pagy can do in order to fix what searchkick decide to return, right?

**Comment by ThiagoCasao** [comment]
Oh, sorry! Of course! 

I thinked that response was from Pagy, no from Searchkick!

But I am confused, because the object returned from Searchkick contains only scoped data. This can be viewed in the image on the first comment. 

Is there a way that I can pass the Searchkick's object to Pagy to paginate only viewed results?

Thank You.

**Comment by ddnexus** [comment]
Did you try [new_from_searchkick](https://ddnexus.github.io/pagy/extras/searchkick#pagynew_from_searchkick)?

**Comment by ddnexus** [comment]
Not totally sure but the problem seems to be the total returned by searchkick, that is not referring to the scoped total, but to the result total, so despite what the items are, the pagy object get initialized with the wrong count.
If that is the case the `new_from_searchkick` will not work as it is now, but changing that should be easy.

**Comment by ThiagoCasao** [comment]
> Did you try [new_from_searchkick](https://ddnexus.github.io/pagy/extras/searchkick#pagynew_from_searchkick)?

Yes. I am using new_from_searchkick.

Studying better the results, I found that `@brands.count` returns 1. This is the desired behaviour.
But `@brands.hits.count` returns 63, in other words, all the records, skiping the scope. 

Maybe Pagy is basing in `@brands.hits` instead of `@brands.count`?

Analysis:
`@brands = Brand.search('*', scope_results: ->(r) { r.from_organization(1) }, page: 1, per_page: 20, order: { _score: :desc, nome: :asc } )
`
Count by hits:
`@brands.hits.count` = 20 (all records, paginated)

Count:
`@brands.count` = 1

Warning from Searchkick shows id ignoreds by scope:
![image](https://user-images.githubusercontent.com/3341391/54124844-3907e780-43e2-11e9-9eb4-bac83edab9e6.png)

**Comment by ddnexus** [comment]
We need just one integer out of the results: that must be the scoped count. If the count that you got is the actual count of the items in the page, then it is not useful. For example:

items per page: 10
results total count: 50
scoped count: 16
page-items: 10 in page 1 and 6 in page 2

Find a way to get 16 out of the results and the problem will be solved.

**Comment by ddnexus** [comment]
I've found the time to play a few minutes with the `scope_results`. 

It filters the results of **the retrieved page** with the scope. 

You can get the scoped count with `results.count` (where result is the `Searchkick::Results` object), and still retrieve the total count with `results.total_count`.

That means that if your unscoped results are for example 3 pages of 10 results each (30 in results.total_count), when you retrieve page #1 the 10 results for that page get filtered by the scope, so you might have just 3 `results.count`  for that page, and maybe you have 4 `results.count`  for page #2, and and another 5 `results.count` for page 3.

If you don't pass neither `page` nor `per_page` then you get the  default 10000 items per page, so it might look like a single paged) results where `results.count` would be 12 (in our example).

Pagy uses the `results.total_count` to initialize the pagy object, which looks correct. What doesn't look correct is the way you are trying to use the `scope_results`.

I am not sure what is the practical usage of the `scope_results`, but it is a post-filtering of the result already retrieved and it is not intended to be paginated. If you want that filter to produce full paged results (the 2 pages in our example: page 1 with 10 items and page 2 with 2 items) you should include the filtering in your initial query, and everything will work as you probably want.

Closing this issue as `invalid`. Please, open another issue in case you have some other suggestions or questions even related to the `scope_results`.
