### ISSUE TITLE
OFFSET-based paging is an anti-pattern

### ISSUE THREAD

**Issue by connorjacobsen** [ddnexus/pagy#14]
While simpler, `OFFSET`-based paging has a number of big issues. If this library is intended to be a toy, the current implementation is fine. If you want serious users, it won't work. At least consider providing some sort of interface for non-offset-based pagination if you want to leave the default.

tldr
- The offset is recomputed each time, so you can get page drift (duplicate data)
- Response times get worse with each page

For more details: https://use-the-index-luke.com/sql/partial-results/fetch-next-page

Offending line: https://github.com/ddnexus/pagy/blob/master/lib/pagy/backend.rb#L21

**Comment by ddnexus** [comment]
@connorjacobsen: Thank you for sharing that interesting article.

That line tries to be simple to understand for everybody and usable out of the box for a number of ORMs. It is indeed  "the default" in a method which only _raison d'être_ is being easy to override in the user controller, as "some sort of interface for" _any_ specialized pagination the user might need/prefer.

It is explained in the [method own doc](https://ddnexus.github.io/pagy/api/backend#pagy_get_itemscollection-pagy). Even the module itself is meant to be just a quick way to get some quick and ready-to-use method to paginate and that you could even replace its use by a 2 lines method, as explained in the first 3 paragraphs of [that page](https://ddnexus.github.io/pagy/api/backend).

That said, if you can suggest any better but broad way to provide the retrieval of the page items, you are very welcome!

Fixing the issue #3, there will be the encouraged practice to use a specific dedicated pagy method to handle specific collection types (i.e. Arrays, elasticsearch results, special ORM cases, etc.). I am about to push the first version that will include that feature, and I would be delighted to add a non-offset based extra as a ready-to-use alternative. If you are willing to contribute, that wold be a very welcome addition.

**Comment by ddnexus** [comment]
@connorjacobsen I read the article and it doesn't look like something that could work in any ORMs. It requires quite a few specific details that must be specifically implemented.

As I said in my previous message, pagy makes the customization of the `pagy_get_items` very easy, so that is not an issue. I am going to close this now also because I didn't have any feedback from anybody in days.
