### ISSUE TITLE
pagy_bootstrap_compact_nav working fine, pagy_bootstrap_responsive_nav is blank

### ISSUE THREAD

**Issue by evamedia** [ddnexus/pagy#140]
I have setup Page fine, adding the extras. If i use the compact extra it displays fine, trying the responsive extra and it's empty, inspect the html it creates the nav-id but there is no btn-group created.

I was of the understanding that require 'pagy/extras/bootstrap' in my page.rb should load compact and responsive, am a bit lost.

**Comment by ddnexus** [comment]
I hope you found out the problem by yourself. Missing the Javascript initialization?

**Comment by evamedia** [comment]
The event listener I think, still not working in production as it does in development, assumed it was the initializer needing reloading, but rebooted server and still the same

**Comment by ddnexus** [comment]
Which event listener are you using?
Production not working with Javascript makes me think to `asset:precompile`. Did you re-compile?

**Comment by evamedia** [comment]
window.addEventListener("turbolinks:load", Pagy.init);

My Capistrano job runs precompile on every deploy. 

It is actually adding items if you drag browser width to maximum, it’s almost like it’s ignoring that the first breakpoint exists, so at mobile size the pagination is wider than the viewport



Dev on left, production on right

**Comment by ddnexus** [comment]
OK, so let's recap (correct me if I am wrong):

- in dev mode it works
- in prod mode it doesn't
- when it doesn't work:
    - the nav is initially empty
    - after a resize the nav gets populated 
    - after the first correct rendering... does it works or not?

**Comment by evamedia** [comment]
> in dev mode it works
Yes
> in prod mode it doesn't
Partially
> when it doesn't work:
> the nav is initially empty
No
> after a resize the nav gets populated
Always populated 
> after the first correct rendering... does it works or not?
Partially, it will add items as the window gets wider, but when made smaller, or first rendered at minimum browser width it doesn’t remove enough items to fit the view

**Comment by ddnexus** [comment]
Another question that I added later: is there any difference in different browsers and different initial sizes?

BTW if I understand correctly, in production the only differences are:
- the breakpoints behave differently than in dev
- the problem appear to be related to the small size (first breakpoint?)
- do bigger size work well?

**Comment by evamedia** [comment]
> Another question that I added later: is there any difference in different browsers and different initial sizes?
> 
Initial size makes no difference, issue not appearing in Safari, but does in Chrome and Firefox (worse in Firefox as browser window goes smaller)
> BTW if I understand correctly, in production the only differences are:
> 
> the breakpoints behave differently than in dev
Yes
> the problem appear to be related to the small size (first breakpoint?)
Yes
> do bigger size work well?

Yes

**Comment by ddnexus** [comment]
That's interesting.
Can we check if there is no difference in the bootstrap breakpoints settings between the dev and prod?
Could you share a minimal app with that settings in order to reproduce the issue?

**Comment by evamedia** [comment]
> That's interesting.
> Can we check if there is no difference in the bootstrap breakpoints settings between the dev and prod?
> 
Definitely the same
> Could you share a minimal app with that settings in order to reproduce the issue?
> 
Could give you access to whole app if you like(ssh details, bitbucket repository), it’s a complete rewrite of an existing site, so the production server is not being used by anyone but me at the moment

**Comment by ddnexus** [comment]
That would work... let's start with adding my email-address to the bitbucket repo, so I could clone it an try it locally. Thanks.

**Comment by ddnexus** [comment]
Maybe also the web address/access to the deployed app, so if I am lucky I don't even have to run the app locally, but use the deployed one.

**Comment by ddnexus** [comment]
One thing that I notice: the pagy breakpoints in the initializer are probably a problem (although doesn't explain the difference dev/prod). Did you try to change that?

**Comment by evamedia** [comment]
I tried them at the defaults, but it seemed to make no difference

**Comment by evamedia** [comment]
Have mailed you details

**Comment by ddnexus** [comment]
That are not a default! they are just a **bad** example. Sorry. I should change that, because the width values are crazy small! You should sync them with the standard width of the bootstrap breakpoints. Please, can you try that?

**Comment by evamedia** [comment]
Thank you, that has fixed it

**Comment by ddnexus** [comment]
Great! Could you post the breakpoints? Are they synced with the bootstrap breakpoints that you use?

**Comment by evamedia** [comment]
too soon, it works on initial load, but as you go through the pages it gets wider and wider than the viewport

this is what I tried

> Pagy::VARS[:breakpoints] = { 0 => [1,2,2,1], 576 => [2,3,3,2], 720 => [3,4,4,3] }

**Comment by ddnexus** [comment]
Not sure to understand "wider and wider than the viewport". Do you mean that the pagy `:size` for the breakpoint is not respected?

**Comment by ddnexus** [comment]
Please, take a look at this page https://bootstrapcreative.com/bootstrap-4-media-queries/ and use the container widths as the reference. The pagy nav applied breakpoint depends on the container width, so please ensure that the container would snap at different widths correctly even without the pagy nav in it.

**Comment by evamedia** [comment]
Will do, should have some time later this evening
