### ISSUE TITLE
No output (Limit 0, Offset 0) when num_items = per page size

### ISSUE THREAD

**Issue by MSeneadza** [ddnexus/pagy#15]
I think this line has a bug in it.  
https://github.com/ddnexus/pagy/blob/b18f254d6dd985bc36f1589d09f9a11cae495e8e/lib/pagy.rb#L33

I've run into the situation where I have exactly 50 items and my per_page is also 50.  In that case I get zero results output.  If I change my per_page to 25, then I get 2 pages of output.

**Comment by ddnexus** [comment]
Yes sir! That is a bug. Thank you!

FYI: In order to be able to paginate pre-paginated collections (with offset and limit), the items of the last page should be adjusted to the actual items in the last page. That logic is correct. What is not correct is the implementation!

**Comment by ddnexus** [comment]
40331bc
