### ISSUE TITLE
The link to migration practical guide in README is broken

### ISSUE THREAD

**Issue by ohlincik** [ddnexus/pagy#150]
The link **Migrating from WillPaginate and Kaminari (practical guide)** under [Posts and Tutorials section](https://github.com/ddnexus/pagy#posts-and-tutorials) in README is broken and results in a 404 File not found.

**Comment by ddnexus** [comment]
Fixed! Thank you!

**Comment by ohlincik** [comment]
Of course! Thanks for fixing so quickly.
