### ISSUE TITLE
Too many page numbers shown in pagy_info at start and end of sequence

### ISSUE THREAD

**Issue by reggieb** [ddnexus/pagy#152]
I have set the `size` to `[1,1,1,1]` to give me the first page number, then the ones before and after the current page, and then the last page. This works perfectly in the middle of the sequence:

![pagy-mid-sequence](https://user-images.githubusercontent.com/213040/55615822-4cf7fc80-5788-11e9-843b-1eb3b185469b.png)

But at either end of the sequence I'm getting an extra page number appearing. For example near the start I'm getting:

![pagy-start-sequence](https://user-images.githubusercontent.com/213040/55615816-49fd0c00-5788-11e9-9699-34a62e28c9c6.png)

I was expecting: 1..3,4,5..16

I think the total number of page numbers shown should be equal to the sum of the numbers in the `size` array plus one (for the current page). So with `[1,1,1,1]` that's 4 + 1 = 5 

With 20 pages and `[]` around the current page the sequence should be:

- [1],2,3,4..20
- 1,[2],3,4..20
- 1,2,[3],4..20
- 1..3,[4],5..20
- 1..4,[5],6..20

  ...
- 1..15,[16],17..20
- 1..16,[17],18..20
- 1..17,[18],19,20
- 1..17,18,[19],20
- 1..17,18,19,[20]

**Comment by ddnexus** [comment]
From the [doc](https://ddnexus.github.io/pagy/api/pagy):

Notice: A :gap is added only where the series is missing at least two pages. When the series is missing only one page, the :gap is replaced with the page link of the actual missing page. That’s because the page link uses the same space of the ... gap but it is more useful.

**Comment by reggieb** [comment]
It's a shame this isn't configurable.

**Comment by ddnexus** [comment]
What is the logic of adding an artificial interruption in a series when you can use the same space to avoid the interruption?

`1 … 3 4 5`
`1 2 3 4 5`

Or you think that the non-clickable `…` is more useful than the `2` link?

Anyway, just comment out the following line and you will get what you want:

https://github.com/ddnexus/pagy/blob/15732da3455c6eff533ada181471b443be2b787c/lib/pagy.rb#L43

**Comment by reggieb** [comment]
I have a designer who has specified the former. I'll get my persuasion hat on and see what I can do. I'd rather not have to run a patched version of the gem.

Thank you for the quick response.

**Comment by ddnexus** [comment]
You could also tell the designer to get his/her persuasion hat on and see if s/he can convince me that there is some advantage in displaying an inactive ellipsis instead of an active link in the same space. I currently don't see any.

**Comment by reggieb** [comment]
I wonder if you could use a Proc to define the series calculations. So wrap the current logic into a proc and use that in `Proc#series`. Then allow series calculation proc selection to be overwritten in the configuration. I could put a PR together if you like.

**Comment by ddnexus** [comment]
I think you have a few better options:

1. monkey-patching in the initializer  
2. sub-classing 
3. writing an extra just for that

I am really really reluctant to add a proc for a method that long or a proc called in that method, and even add a variable flag, since again,  someone should show me an advantage first.

**Comment by reggieb** [comment]
OK - fair enough.
