### ISSUE TITLE
Having trouble with installation

### ISSUE THREAD

**Issue by bhavyabh** [ddnexus/pagy#157]
We have successfully installed Pagy, and it IS working on the posts/index page.  But now, we see that the tags page is giving us this error---and this error did not exist prior to installing Pagy.

![image](https://user-images.githubusercontent.com/34382500/57160452-d36b2280-6db6-11e9-8b73-27aad6aa621d.png)

What's odd is that the method DOES exist.  And of course it did because it was working before.  Here is the method:

 ```
 def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end
```

Do we have to somehow add @pagy here somewhere?

This is how we set things up in the post controller:

```
  def index
    @profile = current_user.profile
    if params[:tag]
      @pagy, @tag   = Tag.find_by(name: params[:tag])
      @pagy, @posts = Post.tagged_with(params[:tag]).order(created_at: :desc)
    else
      @pagy, @posts = pagy(Post.order(created_at: :desc), items: 20)
    end
  end
```

We tried it with @pagy in front of @tag, as you see here, and also without.

We are really hoping that you can help us figure out why Pagy might be causing this error.  Thank you very much!

**Comment by monroemann** [comment]
Yes, thank you @bhavyabh for doing this.  @ddnexus Bhavya works with me on our volunteer coding team at Break Diving.  We are both trying to figure out this issue.  If you recall, I am a member of GoRails--we had everything working great until today when we noticed that the tags no longer work when you click on them.  Hoping that what we've provided makes sense and is enough to help you ascertain our issue!  Thank you!

**Comment by monroemann** [comment]
@ddnexus I just found the error.  You can delete this now.  @pagy doesn't need to go in front of @tag and we forgot the pagy() on the right side of line that now reads:

`@pagy, @posts = Post.tagged_with(params[:tag]).order(created_at: :desc)`

Sometimes just writing it out we are able to find the errors ourselves (and that now seems so obvious).  Thank.  

You can close this issue now.  Solved! :D

**Comment by ddnexus** [comment]
It's really easy to support users that solve their own problems! :)
Glad that you got it working.
