### ISSUE TITLE
Purpose of hidden links like ...page=-pagy-12345...?

### ISSUE THREAD

**Issue by MSeneadza** [ddnexus/pagy#158]
Yesterday I upgraded to Pagy 3.0 and switched my pagination over to use `pagy_bootstrap_combo_nav_js`.  Shortly thereafter I started getting server errors like this: `ArgumentError: expected :page >= 1; got "-pagy-2090527552074306646-"` . The errors are all from crawlers which are following those links.

I see in my pagination markup that there are links like this being generated: `<a href="/stock-trading-articles?page=-pagy-2090527552074306646-"   style="display: none;" ></a>`  What's the purpose of those links?  Is it possible to suppress them?

**Comment by ddnexus** [comment]
@MSeneadza that are sort of link-templates that are used to generate the actual link to the page by replacing the `-pagy-0000...-` with the actual page number. The technique is easy to implement and fast to execute, but I completely overlooked the fact that crawlers could follow them, and that has to be addressed.

The first fix that comes to mind is adding a `rel="nofollow" to that links. Please, could you try to temporarily override the helper by copying the method below and pasting it  in your application controller?

```ruby
    def pagy_bootstrap_combo_nav_js(pagy, id=pagy_id)
      link, p_prev, p_next, p_page, p_pages = pagy_link_proc(pagy), pagy.prev, pagy.next, pagy.page, pagy.pages

      html = %(<nav id="#{id}" class="pagy-bootstrap-combo-nav-js pagination" role="navigation" aria-label="pager">) \
             + link.call(MARKER, '', %(style="display: none;" rel="nofollow" ))
        (html << link.call(1, '', %(style="display: none;" rel="nofollow" ))) if defined?(TRIM)
        html << %(<div class="btn-group" role="group">)
        html << (p_prev ? link.call(p_prev, pagy_t('pagy.nav.prev'), 'aria-label="previous" class="prev btn btn-primary"')
                        : %(<a class="prev btn btn-primary disabled" href="#">#{pagy_t('pagy.nav.prev')}</a>))
        input = %(<input type="number" min="1" max="#{p_pages}" value="#{p_page}" class="text-primary" style="padding: 0; border: none; text-align: center; width: #{p_pages.to_s.length+1}rem;">)
        html << %(<div class="pagy-combo-input btn btn-primary disabled" style="white-space: nowrap;">#{pagy_t('pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages)}</div>)
        html << (p_next ? link.call(p_next, pagy_t('pagy.nav.next'), 'aria-label="next" class="next btn btn-primary"')
                        : %(<a class="next btn btn-primary disabled" href="#">#{pagy_t('pagy.nav.next')}</a>))
      html << %(</div></nav>#{pagy_json_tag(:combo_nav, id, MARKER, p_page, !!defined?(TRIM))})
    end
```

Please, let me know if it fixes the problem, so I will push the fix to all the frontend combo methods in pagy.

Thanks
dd

**Comment by ddnexus** [comment]
In alternative you can also try the `crawler-fix` branch.

**Comment by MSeneadza** [comment]
@ddnexus Thanks for the quick response & fix.  I installed the `crawler-fix` branch last night -- about 16 hours ago. When I installed the fix it had been 9 hours since a crawler had followed one of the original hidden links.  

There were no instances of that ArgumentError until a few minutes ago.  Google just tried to crawl one of those links 6 times.  These were the first errors for that page but I have no idea when Google first noticed the link -- it could have been seconds before I got the errors or 24 hours ago.

**Comment by MSeneadza** [comment]
So I just tried replacing

`+ link.call(MARKER, '', 'style="display: none;" rel="nofollow"')` 

with 

`+ ''`

As far as I can tell the paginator looks the same and seems to function just fine.  What functionality would I lose if I just got rid of `+ link.call(MARKER, '', 'style="display: none;" rel="nofollow"')` ?

**Comment by ddnexus** [comment]
> As far as I can tell the paginator looks the same and seems to function just fine.

Really? That is the link that the javascript will use to replace the `MARKER` string with the real page number and then "click" in order to go to the page. I really doubt that anything will work without it.

Are you sure that you are not modifying something that is not used in the real page? Please check the generated HTML source to confirm.

- Also check that your server doesn't have some cached instance of the old process, or resumed an old one under heavy traffic: that would also explain how google followed the link that in that case was not a "nofollow" link.

- Another possibility would be that the "nofollow" is missing somewhere or has a typo. We should also check that.

- According to Google there is also another possibility:

    > Essentially, using No Follow causes us to drop the target links from our overall graph of the web.
However, the target pages may still appear in our index if other sites link to them without using No Follow, or if the URLs are submitted to Google in a Sitemap. and the most probable explanation is that google reached your no-follow link through another site.

- And another possibility is that some other search engine is not stopped by the "nofollow", but in this case you said it's Google.

Please, check all that, and keep monitoring your log for some day, so we may have a better idea.
If that will not be a viable solution, I will try to implement a different way to do the same.

**Comment by ddnexus** [comment]
I have found 2 solutions that will avoid the bogus link. I will implement the best one ASAP.

**Comment by ddnexus** [comment]
@MSeneadza Pushed the v3.1.

**Comment by MSeneadza** [comment]
@ddnexus thanks!

**Comment by MSeneadza** [comment]
FYI, I upgraded to v3.1 and now I'm getting a slightly different error:

![Screenshot 2019-05-08 17 05 16](https://user-images.githubusercontent.com/1416050/57408458-b6b65c80-71b3-11e9-9e2c-901ee615da6f.png)

markup is: `<nav id="pagy-77e45606acc6afe7e6c935f9e07b534cce8d99dc" class="pagy-bootstrap-combo-nav-js pagination" role="navigation" aria-label="pager"><div class="btn-group" role="group"><a class="prev btn btn-primary disabled" href="#">&lsaquo;&nbsp;Prev</a><div class="pagy-combo-input btn btn-primary disabled" style="white-space: nowrap;">Page <input type="number" min="1" max="1141" value="1" class="text-primary" style="padding: 0; border: none; text-align: center; width: 5rem;"> of 1141</div><a href="/stock-trading-articles?page=2"   rel="next" aria-label="next" class="next btn btn-primary">Next&nbsp;&rsaquo;</a></div></nav><script type="application/json" class="pagy-json">["combo_nav","pagy-77e45606acc6afe7e6c935f9e07b534cce8d99dc",1,{"standard":"<a href=\"/stock-trading-articles?page=--pagy.page--\"   style=\"display: none;\"></a>"}]</script>`

**Comment by ddnexus** [comment]
I don't know RollBar and I don't understand how you may get that error.

1. The url is now just a string in a JSON object. That is not in the HTML DOM elements anymore. The HTML does not have that link.
2. The "--pagy.page--" string gets replaced by the actual page number in the javascript BEFORE becoming a DOM object added to the NAV, so it will never happen to be a real URL unless the replacement occurs.
3. That URL should never get requested. If it does, then the `replace` below didn't work and we have to find why. https://github.com/ddnexus/pagy/blob/29a6876a9f221dec3e377e614b75fa425ca368eb/lib/javascripts/pagy.js#L65

Could you reproduce that by interacting with any browser, and let me know?

**Comment by MSeneadza** [comment]
Rollbar.com is an error capturing & reporting service.  So that's where my Rails app sends its exceptions.

I've only seen these exceptions triggered by bots.  My users and I use paginated pages on my site constantly and it's only bots which are triggering these exceptions.  In the case of these latest ones the user agent was: `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`

I can only assume that Google is being *smart* and decided that was a link which needed to be followed, despite it being inside that JSON object. 

Please let me know how/if I can help to debug this.

**Comment by ddnexus** [comment]
It looks like Google will follow anything looking like a link, no matter where it finds it.

I just did a little refactoring changing the marker strings as `"__pagy_page__"` and `"__pagy_items__"` and other small improvements in the `pagy.js`, now pushed to the `3.1.1` branch.

A simple solution to prevent the error (with the new strings) is adding something like the follow to the robots.txt:

```
User-agent: *
Disallow: *__pagy_page__
Disallow: *__pagy_items__
```

I validated it with an online robots.txt validator and it should work with all the bots. could you try the branch and confirm whether it works? Thanks.

**Comment by MSeneadza** [comment]
I just pushed 3.1.1 to production along with an updated robots.txt.  This should do the trick.

Thanks again.

**Comment by ddnexus** [comment]
Let's see...

**Comment by MSeneadza** [comment]
So it's been about 23 hours since I pushed to production.  Google followed one of those links about 20 hours ago but no hits since then.  For now I'll assume that one hit was because Google had not yet re-processed my robots.txt at that time.

**Comment by ddnexus** [comment]
Finally great news!

I made further refactorings to helpers and javascripts for better support of the trim extra and now the code is better. The `robot.txt` will need only the `*__pagy_page__` line. I will release the 3.2 ASAP with the updated doc about the `robot.txt` entries.

 Thank you!

**Comment by ddnexus** [comment]
Pushed 3.2.0 to rubygems.

**Comment by MSeneadza** [comment]
FYI (and a note for anybody else who may be having these issues)... I'm still not seeing the new marker links get followed, which is great.  However today Bing started hitting the old marker links.  I guess they indexed my pages last week and are just now getting around to processing links that *were* on the page.  So I've started blocking URIs with `-pagy-` in them via my rack-attack ( https://github.com/kickstarter/rack-attack ) file

**Comment by ddnexus** [comment]
The fact that you use `-pagy-` means they are old links. now it is `__pagy_page__`. Can you post one link to confirm is an old pagy format?

**Comment by MSeneadza** [comment]
Right, I said they were old. Likely due to Bing indexing those pages last week

**Comment by ddnexus** [comment]
Ok so I will add a couple of notes in the doc, exposing the problem of old indexed links and the solution you pointed out. Thank you.
