### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by antwonlee** [ddnexus/pagy#159]
I researched the issues but couldn't find the solution.

I am looking at this document https://ddnexus.github.io/pagy/extras/support.html to implement the infinite scroll with pagy.  

I am trying to expand the page with more results other than page reloading to ?page=1, ?page=2, ?page=3, etc.  

What am I missing here?  How can I just append the results from previous results?  Let me know if I am not implementing this correctly

```ruby
def index
 @pagy, @jobs = pagy_countless(Job.published, count: 25, items: 5, cycle: true)
end
```

**Comment by ddnexus** [comment]
The statement you are using is a cycling and fixed number of pages. That will cause a cycle of 5 pages of 5 items. that means, 1-2-3-4-5-1-2-3-4-5-1-2-3-... 

Is that what you are trying to do? Maybe you should look at the Naveless/Incremental or Auto-incremental examples that seems to behave like you would like.

BTW, this doesn't look like a Pagy issue, but a support request. Please use [gitter](https://gitter.im/ruby-pagy/Lobby) if you need more support.
