### ISSUE TITLE
What's the most efficient way to paginate multiple collections in a single page?

### ISSUE THREAD

**Issue by JamesChevalier** [ddnexus/pagy#161]
Everything is working great, thanks for such a performant gem!

I've got a page that has two Pagy instances, and since all the data is flowing through a single controller action I'm effectively paginating both sets of data each time. Here's a short example action:

```ruby
def show
  @user                   = User.find(params[:id])
  @pagy_poems, @poems     = pagy(@user.poems, link_extra: "data-remote='true'", page_param: :page_poems)
  @pagy_stories, @stories = pagy(@user.stories, link_extra: "data-remote='true'", page_param: :page_stories)
  return if request.format.js? || request.format.json?
  # other code that's required for initial page load but not for pagination goes here
end
```

If I click through the 'next' links for `@stories`, it's also running the queries for `@poems`.

I can wrap each `pagy` line in its own `params[:page_poems]`/`params[:page_stories]` check, but I've found that if I click the 'next' link for `@poems` and then click the 'next' link for `@stories` then both params are passed to the controller.
Is there a better way to handle this, or is that as efficient as I can get?

I looked through [the pagy_combo_nav_js code](https://github.com/ddnexus/pagy/blob/master/lib/pagy/extras/navs.rb#L24-L35) and it doesn't seem possible to pass custom URLs e.g. `<%== pagy_combo_nav_js(@pagy_poems, url: user_poems_path(@user)) %>` because it's relying on [request.path](https://github.com/ddnexus/pagy/blob/87d008c71929c8d1937486da8ee02ccd353ea842/lib/pagy/frontend.rb#L17) (potentially for compatibility).

**Comment by ddnexus** [comment]
If you are displaying the 2 sets of paginated record and pagination links in the same page at the same time with a single request, you need one action that runs the 2 queries.

But I see that you are using `'data-remote="true"'`, which makes me think that you should populate the record and pagination nav for each set separately, i.e. with 2 independent AJAX requests. That would even avoid the use of `:page_param`.

**Comment by JamesChevalier** [comment]
Hm. Maybe I'm doing this async pagination wrong, then.
Here's an over-simplified example of my view files (which pairs with the example `show` action above). With this setup, I don't seem to have the option of splitting poem/story pagination into multiple actions.

In this example below, I find that the initial page load populates the first page of poems/stories and then clicking the 'next' button for either list routes back through the same `show` action, into the `show.js.erb` file.

`show.html.erb`:
```erb
<div id="paginated-poems-container">
  <%= render 'paginated_poems', poems: @poems, pagy: @pagy_poems %>
</div>

<div id="paginated-stories-container">
  <%= render 'paginated_stories', stories: @stories, pagy: @pagy_stories %>
</div>
```

`show.js.erb`:
```js
<% if @poems %>
  document.getElementById('paginated-poems-container').innerHTML = "<%= j(render 'paginated_poems', poems: @poems, pagy: @pagy_poems) %>";
  Pagy.init(document.getElementById('paginated-poems-container'));
<% end %>

<% if @stories %>
  document.getElementById('paginated-stories-container').innerHTML = "<%= j(render 'paginated_stories', stories: @stories, pagy: @pagy_stories) %>";
  Pagy.init(document.getElementById('paginated-stories-container'));
<% end %>
```

`_paginated_poems.html.erb`:
```erb
<%== pagy_combo_nav_js(pagy) %>

<% poems.each do |poem| %>
  <%= render 'poem', poem: poem %>
<% end %>
```

`_paginated_stories.html.erb`:
```erb
<%== pagy_combo_nav_js(pagy) %>

<% stories.each do |story| %>
  <%= render 'story', story: story %>
<% end %>
```

**Comment by ddnexus** [comment]
> Maybe I'm doing this async pagination wrong, then.

Yes indeed. You are not doing async at all. :)

Sorry, but this is not a pagy issue: it is a support request, and it is not even pagy-specific. I would suggest you to research (google for "rails ajax render"), or ask in some forum, and eventually use the [Pagy Support on Gitter](https://gitter.im/ruby-pagy/Lobby) for specific pagy support.

HTH

**Comment by JamesChevalier** [comment]
Oh! I see - I'll have to do the initial ajax data load on my own. I thought Pagy was going to handle that for me because of how much `pagy_combo_nav_js` is doing already. 😬 

Thanks again!
