### ISSUE TITLE
Incorrect COUNT (*)

### ISSUE THREAD

**Issue by 9mm** [ddnexus/pagy#165]
This took me forever to find this bug, but it appears Pagy for whatever reason is calling the completely wrong query...

Here is the AR query which is the culprit. I am using lots of explicit typing rather than fancy rails way because I have some pretty complex queries and I like them to look homogenous (although in this case the INNER JOINs are quite vanilla):

    invoices = Invoice
      .select('invoices.*')
      .select('sum(line_items.amount) AS balance_due')
      .select('tenants.first_name AS tenant_first_name, tenants.last_name AS tenant_last_name')
      .joins('INNER JOIN properties ON properties.id = invoices.property_id')
      .joins('INNER JOIN users tenants ON tenants.id = invoices.user_id')
      .joins('INNER JOIN line_items ON line_items.invoice_id = invoices.id')
      .joins('INNER JOIN accounts ON accounts.id = line_items.account_id')
      .where('properties.company_id = ?', company_id)
      .where('invoices.created_at >= ?', start_date)
      .where('invoices.created_at <= ?', end_date)
      .where('accounts.is_accounts_receivable = TRUE')
      .group('invoices.id, tenants.first_name, tenants.last_name')
      .order('invoices.created_at DESC')

Most important part is `.select('sum(line_items.amount) AS balance_due')`

Here is the proper query:

```
SELECT  invoices.*, sum(line_items.amount) AS balance_due, tenants.first_name AS tenant_first_name, tenants.last_name AS tenant_last_name FROM "invoices" INNER JOIN properties ON properties.id = invoices.property_id INNER JOIN properties_users ON properties_users.property_id = properties.id INNER JOIN users managers ON managers.id = properties_users.user_id INNER JOIN users tenants ON tenants.id = invoices.user_id INNER JOIN line_items ON line_items.invoice_id = invoices.id INNER JOIN accounts ON accounts.id = line_items.account_id WHERE (properties.company_id = 1) AND (managers.id = 3) AND (invoices.created_at >= '2019-06-01 04:00:00') AND (invoices.created_at <= '2019-07-01 03:59:59.999999') AND (accounts.is_accounts_receivable = TRUE) GROUP BY invoices.id, tenants.first_name, tenants.last_name ORDER BY invoices.created_at DESC LIMIT 1 OFFSET 0
```

Here is what Pagy generates... notice `balance_due` is missing

```
SELECT COUNT(*) AS count_all, invoices.id, tenants.first_name, tenants.last_name AS invoices_id_tenants_first_name_tenants_last_name FROM "invoices" INNER JOIN properties ON properties.id = invoices.property_id INNER JOIN properties_users ON properties_users.property_id = properties.id INNER JOIN users managers ON managers.id = properties_users.user_id INNER JOIN users tenants ON tenants.id = invoices.user_id INNER JOIN line_items ON line_items.invoice_id = invoices.id INNER JOIN accounts ON accounts.id = line_items.account_id WHERE (properties.company_id = 1) AND (managers.id = 3) AND (invoices.created_at >= '2019-06-01 04:00:00') AND (invoices.created_at <= '2019-07-01 03:59:59.999999') AND (accounts.is_accounts_receivable = TRUE) GROUP BY invoices.id, tenants.first_name, tenants.last_name ORDER BY invoices.created_at DESC
```

**Comment by 9mm** [comment]
https://github.com/ddnexus/pagy/issues/130

**Comment by 9mm** [comment]
Here's how I solved it, for people in the future seeing this:

```
  def self.custom_count(query)
    # to fix issue in Rails/pagy where it doesn't know how to count custom aggregate selects
    Invoice.from("(#{query.to_sql}) invoices_with_balances").count
  end
```

Ghetto, but good enough... I really dont understand why rails can't do this on its own though. if theres now HAVING() clause then i imagine it would just be fine to strip all the custom selects and do it how I did above...

**Comment by ddnexus** [comment]
So it looks like pagy has nothing to do with the problem after all. ;)

That should be one of the cases covered by the [Custom Count for Custom Scopes](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes) section.
