### ISSUE TITLE
Searchkick items params, ignoring pagination params passing

### ISSUE THREAD

**Issue by bestwebua** [ddnexus/pagy#168]
Hello! Thanks for nice gem. Yesterday I have faced with pagination bug in searchkick+pagy bundle. It was bug with passing pagination searchkick params, and using items size from controller params. That is my propose to fix it. Cheers!

File: pagy/lib/pagy/extras/searchkick.rb

```ruby
# See the Pagy documentation: https://ddnexus.github.io/pagy/extras/searchkick
# encoding: utf-8
# frozen_string_literal: true

require 'pagy/extras/pagy_search'

class Pagy

  # used by the items extra
  SEARCHKICK = true

  # create a Pagy object from a Searchkick::Results object
  def self.new_from_searchkick(results, vars={})
    vars[:items] = results.options[:per_page]
    vars[:page]  = results.options[:page]
    vars[:count] = results.total_count
    new(vars)
  end

  # Add specialized backend methods to paginate Searchkick::Results
  module Backend ; private

    # Return Pagy object and results
    def pagy_searchkick(search_args, vars={})
      model, term, options, block, *called = search_args
      vars               = pagy_searchkick_get_vars(nil, vars)
      options[:per_page] = vars[:items]
      options[:page]     = vars[:page]
      results            = model.search(**term, **options, &block) # fix with pagination params passing
      vars[:count]       = results.total_count
      pagy = Pagy.new(vars)
      # with :last_page overflow we need to re-run the method in order to get the hits
      if defined?(OVERFLOW) && pagy.overflow? && pagy.vars[:overflow] == :last_page
        return pagy_searchkick(search_args, vars.merge(page: pagy.page))
      end
      [pagy, called.empty? ? results : results.send(*called)]
    end

    # Sub-method called only by #pagy_searchkick: here for easy customization of variables by overriding
    # the _collection argument is not available when the method is called
    def pagy_searchkick_get_vars(_collection, vars)
      vars[:items] ||= (params[:items] || VARS[:items]).to_i # ability to use items size from params 
      vars[:page]  ||= (params[ vars[:page_param] || VARS[:page_param] ] || 1).to_i
      vars
    end

  end
end
```

**Comment by ddnexus** [comment]
Hi @bestwebua, that is not a bug.

If you want to pass the items params to pagy, you should use the [items extra](http://ddnexus.github.io/pagy/extras/items) which will take the default `:items` param (or your custom named params) into account in order to paginate with any arbitrary number of custom items.

HTH

**Comment by bestwebua** [comment]
Okay, so what about this line?
```ruby
results = model.search(**term, **options, &block)
```

**Comment by ddnexus** [comment]
I am not that familiar with sidekick. What is that line for?

**Comment by bestwebua** [comment]
If you want pass pagination params into searchkick method ```.search``` and get results, you should pass this params into one hash, for example:

```ruby
Product.search(where: {in_stock: true}, page: 1, per_page: 1)
```
But look at this line, you have passed 2 hashes instead one:
https://github.com/ddnexus/pagy/blob/389755bd2b8f600d675720adac6ca2426e486a81/lib/pagy/extras/searchkick.rb#L29

I think it should be like this:
```ruby
results = model.search(**term, **options, &block)
```

**Comment by ddnexus** [comment]
Indeed the current implementation is what I see in the github page of searchkick. For example:

```ruby
Product.search "apples", where: {in_stock: true}, limit: 10, offset: 50
```

If you happen to omit the term (`"apple"` in the example) it uses the `"*"` as default, but the method accepts 2 arguments: term and options. 

You can check the searchkick code [here](https://github.com/ankane/searchkick/blob/d889fa0a65b767be3c8e64a58a93b953498f7e00/lib/searchkick/model.rb#L42).

**Comment by ddnexus** [comment]
What may happen is that the optional nature of the term argument become mandatory in the pagy_search method. That should be reflected in the doc or better it should be changed so it will not be different from the searchkick search.

**Comment by bestwebua** [comment]
Maybe best fix is add the same behaviour for ```term``` parameter like in ```Searchkick.searchkick_search```? I have opened PR: https://github.com/ddnexus/pagy/pull/169, please check out.
