### ISSUE TITLE
Pagy without Last Page

### ISSUE THREAD

**Issue by RaresSalcudean** [ddnexus/pagy#175]
Hello,

I just started using Pagy and I found it to be AWESOME! 

We have multiple huge tables around ~600 million rows in each one, and I had to do quick pagination with around 100 items per page. 

We have 2 apps that communicate via APIs, in the first app I prepare the pagination object:

```
estimate_count = ActiveRecord::Base.connection.execute("SELECT reltuples::int AS approximate_row_count FROM pg_class WHERE relname = 'handicap_revisions';").first["approximate_row_count"]

pagy, handicap_revisions = pagy(HandicapRevision.includes(:golfer_only_fetch_name).all.order(created_at: :desc), count: estimate_count, items: 100)

```

And I send the `pagy` object via JSON.

On my second application, I receive the JSON payload and do the following:

```
pagy_attrs = @response["output"]["pagy"].deep_symbolize_keys #pagy object
@payload = @response["output"]["payload"] # array of hashes (rows)

@pagy = Pagy.new(pagy_get_vars(@payload, pagy_attrs[:vars]))
```

And the on the client-side (views):

`= raw pagy_bootstrap_nav(@pagy)`

The result:

<img width="716" alt="Screenshot 2019-08-14 at 16 13 21" src="https://user-images.githubusercontent.com/29229646/63023802-87984100-beae-11e9-9135-60fd0071cc20.png">

But I don't actually want to display the last page (link or counter), so I read the documentation and found no way to remove it.

I did a quick JQuery hack and deleted that `li`, e.g, `$('ul li.page-item:last-child').prev('li').remove()`.

Result:

<img width="626" alt="Screenshot 2019-08-14 at 16 13 36" src="https://user-images.githubusercontent.com/29229646/63023888-bd3d2a00-beae-11e9-9cf7-52b29597c0cc.png">

I tried to use `pagy_countless` or `pagy_array` but it did not work for my use case, usually, I got `undefined method prev for Array` or `undefined method offset for Array`.

Is there a way to display the pagination navbar without the last page? Even without the count query? - as you can see from my example I use an 'estimate count'. 

I didn't manage to do it with `pagy_countless` :( - Mainly because of my 'payload' / collection is an array not Active Record Association.

My 'hack' works fine.. but I would like the have a clean solution for my problem if there is one? 

Thank you and have a great day!

**Comment by ddnexus** [comment]
You can do it with the `:size` variable. See [Controlling the page links](https://ddnexus.github.io/pagy/how-to#controlling-the-page-links)
