### ISSUE TITLE
Pagy is failing on complex SQL Query that uses group, because it calls .count

### ISSUE THREAD

**Issue by krtschmr** [ddnexus/pagy#179]
I have a double accounting book where a transaction has plus on one side and minus on another side. both transactions share the same reference.
(eg: reference creates plus transaction for USD and minus transaction for EUR)

i want to go through all transactions, but only unique on the reference.
example table for `ledger_entries`

```
id | reference | currency | value
6 | ZZZ | EUR | + 96
5 | ZZZ | USD | -100
4 | QRT | USD | +90
3 | QRT | JPY | -50
2 | AAA | USD | + 120
1 | AAA | EUR | -100

```

for this example, i want only 1 item per page. so on the first page, i expect ZZZ, on the second page, i expect QRT and on the last i expect AAA

this would work, with the following query

`current_user.ledger_entries.select(:reference, "max(id) as id").group(:reference).order("id desc")` 
![image](https://user-images.githubusercontent.com/13366714/63406954-8b2f4900-c415-11e9-99de-fe1e5b20d711.png)

this is returning me the correct set. if i would call `.offset(6.)limit(2)` i would indeed receive the correct entries

however, `.count` isn't working for this query. and it has to do with the way `mysql 5.7` is working.
i run the following (i assume that's what pagy does aswell at least when i read the code) 
`a.ledger_entries.select(:reference, "max(id) as id").group(:reference).order("id desc").count` 
and this error is thrown.
![image](https://user-images.githubusercontent.com/13366714/63407091-df3a2d80-c415-11e9-9bcc-c8d445c16a44.png)

i tried several attempts to fix the sql query, but i failed.
the only way to fix this, seems to be calling `.to_a.count` if a `group` is included

can somebody confirm that pagy has issues with this?

i'm not sure if this is really pagy related or more active-record issue.

**Comment by krtschmr** [comment]
if we the count method in `change pagy_get_vars`

    def pagy_get_vars(collection, vars)
          vars[:count] ||= collection.to_a.count

it would work for my specific query. but i assume it would perform horrible for huge datasets.

**Comment by ddnexus** [comment]
That is a known quirk of complex AR queries: just check some of these [google results](https://www.google.com/search?q=ActiveRecord+wrong+query+count) to get an idea.

Indeed you can overwrite the `pagy_get_vars` in the unlikely case that every queries in your app would benefit from it, but as a more globally-efficient alternative, you can use a [Custom Count for Custom Scopes](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes) just in the actions that need it.

**Comment by krtschmr** [comment]
@ddnexus  thank you. 

        q = current_user.ledger_entries.select(:reference, "MAX(id) AS max").group(:reference).order("max DESC")
        @pagy, @references = pagy( q, items: 10, count: q.to_a.count)

fixed it indeed. 
the google results are not related, but thank you.

**Comment by ddnexus** [comment]
In that results I read one post explicitly mentioning the AR `select` count problem... in some other the AR `group` count problem which happen to be both in your query, however, good that you got it working.
