### ISSUE TITLE
Incorrect documentation on rendering templates?

### ISSUE THREAD

**Issue by scotteknight** [ddnexus/pagy#180]
The documentation for rendering a customizable template for the navigation links shows:
```
<%== render 'pagy/nav', locals: {pagy: @pagy} %>
```
This did not work for me and I had to change it to:
```
<%== render partial: 'pagy/nav', locals: {pagy: @pagy} %>
```
The [Rails documentation ](https://guides.rubyonrails.org/layouts_and_rendering.html#partial-layouts) says that 'partial' must be explicitly added whenever there are options passed to the render call, unless I'm missing something.

**Comment by ddnexus** [comment]
You are absolutely right! I thought I already fixed that in the doc, but I missed that instance... I will search and fix it again. Thank you!
