### ISSUE TITLE
Hi I'm getting the following error "undefined method `some_scope' for"

### ISSUE THREAD

**Issue by bobomimi** [ddnexus/pagy#182]
![Screenshot from 2019-08-26 13-15-34](https://user-images.githubusercontent.com/11933277/63683800-fc02a680-c803-11e9-95ed-0f551453e547.png)

I did everything as described here: https://ddnexus.github.io/pagy/how-to#quick-start

thank you so much :)

**Comment by bobomimi** [comment]
this line of code worked grate "@pagy, @articles = pagy(Article.order('created_at DESC'))"

**Comment by ddnexus** [comment]
Indeed the `some_sope` is just used as an example: you have to define a scope in your model and then call it from the method in order to paginate it.
