### ISSUE TITLE
Reverse pagination

### ISSUE THREAD

**Issue by nubi** [ddnexus/pagy#183]
I'm wondering is it possible to reverse the pagination?

Like now it's [1, 2, 3, 4, 5, 6 ...10]
Can we change them to [10, 9, 8, 7, 6 ... 1]

**Comment by ddnexus** [comment]
@nubi This is a question, not an issue, so please, use the [Gitter Chat Support](https://gitter.im/ruby-pagy/Lobby) for it. Thanks.
