### ISSUE TITLE
Elasticsearch 7 support

### ISSUE THREAD

**Issue by amenon** [ddnexus/pagy#184]
I'm using elasticsearch 7, and it looks like the `total` attribute in the response is [now a hash](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-request-body.html#request-body-search-track-total-hits) instead of an integer count. So we'd probably need to extract the count using something like:
```
  total = response.raw_response['hits']['total']
  total.is_a?(Hash) ? total['value'] : total
```

I'm happy to open up a PR, but wanted to know your thoughts on this, and if we should add an additional mock model for ES7.

**Comment by ddnexus** [comment]
Hi @amenon, that looks good. PR is welcome. Thanks.

**Comment by ddnexus** [comment]
and... if you can add the test for that it's a lot beer :)

**Comment by exocode** [comment]
Is it possible to add this feature also to version 3.x, because Ruby 3.x is quite "experimental" (I had issues to debug rspec) installing nokogiri and so on.. so it is - in my opinion - not ready for production.

**So it would be great to make this feature available to Ruby 2.x  users too...**

**Comment by ddnexus** [comment]
This feature should already be in 3.x since almost 2 years. Do I miss something?

**Comment by exocode** [comment]
> This feature should already be in 3.x since almost 2 years. Do I miss something?

Ok, I didn't recognized that. Thank you!
