### ISSUE TITLE
How do I change variable names on medata ?

### ISSUE THREAD

**Issue by bcott** [ddnexus/pagy#197]
Hi,
I’m using Pagy with metadata and wondering how I could change the variables names within  the response, for instance total instead or count.

**Comment by ddnexus** [comment]
Hi @bcott 
the metadata is returning a hash using pagy internal naming. If you want to change it you should re-map the hash to your liking. You can do that in your own code in many ways, or you can override the `pagy_metadata` method in your controller, or write a new method that internally call the `pagy_metadata` and returns a re-mapped version of it.

**Comment by bcott** [comment]
Hi @ddnexus,
Thanks for the reply,
I wanted to Be sure not to miss it from the config/pagy.rb. because there are a lot of options 

Then I would go for a helper method in the controller
