### ISSUE TITLE
It's an honor to blog tutorial posted.

### ISSUE THREAD

**Issue by kbs4674** [ddnexus/pagy#203]
Thanks for post my blog from pagy tutorial (한국어, Korean Ver.)
by the way, Could you modify blog URL?

my blog is move to another blog website.
request modify https://blog.naver.com/kbs4674/221616865157 to https://kbs4674.tistory.com/72 .
thanks!

**Comment by ddnexus** [comment]
Thanks for the info. I will change the link.
dd

**Comment by ddnexus** [comment]
973f4fe2d59317a298208006513869c5edf865e4
