### ISSUE TITLE
disable with pagy_next_link

### ISSUE THREAD

**Issue by nikolaokonesh** [ddnexus/pagy#206]
_next_link.html.erb
```
<%== pagy_next_link(pagy, icon('fas', 'chevron-down fa-2x', class: 'link', title: 'Показать больше')) unless pagy.last == pagy.page %>
```
how add 
`data: {disable_with: 'Open...'}`
Finding solutions failed :( Help!!!

**Comment by ddnexus** [comment]
please, give more context, because it is not clear what you want to do

**Comment by ddnexus** [comment]
BTW, please use the [Chat Support](https://gitter.im/ruby-pagy/Lobby) for questions. Thanks.
