### ISSUE TITLE
How to remember state within a collection and reset when moving to another collection?

### ISSUE THREAD

**Issue by odinsride** [ddnexus/pagy#209]
Hello, 
I am implementing the pagy gem for an application where I have the following models:

Accounts has_many Transactions.

When I go to the Transactions list of an account I am doing the pagination, but I want to be able to go to say, page 3 of Transactions, edit the Transaction, and redirect back to page 3.

Then, if I go to another account I want it to start on page 1 of the Transactions.  

What is currently happening is that the page number is being saved between accounts so if I'm on Transaction page 3 of Account A, when I go to Account B it also goes to Transaction page 3.

How can I force it to start on Page 1 when I switch to another Account's transactions?

Here is my Transaction controller index:

```ruby
  # Index action to render all transactions
  def index
    session[:trx_index_page] = params[:page] if params[:page]

    @transactions = @account.transactions.search(params[:description]).with_balance.desc
    @pagy, @transactions = pagy(@transactions, page: session[:trx_index_page], items: 15)
    @transactions = @transactions.decorate

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @transactions }
    end
  end
```

**Comment by ddnexus** [comment]
This is a question, not an issue, so please use the [Chat on Gitter](https://gitter.im/ruby-pagy/Lobby).

Quick answer: the `params[:page]` is`nil` for page #1, hence you are not changing the `session[:trx_index_page]` when you change the account, and you are still passing the last `session[:trx_index_page]`. You should review the logic of that.
