### ISSUE TITLE
Error When Using Pagy with AJAX Request

### ISSUE THREAD

**Issue by shawnpk** [ddnexus/pagy#213]
I have Pagy implemented in a few places in my app. The newest place I want to implement it is giving me an error:
![Screen Shot 2020-01-21 at 3 29 58 PM](https://user-images.githubusercontent.com/5712501/72848934-ea161a00-3c62-11ea-83ac-3fb9c95777b6.png)
I'm attempting to use this pagination with a page that is part of an AJAX request. How I can get Pagy to work with an AJAX request?

**Comment by ddnexus** [comment]
This doesn't look like a pagy issue but a generic issue in your app, so please use the [![Chat](http://img.shields.io/badge/gitter-ruby--pagy-purple.svg?colorA=800080&colorB=b300b3)](https://gitter.im/ruby-pagy/Lobby) support chat.

From your post there is no indication about the actual code you use, however, you may be missing the `link_extra: 'data-remote="true"` to get the actual ajax call.
