### ISSUE TITLE
Failed to dump Symbol Object to JSON in strict mode. - When using nav_js

### ISSUE THREAD

**Issue by vitroz** [ddnexus/pagy#214]
Been trying to use pagy*_nav_js pagination, but haven't been able to figure out this error.

I have oj gem.

pagy_bootstrap_nav itself works fine, but pagy_bootstrap_nav_js will throw that error for me.

Any solutions? Cound't find any simillar issue

**Comment by ddnexus** [comment]
@vitroz did you find the problem? What was it?

**Comment by vitroz** [comment]
@ddnexus did not find the solution, unfortunately
