### ISSUE TITLE
Lose results when paginating

### ISSUE THREAD

**Issue by damienlethiec** [ddnexus/pagy#215]
Hi there,

I have a problem with pagy.

I use the following query in my controller and it works really well:
`Client.joins(:orders).merge(Order.unpaid.order('created_at_shopify'))`

Unfortunately, when I filter with `@pagy, @clients = pagy(@clients, items: 80)`, I lose some results (@clients loses around 1/3 of its results).

Could you help me with this?

Thanks so much

**Comment by ddnexus** [comment]
The [Custom count for custom sopes](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes) may help in your case.

This doesn't look like a pagy issue but a know problem of AR count, so, in case the suggestion doesn't solve your problem, please use the [![Chat](http://img.shields.io/badge/gitter-ruby--pagy-purple.svg?colorA=800080&colorB=b300b3)](https://gitter.im/ruby-pagy/Lobby) support chat.
