### ISSUE TITLE
ElasticSearch Rails below version 6 not supported 

### ISSUE THREAD

**Issue by doutatsu** [ddnexus/pagy#217]
In the code, you make use of `raw_response` for getting the total with `response.raw_response['hits']['total']`. That method didn't exist (there was only `response`) until version 6, so version 5 and 2 fail when using the extra.

Looking into the `Elasticsearch::Model::Response::Base` I can see there is exists method called `total` which does exactly what is being done in pagy extra. I suspect switching to using this method, will make sure that pagy extra will work for all versions (as that method exists in all versions). 

Don't quite have time to do a proper PR, so for now, just wanted to highlight this issue

**Comment by ddnexus** [comment]
It looks like a good improvement! Thank you! 
I hope you will have time to do a PR and test it soon.

**Comment by codingluka** [comment]
Hi, @doutatsu 
May I try to fix this issue. Then attached a PR?

**Comment by doutatsu** [comment]
@codingluka Please do, I never found time to do that

**Comment by ddnexus** [comment]
Me neither, and it should be quite simple. Just remember to add tests. Thank you @codingluka

**Comment by codingluka** [comment]
@doutatsu Thank you!!
@ddnexus Thanks for answering. I'm glad to do it.

**Comment by codingluka** [comment]
raw_response replaced response is a performance improvement of elasticsearch-rails.
see https://github.com/elastic/elasticsearch-rails/pull/850

**Comment by ddnexus** [comment]
closed by #234
