### ISSUE TITLE
Unable to set-up current page

### ISSUE THREAD

**Issue by swilgosz** [ddnexus/pagy#218]
### Overview

There is a big coupling to `params` which makes `pagy` hard to configure. Options arguments allow to pass `items` to override default fetching `per_page` attribute from params, but there is no such option for the `page_number` parameter.

This is an issue, because gem assumes that pagination parameters are always flat. Which is not a case.

The http://jsonapi.org standard assumes you should provide pagination arguments in the form: 
`page[number]` and `page[size]`

which is transformed to `{ page: { number: 1, size: 10 } }` in the request params.

There is no way to configure the pagy to support such page objects other than overriding the method.

https://github.com/ddnexus/pagy/blob/ee22c989644bb1e6794b090fd134d46333c6b7b9/lib/pagy/backend.rb#L19-L30

### Suggested solution

Allow to pass page value from the outside following the standard dependency injection pattern and don't rely on the `params` object anymore.

**Comment by ddnexus** [comment]
> there is no such option for the page_number parameter.

It looks like you missed the `page` variable: just set it to the number you want as explicitly explained in the [Passing the page number](https://ddnexus.github.io/pagy/how-to#passing-the-page-number) section of the How To page.

 > This is an issue, because gem assumes that pagination parameters are always flat. Which is not a case.

It looks you are confusing the pagy variables with the request params.

> The http://jsonapi.org standard assumes you should provide pagination arguments in the form:
page[number] and page[size]

The `jsonapi` can assume whatever, and still that is not a pagy core concern. Pagy can easily be used with ANY assumption as it is right now. However, if you want to add automatic support for that specific `jsonapi`, pagy makes it simple to write just a few lines in a single file and create the `jsonapi` extension. That could be optionally required to whoever want to use it without imposing it to everybody, even if their app has nothing to do with any `jsonapi`. An extra to just pick a couple of params (that you can pass easily without any extra) would be a very marginal advantage, but PRs are welcome for discussion.

> There is no way to configure the pagy to support such page objects other than overriding the method.

You have all the means to handle whatever are the request params and use them to create totally custom pagy objects by just setting any of the [instance variables](ddnexus.github.io/pagy/api/pagy#instance-variables) as you wish, right in the constructor argument for example. 

What about just:

```
@pagy, @records = pagy(Products.all, page: params[:page][:number], items: params[:page][:size]
```

> Suggestion: Allow to pass page value from the outside ...

Thanks for the suggestion but it's already allowed

> ... and don't rely on the params object anymore.

...so breaking ALL the apps that currently use pagy, AND obliterating the params management that allows features like [Stateful Tabs](https://www.imaginarycloud.com/blog/how-to-paginate-ruby-on-rails-apps-with-pagy) for example. Thanks for the suggestion but it doesn't look like the best idea to me.

Now... my turn for a suggestion ;)

Maybe before making quite a few wrong assumptions, a simple question like _"How can I pass the page number?"_ (possibly in the [dedicated chat support](https://gitter.im/ruby-pagy/Lobby)), would have been a wiser choice ;)

**Comment by swilgosz** [comment]
You're right, I just missed the `page:` parameter, which was the core of my wrong assumptions. Thanks for explaining and sorry for being too hurry to create an issue. All the best and thanks for the great plugin.

**Comment by ddnexus** [comment]
You are welcome, and thanks for the thanks :)
