### ISSUE TITLE
Feature: Tailwind css Frontend extra

### ISSUE THREAD

**Issue by gathuku** [ddnexus/pagy#219]
Requesting for a tailwind css frontend extra

**Comment by ddnexus** [comment]
It looks like there is no specific pagination component for tailwind, so it's just a matter of designing your own custom helper/template.

If you want to create an extra for that, a PR would be welcome. Thanks.

**Comment by gathuku** [comment]
@ddnexus  Working on it

**Comment by ddnexus** [comment]
This has been replaced by #220. Closing.
