### ISSUE TITLE
pagy_array collection is not updating after pagination call with data-remote=true

### ISSUE THREAD

**Issue by tiagocassio** [ddnexus/pagy#221]
Hi, first of all, thanks for this great job.

I'm using pagy to paginate an array of hashes. 

My problem is because the @records is not being updated after pagination request with "data-remote=true", here is the example:

```
@pagy, @records = pagy_array(@collection['data'],
                                 page: @collection['data'].any? ? @collection['pagination']['current'] : 1,
                                 link_extra: 'data-remote="true"',
                                 count: @collection['pagination']['count'])
```

The other things like respond_to and views are same like in this doc:

[https://ddnexus.github.io/pagy/extras/array](url)

NOTE:
The first server-sided request is OK but, when i click on page 2 to retrieve the next slice, the @records is being empty but the @pagy update normally.

**Comment by BKSpurgeon** [comment]
hi there @tiagocassio 

* are you using rails? if so would you be able to spin up a minimal app with a failing test?

**Comment by ddnexus** [comment]
@tiagocassio: I hope you are aware of the downsides of using `pagy_array`, however, assuming that you have no other way to do it... your way of paginating looks quite indirect to me.

For example, why you pass an explicit `count` taken from your metadata, which needs to get updated manually (with possibly many ways to get it wrong)? If you remove it, the `pagy_array` will simply use `@collection['data'].size` which is supposed to be the array count you are paginating, and granted to be consistent.

Why you pass a `page` - again - taking it from your manually-kept metadata, while pagy would just take it from the `page` param?

Isn't this enough?

```ruby
@pagy, @records = pagy_array(@collection['data'], link_extra: 'data-remote="true"')
```

**Comment by ddnexus** [comment]
And BTW, did you read [Using AJAX](ddnexus.github.io/pagy/api/javascript#using-ajax) ?

**Comment by ddnexus** [comment]
I assume this has been resolved, besides it doesn't look like a pagy issue. Closing.
