### ISSUE TITLE
lib/pagy/backend pagy_get_vars method make mistake when collection order by field doesn't in table

### ISSUE THREAD

**Issue by kingyueng** [ddnexus/pagy#237]
![image](https://user-images.githubusercontent.com/42204596/80582268-fcada580-8a40-11ea-9919-0002a5ea96df.png)
I want to order customers with customize field, but it mistake when execution pagy_get_vars method in lib/pagy/backend
I override it like below, add unscope(:order) to collection
Is this right, or will it cause other problems？

`def pagy_get_vars(collection, vars)`
`    vars[:count] ||= (c = collection.uncsope(:order).count(:all)).is_a?(Hash) ? c.size : c`
`    vars[:page]  ||= params[ vars[:page_param] || VARS[:page_param] ]`
 `   vars`
`end`

**Comment by ddnexus** [comment]
Count is a tricky thing with complex queries in AR.

You have a couple of options to avoid overriding:

1. You could try to see if the [arel extra](https://ddnexus.github.io/pagy/extras/arel) works better in your case
2. You could also simply pass the custom calculate count explicitly (see [Custom Count for Custom Scopes](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes))

**Comment by kingyueng** [comment]
thanks
