### ISSUE TITLE
how to use custom template for pagy_items_selector_js

### ISSUE THREAD

**Issue by nyrf** [ddnexus/pagy#240]
I want to use select to change per page items, i found https://github.com/ddnexus/pagy/blob/master/lib/pagy/extras/items.rb#L51 there is not way to use custom template, any way?

**Comment by ddnexus** [comment]
It's a helper and there is no template for that, however creating one out of the output should be quite simple.

**Comment by nyrf** [comment]
Thanks, i've create a new helper and js method to do that.
