### ISSUE TITLE
Brakeman Warning: Unescaped output may cause cross-site scripting vulnerabilities

### ISSUE THREAD

**Issue by joshRpowell** [ddnexus/pagy#243]
Hi, love Pagy!  We just implemented strict Brakeman requirements and get the following warning for both `pagy_nav` & `pagy_bootstrap_nav`

```
== Warnings ==

Confidence: Info
Category: Cross-Site Scripting
Check: UnescapedOutputs
Description: Unescaped output in view
Unescaped output may cause cross-site scripting vulnerabilities.

This application is configured to escape HTML by default. Explicitly unescaped output via template features or `raw`/`html_safe` should be used cautiously.
Code: pagy_nav(@pagy)
File: path_to_view_file/edit.html.erb
Line: 54
```

suggestions on how to handle?

**Comment by ddnexus** [comment]
> This application is configured to escape HTML by default. Explicitly unescaped output via template features or `raw`/`html_safe` should be used cautiously.

Yeah, we all know and agree that "it should be used cautiously". I cannot think of a way to inject cross-site scripting in pagy, which uses integers coming from calculation on a count on the backend. It even raise an exception if any instance variable is not an integer.

Besides, can you think of any way to output valid HTML by escaping it? :)

**Comment by ddnexus** [comment]
Thoughts?

**Comment by joshRpowell** [comment]
Agree. 

We just added it to our brakeman.ignore file.
