### ISSUE TITLE
What would be the recommended solution for overriding the `series`?

### ISSUE THREAD

**Issue by dizzyfingerz** [ddnexus/pagy#245]
Several studies have shown that "classic" pagination approaches are not the best for both user-experience and website bot crawlers. The following articles lay out the pros and cons of these pagination strategies, and also lay out some of the recommended alternatives (such as midpoint, logarithmic, and ghostblock).

Example: https://www.portent.com/blog/seo/pagination-tunnels-experiment-click-depth.htm
Example: https://audisto.com/insights/guides/1/

Given that so much of the pagy architecture is customizable, what would be the recommended solution to achieving something similar here? Overrides in the view? 

I'm still a pagy beginner, so apologies if I've missed something in the documentation.

**Comment by ddnexus** [comment]
You can override the [series](https://github.com/ddnexus/pagy/blob/c4336490ff4d5c256e00ca67ef356bd49a36bc05/lib/pagy.rb#L35-L46) method. Here is the [documentation](https://ddnexus.github.io/pagy/api/pagy#series).

**Comment by ddnexus** [comment]
A more flexible approach that allow to jump to whatever page you want is using the [pagy_*combo_nav_js](https://ddnexus.github.io/pagy/api/javascript.html#javascript-combo-navs).

**Comment by dizzyfingerz** [comment]
Overriding works... ish. It's tough to get custom behavior only in certain cases, so I ended up overriding the entire method definition with an additional `type` param. So that cases that need specific paginations can include a `type='midpoints'` (example) in the call.

```ruby
# Override default Pagy series method here so that we can create our own types of series
Pagy.class_eval do
  def series(size=@vars[:size], type=@vars[:series_type])
    (series = []) and size.empty? and return series
    4.times{|i| (size[i]>=0 rescue nil) or raise(VariableError.new(self), "expected 4 items >= 0 in :size; got #{size.inspect}")}
    [*0..size[0], *@page-size[1]..@page+size[2], *@last-size[3]+1..@last+1].sort!.each_cons(2) do |a, b|
      if    a<0 || a==b || a>@last                                        # skip out of range and duplicates
      elsif a+1 == b; series.push(a)                                      # no gap     -> no additions
      elsif a+2 == b; series.push(a, a+1)                                 # 1 page gap -> fill with missing page
      else            series.push(a, :gap)                                # n page gap -> add gap
      end                                                                 # skip the end boundary (last+1)
    end                                                                   # shift the start boundary (0) and
    series.shift; series[series.index(@page)] = @page.to_s; series        # convert the current page to String
    # ***DEAR GIT READERS, OVERRIDE IS HERE***
    if type == 'with_midpoints'
      Pagy::Overrides.series_with_midpoints(series)
    else
      series
    end
  end
end
```

This has quite the code smell though. Still feels like I'm missing something.

**Comment by ddnexus** [comment]
> get custom behavior only in certain cases

maybe I am missing something, but why you override the whole series method if you use it in certain cases, and your `series_with_midpoints` uses the original series? 

Isn't it simpler and cleaner just creating your own method that calls the original series and alias chains it?

**Comment by dizzyfingerz** [comment]
Ahh ok I think I'm tracking. New approach, taking advantage of the customizable `vars`.

```ruby
class Pagy
  alias_method :default_series, :series
  def custom_series
    case vars[:series_type]
    when :midpoint
      Pagy::Overrides.series_with_midpoints(default_series)
    else
      default_series
    end
  end
  alias_method :series, :custom_series
end
```

**Comment by ddnexus** [comment]
Yes, it looks better. 

Here is a suggestion that should simplify it (depending on the complexity of your logic) and make it more resource-efficient:

```ruby
class Pagy
  alias_method :series_without_midpoints, :series

  def series_with_midpoints
    series_array = series_without_midpoints
    series_array.map! { ... } if vars[:series_type] == :midpoint
    series_array
  end

  alias_method :series, :series_with_midpoints
end
```

**Comment by bb** [comment]
I had a similar requirement like the midpoints and preliminary solved it like this:
You can define a gap_divisions option which provides an integer greater 0. The gaps will be split into by this amount of divider page-numbers; however I made sure the gaps won't become too small.

It might be better to configure not (only) the number of divisors but the number of divisions (i.e. + 1), the maximum gap size, or something more dynamic. I'll let those considerations sink in in the next few days before I need to take action.

Please be aware this is NOT tested yet and NOT in production use anywhere. I just wrote it down to get it out of my head and trigger any questions which might arise.


    class Pagy
      alias_method :series_without_gap_divisions, :series

      def series_with_gap_divisions
        series_array = series_without_gap_divisions
        divisions = vars[:gap_divisions]
        if divisions && divisions > 0
          new_series = []
          series_array.each_cons(3) do |pre,gap,nex|
            if gap == :gap
              divisions = [(nex-pre)/4, divisions].min # prevent tiny gaps
              divisor = divisions + 1
              gap = (nex-pre)/divisor
              divisions.times do |n|
                new_series.push(pre+gap*n)
                new_series.push(:gap)
              end
              new_series.push(pre+gap*divisions)
            else
              new_series.push(pre)
            end
          end
          new_series.push(series_array.second_to_last) # last item of pagy vars size must not be 1, or it will fail here!
          new_series.push(series_array.last)
          return new_series
        end
        series_array
      end

      alias_method :series, :series_with_gap_divisions
    end

**Comment by ddnexus** [comment]
This is a good example that shows how you can further expand/reconsider the original gaps created by the original series. Thank you.

**Comment by bb** [comment]
Here's an improved version which supports a gap at the second-to-last position. I considered making it more configurable (see below) but I think I'll just use that for the current requirement.

```ruby
class Pagy
  alias_method :series_without_fill_gaps, :series

  # Fills gaps with some interjacent page numbers.
  # Activate by setting `Pagy::VARS[:fill_gaps]` or passing option `:fill_gaps` to the `pagy`-call.
  def series_with_fill_gaps(*args)
    series_array = series_without_fill_gaps(*args)
    return series_array unless vars[:fill_gaps]

    series_array.flat_map.with_index do |item, index|
      next item unless item == :gap && (next_ = series_array[index + 1].to_i) - (previous = series_array[index - 1].to_i||1) > 3

      divisions = [(next_ - previous)/4, 10].min # prevent tiny gaps or too many insertions
      gap = ( next_ - previous ) / ( divisions + 1 )
      
      [:gap, *(0...divisions).flat_map { [previous += gap, :gap]}]
    end
  end

  alias_method :series, :series_with_fill_gaps
end
```

The line which is setting the number of divisions is an obvious place for introducing configurability which might be desirable for a more generic solution, e.g. max insertions, custom division size based on prev/next (by passing a proc like `->(prev,next_) { }`) etc. - all making it more complex and possibly slower. So I'll just leave that here as an inspiration.

```ruby
class Pagy
  alias_method :series_without_fill_gaps, :series

  # Fills gaps with some interjacent page numbers.
  # Activate by setting `Pagy::VARS[:fill_gaps]` or passing option `:fill_gaps` to the `pagy`-call.
  # Accepted values are `true` or a settings object.
  def series_with_fill_gaps(*args)
    series_array = series_without_fill_gaps(*args)
    return series_array unless (gaps_settings = vars[:fill_gaps])

    gaps_settings = {} if gaps_settings == true
    gaps_settings = {max_insertions: 10}.merge(gaps_settings)

    series_array.flat_map.with_index do |item, index|
      next item unless item == :gap && (next_ = series_array[index + 1].to_i) - (previous = series_array[index - 1].to_i||1) > 3

      divisions = [(next_ - previous)/4, gaps_settings[:max_insertions]].min # prevent tiny gaps
      gap = ( next_ - previous ) / ( divisions + 1 )
      
      [:gap, *(0...divisions).flat_map { [previous += gap, :gap]}]
    end
  end

  alias_method :series, :series_with_fill_gaps
end
```
