### ISSUE TITLE
Reverse pagination, but only on the show page?

### ISSUE THREAD

**Issue by monroemann** [ddnexus/pagy#251]
We have a message inbox, and we want to paginate it.  

We have successfully done so, but now, every time you load the inbox, it
a) scrolls to the bottom
b) leaving the most recent message up top

Is there a way to reverse the per-page display, so that it displays the most recent message at the bottom of each page?

Thank you!
-Monroe from BreakDiving.io (501(c)(3) charity)

**Comment by BKSpurgeon** [comment]
Yes, see here:

```
@pagy, messages = pagy( Message.all)

@messages = messages.order(:created_at, :desc)
```

**Comment by BKSpurgeon** [comment]
Scrolling to the bottom should not be handled by pagy. Are you able to demo the problem with a minimal app?
