### ISSUE TITLE
Pass the `items` param in API

### ISSUE THREAD

**Issue by Tao-Galasse** [ddnexus/pagy#252]
Hi!

I'm using Pagy in an API, and I would like to allow users to specify the page they want AND the number of items per page.

In this method, https://github.com/ddnexus/pagy/blob/master/lib/pagy/backend.rb#L20 it seems like it's not currently possible to do it without specifying it directly in the controller, but could you explain me why?

For the moment I just changed my controller method from `@pagy, records = pagy(my_items)` to `@pagy, records = pagy(my_items, items: params[:items] || Pagy::VARS[:items])`, but I think it would be useful to not have to specify it like this.

Would you be open to a PR, or could you explain me why not?

Thanks! 🙏

**Comment by ddnexus** [comment]
Maybe you are looking for the [items extra](http://ddnexus.github.io/pagy/extras/items)

**Comment by Tao-Galasse** [comment]
Oh, thank you! I read this part of the doc, but I forgot to uncomment the line `Pagy::VARS[:items_param] = :items` in my initializer so it wasn't working… 🤦‍♂️
Thanks for the quick answer! 😄
