### ISSUE TITLE
The number of rows provided for a FETCH caluse must be greater then zero.

### ISSUE THREAD

**Issue by daveomcd** [ddnexus/pagy#26]
Rails 5.1.6

I use the following for connecting to my database,
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'

I use SQL Server for my database.  I recently ran into this error when trying out the pagy gem in place of will_paginate.  It happens when I trying to visit a page where I don't have any notes currently tied to a record.  Wasn't sure if this was an issue with the gem or something I'm doing incorrectly, but figured I'd post it here.

`@pagy_notes, @notes = pagy(@player.notes.ordered, items: 10)`

Then when I try to access @notes.

**Error**
`TinyTds::Error: The number of rows provided for a FETCH clause must be greater then zero.: EXEC sp_executesql N'SELECT  [notes].* FROM [notes] WHERE [notes].[hidden] = @0 AND [notes].[player_id] = @1 AND ([notes].[type] != @2)  ORDER BY updated_at DESC OFFSET @3 ROWS FETCH NEXT @4 ROWS ONLY', N'@0 bit, @1 int, @2 nvarchar(75), @3 int, @4 int', @0 = 0, @1 = 10075, @2 = N'User', @3 = 0, @4 = 0`

**Comment by ddnexus** [comment]
>  It happens when I trying to visit a page where I don't have any notes currently tied to a record.

I missed that sentence. Did you try to run `@player.notes.ordered` in the console to see what it returns? It should be a scope/collection.

**Comment by daveomcd** [comment]
ddnexus, yep it returns a `#<ActiveRecord::AssociationRelation []>`.  Even though I specify "10" items, since there are no notes/items for that parent record it seems to build out the query with '0' for the @4 argument.  As seen `, @4 = 0`.

**Comment by ddnexus** [comment]
Please, try `@player.notes.ordered.offset(0).limit(10)`

**Comment by daveomcd** [comment]
Sorry ddnexus, appears that I get the `#<ActiveRecord::AssociationRelation []>` for that as well.  I made an incorrect assumption that I received the error when executing `@notes`, but it happens when doing `@notes.each`.  So I'm guessing that's outside of the scope of your gem and more the TinyTDS/SqlServer adapter I'm using perhaps.

**Comment by ddnexus** [comment]
Correct. If you don't have more questions, please close the issue. Thanks.
