### ISSUE TITLE
Limit is set as 1 but in configuration I have 25

### ISSUE THREAD

**Issue by sveredyuk** [ddnexus/pagy#260]
I found a really strange behavior of the pagy when I paginate something from lamda, like:

```ruby
q = ->() { Item.all } # i have more than 100k records in the DB
pagy, paginated_collection = pagy q.call, items: 30

paginated_collection.size # => 1
```
In the logs i see:

```sql
--- full query body and I am 200% sure that there are no LIMIT of OFFSET functions
LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 0]]
```

```ruby
Pagy::VARS

{
          :page => 1,
         :items => 20,
        :outset => 0,
          :size => [
        [0] 1,
        [1] 4,
        [2] 4,
        [3] 1
    ],
    :page_param => :page,
        :params => {},
        :anchor => "",
    :link_extra => "",
      :i18n_key => "pagy.item_name",
         :cycle => false,
         :steps => false
}
```

I am very confused and ask for some help. Thank you.

**Comment by ddnexus** [comment]
Does `Items,all` return a AR scope or an array?

**Comment by sveredyuk** [comment]
@ddnexus it returns `ActiveRecord::Relation`

**Comment by ddnexus** [comment]
I didn't notice that you didn't use parenthesis. 
That is probably a problem because it is ambiguous in the context of multiple variable assignment.

Try: `pagy, paginated_collection = pagy(q.call, items: 30)`

**Comment by sveredyuk** [comment]
Unfortunately does not change the result.
```ruby
collection_query = -> { Item.all } 
collection_query.call.size #=> 103254
pagy, result = pagy(collection_query.call, items: 30)
pagy # => #<Pagy:0x00007fdb6c4f2b18 @vars={:page=>1, :items=>20, :outset=>0, :size=>[1, 4, 4, 1], :page_param=>:page, :params=>{}, :anchor=>"", :link_extra=>"", :i18n_key=>"pagy.item_name", :cycle=>false, :steps=>false, :count=>1}, @count=1, @items=1, @outset=0, @page=1, @last=1, @pages=1, @offset=0, @from=1, @to=1, @prev=nil, @next=nil>

result.size #=> 1
```

**Comment by ddnexus** [comment]
What if you do `pagy, result = pagy(Item.all, items: 30)` ?
What is `result.class` and `result` itself?

**Comment by sveredyuk** [comment]
```ruby
result.class #=> Item::ActiveRecord_Relation < ActiveRecord::Relation
result.size #=> 30
```

**Comment by ddnexus** [comment]
1. I asked "What if you do `pagy, result = pagy(Item.all, items: 30)` ?" and you didn't answer.
2, I asked what is the content of `result` itself and you didn't answer.
3. Now you report that the `result.size` is not 1 anymore but 30

> I think also need to mention that the Item itself is a PG view that I wrap into scenic model https://github.com/scenic-views/scenic

And I think you should have mentioned that from the beginning. It is messing up your model in some way that you are not aware of, and neither am I. 

What I am pretty sure about is that pagy has nothing to do with it.
If you want to debug it put a break-point in the `pagy` method itself and follow it from there.

**Comment by sveredyuk** [comment]
@ddnexus Thanks.
