### ISSUE TITLE
undefined method `pagy_items_selector_js'

### ISSUE THREAD

**Issue by vkalach** [ddnexus/pagy#261]
in initializers
`require 'pagy/extras/items'`

in application helper
`include Pagy::Frontend`

but still receiving this error

what have I missed?

**Comment by ddnexus** [comment]
I guess you restarted the app.
It looks like a basic ruby (rails?) inclusion problem... it behave like your view cannot access the method defined in the inclued module.
Are you using rails? Did you try that in a basic new created app?
Try to move the `include Pagy::Frontend` directly in the specific controller-helper instead application helper... just in case.

**Comment by ddnexus** [comment]
After one week of inactivity I asume this is not an issues anymore.
