### ISSUE TITLE
Page countless does not return the relation

### ISSUE THREAD

**Issue by bpinto** [ddnexus/pagy#263]
Rails 6.0+ has [added](https://github.com/rails/rails/commit/4f2ac80d4cdb01c4d3c1765637bed76cc91c1e35) `cache_version` and `cache_key` to relations. This is useful if you want to cache the results without having to perform a DB query first.

```
Rails.cache.fetch collection.cache_key, version: collection.cache_version do
  # do something
end
```

Its implementation uses a cache key like this:

```
query_signature = ActiveSupport::Digest.hexdigest(to_sql)
key = "#{klass.model_name.cache_key}/query-#{query_signature}"
```

It would be nice if `page_countless` somehow returned the relation so that we could do a `.to_sql` on it (or use `.cache_key` if on Rails 6.0+).

As a workaround, I'm doing something like this:

````
@relation = @collection.offset(params[:page]).limit(per_page + 1)
@pagy, @collection = pagy_countless(@collection, items: per_page)
````

The problem here is that `pagy_countless` will return the collection instead of the relation because it needs to do the `pop`, I'm not sure what we could do differently.

**Comment by ddnexus** [comment]
> I'm not sure what we could do differently.

... and neither do I :) 

I am not even sure it is possible to change it in such a way that could return an association still returning one less record than what it queried for, but that doesn't mean you cannot find a way ;).

**Comment by ddnexus** [comment]
I've just realized that if your scope is caching the query that pagy executes then you should not try to make pagy return the AR relation and do it outside of it. Instead you should use the cache block in the `pagy` method itself (or its sub-methods). 

Something similar to what is proposed in the [Caching the count](https://ddnexus.github.io/pagy/how-to#caching-the-count) example, obviously done with the result query instead the count query (which is skipped with `countless`). That is an example that uses the regular/legacy rails cache, so with Rails 6 you you should be able to do it with even less code.

**Comment by bpinto** [comment]
Thanks for the example! I see how it could work in a normal controller flow, but we have a slightly different approach, I'll try to adjust to it.

Thanks for working with me on this :+1:
