### ISSUE TITLE
Link rel & prev

### ISSUE THREAD

**Issue by Tioneb12** [ddnexus/pagy#265]
The best pratice it's to put rel="next" and rel="next" in the head and not in the body.

How can I do that ?

**Comment by ddnexus** [comment]
> The best pratice it's to put rel="next" and rel="next" in the head and not in the body.

Actually the "best" practice is not adding link tags in the HTML head, but if you really want to follow the complete official [RFC-8228](https://tools.ietf.org/html/rfc8288) you can use the [headers extra](https://ddnexus.github.io/pagy/extras/headers) which implements headers pagination.

If you really want to add tags in the heads, you can create a couple of simple helpers and use them in your views/layouts. 
Something like:

```ruby
def pagy_prev_link_tag(pagy)
  %(<link href="#{pagy_url_for(pagy.prev, pagy)}" rel="prev" aria-label="previous" />) if pagy.prev
end

def pagy_next_link_tag(pagy)
  %(<link href="#{pagy_url_for(pagy.next, pagy)}" rel="next" aria-label="next" />) if pagy.next
end
```

**Comment by ddnexus** [comment]
Version 3.9.0 added the link tag helpers above.
See [pagy_prev_link_tag](https://ddnexus.github.io/pagy/extras/support#pagy_prev_link_tagpagy) and [pagy_next_link_tag](https://ddnexus.github.io/pagy/extras/support#pagy_next_link_tagpagy)
