### ISSUE TITLE
#<TypeError: no implicit conversion of nil into String>

### ISSUE THREAD

**Issue by Tioneb12** [ddnexus/pagy#266]
I have a scope :

```
pg_search_scope :search_by_name_or_zip_code,
                  ignoring: :accents,
                  against: :name,
                  associated_against: {
                    poi: %i[city zip_code]
                  },
                  using: {
                    tsearch: { prefix: true, any_word: true }
                  }
```

and in my controller : 

```
      if params[:query].present?
          @pagy, @towns = pagy(Town.search_by_name_or_zip_code(params[:query]), items: 50)
        else
        @pagy, @towns = pagy(@towns.order('pois.city'), items: 50)
      end
```

Town.search_by_name_or_zip_code(str) work fine

and in my view, I get :  

```
Completed 500 Internal Server Error in 1654ms (ActiveRecord: 332.8ms | Allocations: 674854)
NoMethodError - undefined method `prev' for nil:NilClass:
  pagy (3.8.3) lib/pagy/frontend.rb:63:in `pagy_link_proc'
  pagy (3.8.3) lib/pagy/extras/bulma.rb:12:in `pagy_bulma_nav'
  app/views/admin/towns/index.html.erb:63
```

**Comment by BKSpurgeon** [comment]
Hi there

are you sure that the `@towns` instance variable is set?

```ruby
if params[:query].present?
          # skip
else
        @pagy, @towns = pagy(@towns.order('pois.city'), items: 50)  ## Where the @towns instance variable set??
end
```

**Comment by Tioneb12** [comment]
I get the error with this line :
`@pagy, @towns = pagy(Town.search_by_name_or_zip_code(params[:query]), items: 50)`

the @towns instance variable is defined before : 
`@towns = Town.joins(:poi).where({ pois: { statut: statut, poitable_type: 'Town' } })`

**Comment by ddnexus** [comment]
It looks like `@pagy` is `nil` when you use `pagy_bulma_nav`. 
Check it from right after you define it in the controller down to the view.

**Comment by ddnexus** [comment]
sorry I didn't notice... `pg_search_scope` what kind of a scope is that one?

**Comment by Tioneb12** [comment]
pg_search_scope is a PostgreSQL's scope full text search. https://github.com/Casecommons/pg_search

The scope work fine in my rails console but not in my controller :

**Comment by ddnexus** [comment]
The scope must return an AR relation. It must respond to `count`, `offset` and `limit`.
The scope is used as `collection` [here](https://github.com/ddnexus/pagy/blob/b4ccf7484d3b170b7fe2b312deff6227433c306b/lib/pagy/backend.rb#L20-L30)
If all that checks out, then maybe that `order` at line 27 is messing things up. Try to remove it.

**Comment by ddnexus** [comment]
Besides, looking at your console... the error comes from your code, before pagy gets defined

**Comment by Tioneb12** [comment]
The scope return an AR relation and respond to count, offset and limit.

Your are rigth :
if I put before the if  `collection = Town.search_by_name_or_zip_code(params[:query])`  I get the same error !

Thanks for your help ;)
