### ISSUE TITLE
I18n not working properly

### ISSUE THREAD

**Issue by ronval** [ddnexus/pagy#267]
Hey guys i'm not sure if its the way i'm using the gem or its not working as it should but I'm trying to add I18n for english and spanish. Under the initializer file I have un commented this 

`Pagy::I18n.load({locale: 'es'},{locale: 'en'})`

I thought that would be it and it did translate it to Spanish but when I change the language to english it stays in Spanish. The rest of the website translates just fine. 

If I add english as the first argument like so 
`Pagy::I18n.load({locale: 'en'},{locale: 'es'})`
 
It changes to english but it doesn't change to Spanish when I change the websites language to Spanish. Not sure if i'm missing something or something is a bit off?

Thanks for any help

**Comment by ddnexus** [comment]
If you did read the [I18n doc](https://ddnexus.github.io/pagy/api/frontend.html#i18n)... did you miss [Setting  the request locale](https://ddnexus.github.io/pagy/api/frontend.html#setting-the-request-locale-in-multi-language-apps)?

**Comment by ronval** [comment]
ya that was the issue sorry for wasting ur time I missed that in the docs :$
Thanks for your time
