### ISSUE TITLE
Gem version badge not updating

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#27]
Not sure whether is a cache problem or anything we can control, but it's an issue. The current version pushed to rubygem is 0.8.0, and I see the badge for 0.7.2 in the page. Why?

**Comment by ddnexus** [comment]
It works now. It was probably some cache to update.

**Comment by gamafranco** [comment]
Yeah. I suspect github is having issues with the badges markup. Yesterday CocoaPods badge was broken pretty much everywhere.
