### ISSUE TITLE
pagy.rb load errors when deploying

### ISSUE THREAD

**Issue by rvrm** [ddnexus/pagy#270]
_Using Pagy 3.10.0:_
Local setup working fine. Deploying to server via Capistrano throws errors for these lines from _initializers/pagy.rb_:

```require 'pagy/extras/bootstrap'```
> LoadError: cannot load such file -- pagy/extras/bootstrap

```Pagy::VARS[:items] = 50```
> NameError: uninitialized constant Pagy

Is anything needed besides 
``` include Pagy::Backend``` in _application_controller.rb_ and ```include Pagy::Frontend``` in _application_helper.rb_ to have the initializer working in production? Thank you!

**Comment by rvrm** [comment]
Seem like Pagy is not initializing correctly:
> uninitialized constant ApplicationController::Pagy (NameError)
From the server log.

**Comment by rvrm** [comment]
Dang it! Solution: Loaded the gem from within the gemfile's development block. closing…

**Comment by ddnexus** [comment]
Glad that you fund out. :)
