### ISSUE TITLE
[BUG???] The records count isn't correct after pagy

### ISSUE THREAD

**Issue by francesco-loreti** [ddnexus/pagy#271]
Hi,
I have a strange problem. My recordset has 152 records before use Pagy. After pagy divide my records into 8 pages with 20 records for each and with limit and offset I arrive to last (8) page. Into this page I have the problem. Ther records are 10 and not 12. The select into db has limit 10 that is wrong. Offset is correct to 140 but I dont't understand why limit is set to 10 records. Anybody know what's probably problem? I can force the limit value into select?

Thanks!!
Francesco

**Comment by francesco-loreti** [comment]
If I set `outset: 140` the limit param is corretly set to 20 and view all latest rows

**Comment by francesco-loreti** [comment]
I have found the solution with count param.

**Comment by r3cha** [comment]
@francesco-loreti Hello, It would be helpful if describe shortly what the problem was? seems I have the same :(

**Comment by francesco-loreti** [comment]
The problem occurs when I entered a "group by".
I don't understand if it's a bug or not but fortunately I found the solution with the "count" parameter: 

`pagy (users, page: @page, count: users.length)`

Now it works and takes the number of records correctly.

**Comment by ddnexus** [comment]
It's not actually a Pagy bug, it's a known AR limitation/bug for complex scopes.
There is a note in the [documentation](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes) to bypass the problem.
@francesco-loreti you did it right.

**Comment by r3cha** [comment]
@ddnexus @francesco-loreti Thank you guys!
