### ISSUE TITLE
Possible to have Pagy but not paginate

### ISSUE THREAD

**Issue by c0mrade** [ddnexus/pagy#273]
Is there a flag/override of some sort that would allow me to keep something like this in my controller:

pagy, records = pagy(active_database_records)

That would allow me to get entire `active_database_records` dataset without paginating it. 
Right now this is what I'm doing:

```
if params[:pagination].presence == 'false'
      records = active_database_records
else
      pagy, records = pagy(active_database_records)
      pagy_headers_merge(pagy)        
end
```

Basically controlling whether to have pagination turned on or not. Is there a better way to do this?

**Comment by benkoshy** [comment]
What is the objective of what you are trying to do? ( trying to understand the context to avoid XY problem). Wanting to know why pagination should be turned off or on. (Turning off pagination might be a problem if you have large datasets. ) I think your front end helper will be expecting a pagy object so you might have to handle that. 

But generally speaking,  what you're trying to do is not handled by pagy itself (I might be mistaken though). Custom logic will be required,  not unlike what you've done. But pls feel free to elaborate on your objectives 

Ben

**Comment by ddnexus** [comment]
@c0mrade You are actually doing it right: implement your logic to use pagy or not. 

In general the condition to use a tool or not must be external to the tool itself.
Using a tool but telling it that you don't want to use it is quite contradictory. :) 
Just don't use it when you don't need it.
