### ISSUE TITLE
Is it possible to use pagy with searchkick when searching mutiple models.

### ISSUE THREAD

**Issue by antarr** [ddnexus/pagy#274]
I've seen the documentation to using pagy with searchkick [here](https://ddnexus.github.io/pagy/extras/searchkick.html). And it works fine for me in most cases. But I have a search function that searches multiple models. How can it get this working so pagy can link to more pages? It currently does not because searchkick on return the current page.

### SearchController
```ruby
  def search
    # binding.pry
    @search = if state_id.blank?
                Rails.cache.fetch("search/#{search_params}/#{page}/", expires_in: 1.hour) do
                  Searchkick.search(search_params, models: search_models, page: page, per_page: 10)
                end
              else
                Rails.cache.fetch("search/#{state_id}/#{search_params}/#{page}/#{state_id}/", expires_in: 1.hour) do
                  Searchkick.search(search_params, models: search_models, page: page, per_page: 10, where: { state_id: state_id })
                end
              end

    @pagy = Pagy.new_from_searchkick(@search)
    render partial: 'search/results'
  end
```

**Comment by ddnexus** [comment]
> It currently does not because searchkick on return the current page.

Not sure that I understand. Do you mean that you get only the "current page"? 
Does that mean that you have only one single page in the pagy navigation (while there should be more), or that you get the right number of pages, but the other pages shown are not linked?

I see that you are using a partial, so does that happen also with a regular helper?

**Comment by antarr** [comment]
The help doesn't render anything at all. Here is my slim template

```slim
section.post-notifications.mt-3
  .badge-wrapper
    .badge Showing #{@search.results.count} result(s).
  .search-results
    = render 'results_list', results: @search.results
  == pagy_next_link(@pagy, 'More...', 'id="next_link" style="display: none;"')

javascript:
  var loadNextPage = function(){
    if ($('#next_link').data("loading")){ return }  // prevent multiple loading
    var wBottom  = $(window).scrollTop() + $(window).height();
    var elBottom = $('#records_table').offset().top + $('#records_table').height();
    if (wBottom > elBottom){
      $('#next_link')[0].click();
      $('#next_link').data("loading", true);
    }
  };
```

**Comment by antarr** [comment]
I was able to figure it out. Use the wrong example there the style is set to display none.
