### ISSUE TITLE
Losing record when calling pagy()

### ISSUE THREAD

**Issue by michebble** [ddnexus/pagy#275]
Hi,

I use the entire collection for metrics at the top of the page, with the paginated list below. I noticed that the count of a paginated collection(3) I receive from the pagy method is less than the relation passed to it(4). This is a consistent and repeatable problem.

Here is the example code
```ruby
    21:  def foo_list_exists?
    22:    return false unless foos.exists?
    23:
    24:    @pagy, @paginated_foos = pagy(foos, items: 10)
 => 25:     binding.pry
    26:    true
    27:  end
```

At the break point I call 
```ruby
{ 
  paginated_count: @paginated_foos.count, 
  unpaginated_count: foos.count
}
=> {:paginated_count=>3, :unpaginated_count=>4}
```

Also if I pass pagy 21 records and receive a paginated collection of 9 on the first page, however the second page will return 10. 

I think this is related to the relation being passed having some ordering applied based on a related record.
In this case `Foo` has many `Bar`, and I apply they following scope
```ruby
foos = account.foos.order('bars.completed_at DESC')
```
Un-scoping the order from the relation when calling pagy resolves the issue, but I kind of want to keep the order.

Is this a bug, or am I trying to push the scoping too hard?

**Comment by ddnexus** [comment]
The automatic counting that pagy apply is a simple `collection.count(:all)` which is just a default: https://github.com/ddnexus/pagy/blob/ebbac6ba2dc2f1fa8b53f9a793408cec59245f71/lib/pagy/backend.rb#L21 
Due to limitation (and issues) of the AR count with complex scopes it may or may not work. When it doesn't you should get the count with your own calculation and pass it to the pagy constructor as indicated [here](https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes) and in other part of the same page.

That should solve your issue.

**Comment by michebble** [comment]
Thank you for your time and your fast reply. I have to say that Pagy is a pleasure to use and I am grateful that we can use it in our project. I did some further digging and realised this isn't an issue with Pagy, I apologise for jumping to conclusions and posting an issue without looking it further first.

Below is just an explanation for the sake of understanding, 

The problem I had was not the count of the relation but the actual number returned. 
```ruby
foos
=> [#<Foo:0x00007fb75069c0d0
  id: "2e1b9a23-8240-4a53-8df7-4416e5dafaba",
  title: "Foo 1">,
 #<Foo:0x00007fb743b45fa8
  id: "c9394e20-7837-47d7-89ea-402dee9470d6",
  title: "Foo 2">,
 #<Foo:0x00007fb743b450a8
  id: "c5d24a88-6a61-4869-91ec-a34fcaa0673b",
  title: "Foo 3">,
 #<Foo:0x00007fb743b3ff40
  id: "88dbb309-cc4d-4343-bd53-d82843c2757c",
  title: "Foo 4">]
    
@paginated_foos
=> [#<Foo:0x00007fb7462465a8
  id: "2e1b9a23-8240-4a53-8df7-4416e5dafaba",
  title: "Foo 1">,
 #<Foo:0x00007fb72d8f0408
  id: "c9394e20-7837-47d7-89ea-402dee9470d6",
  title: "Foo 2">,
 #<Foo:0x00007fb72d8eb368
  id: "c5d24a88-6a61-4869-91ec-a34fcaa0673b",
  title: "Foo 3">]
  ```
Looking at the Pagy code I noticed it just calls `offset` and `limit` on the relation. I found the values being used, in this case 0 and 4 respectively. Of course calling the same code on the relation before passing it caused the same unexpected behaviour.
