### ISSUE TITLE
pagy_array with :anchor

### ISSUE THREAD

**Issue by Tioneb12** [ddnexus/pagy#282]
I would like to add an anchor to pagy_arrray like :

`@pagy, @items   = pagy_array(@items, items: 18, anchor: '#top')`

but returns :
`/items?page=2#top`

insted :
`/items#top?page=2`

**Comment by ddnexus** [comment]
That is the correct way. See [this](https://superuser.com/questions/498617/does-an-anchor-tag-come-before-the-query-string-or-after)
