### ISSUE TITLE
Arabic language misses a few keys - see latest comment(s)

### ISSUE THREAD

**Issue by A-S-Baqtyan** [ddnexus/pagy#295]
Please add Arabic translation

**Comment by benkoshy** [comment]
@A-S-Baqtyan excellent suggestion, thank you! 

Unfortunately, I do not speak ANY Arabic. I can put in the PR myself, but I'd prefer someone with Arabic ability to vet it:  are you able to help out with that? 

If you can, I suspect @ddnexus will be only too happy to oblige with a merged PR. what do you think?

**Comment by A-S-Baqtyan** [comment]
With all fun, sure I will raise PR to add an Arabic language. Thanks.

**Comment by benkoshy** [comment]
@A-S-Baqtyan - here is a similar PR which may help (Danish translation): https://github.com/ddnexus/pagy/pull/232/files

This link may also help: https://ddnexus.github.io/pagy/api/frontend#i18n

**Comment by A-S-Baqtyan** [comment]
Yes I read your douc I saw your supported languages files I will raise PR
latter .

**Comment by A-S-Baqtyan** [comment]
Hi the PR was created successfully Arabic language pull request
<https://github.com/ddnexus/pagy/pull/298/files>.
Could you please merge it soon into master because we need this feature in
our rails application.
Please if you merge it into master send me a message here.

Thanks.

**Comment by ddnexus** [comment]
@A-S-Baqtyan Please, look at the [add-arabic-locale](https://github.com/ddnexus/pagy/tree/add-arabic-locale) branch. It is missing only the translation of a few keys. Please, create a PR out of it. Thanks.

**Comment by ddnexus** [comment]
The [add-arabic-locale](https://github.com/ddnexus/pagy/tree/add-arabic-locale) branch, misses only a few pluralization keys for the word "item/items". We need an arabic native speaker to complete it. Thanks.
