### ISSUE TITLE
Treat arrays like any other collection

### ISSUE THREAD

**Issue by SxDx** [ddnexus/pagy#3]
Adding a simple check to the `pagy_get_items`method makes pagy handle arrays nicely.
I feel like this is something that should be added?

```ruby
def pagy_get_items(collection, pagy)
    # handle arrays
    return collection[pagy.offset, pagy.items] if collection.is_a? Array
    # this should work with ActiveRecord, Sequel, Mongoid...
    collection.offset(pagy.offset).limit(pagy.items)
end
```

I have not done any performance testing,
* is there a faster method to check for Arrays than `is_a?`
* maybe `collection.drop(pagy.offset).first(pagy.items)`is faster.

**Comment by SleeplessByte** [comment]
@ddnexus there are use cases around paginating data not from ORM. Think:

- defined and or large list of constants
- data coming from a file or different IO (web request)
- data you have after a transformation that can't be done in SQL

**Comment by ddnexus** [comment]
A quite better approach would be just adding the `pagy_array` (and eventually `pagy_elasticsearch`) methods to the `Pagy::Backend` (using the same approach of the extras), so it will not override the `pagy` method behavior, and you could use different types of collections in the same app. You would have just to use the `pagy-extras` gem, then:

```ruby
include Pagy::Backend # as usual

@pagy, @items   = pagy_array(any_array)
@pagy, @results = pagy_elasticsearch(elasticsearch_results)
@pagy, @records = pagy(any_scope) # eventually aliased as pagy_orm for clarity
```
It looks like the way to go...

**Comment by SxDx** [comment]
> What is your specific case to paginate an array?

Pretty much any _non-Rails_ operation turns ActiveRecord Relations into an array. In my case I am dealing with Hotels from a DB and Prices from an API:

```ruby
hotels = Hotels.all
hotels.map(&:load_prices)
hotels.sort_by(&:lowest_price)
```

> The dilemma is: do we prefer it to work on everything out of the box (paying a small performance/coolness cost) 

Are you able to test the performance impact? As far as I can see the performance tests are not 
included in the repo (might be a good idea to include them anyway)

> Personally I use pagination on non-orm results all the time, for example json api responses

Same for me, as apps get bigger and more sophisticated it gets harder to stay on the _happy path_.

**Comment by gamafranco** [comment]
I think that creating an extension targeting Rails convenience should be the way to go.

We just need to make sure there are a few more use cases like this and benchmark it in a Pagy approach.

Those were my 5 cents. I might have a few more to share...

**Comment by ddnexus** [comment]
I am working on some specialized extra methods to handle also Arrays directly and without overriding. Specifically what I proposed in my previous post. It should be pushed in a couple of days.

**Comment by MSeneadza** [comment]
I'm fine with the work-around and I think having some kind of extension would be great.  But I wanted to add that I also paginate arrays all the time in Rails apps.  My case is usually that I have some complex SQL statement, often including a `UNION` and I execute it via `find_by_sql`.  My code has `Kaminari.paginate_array` all over the place.

**Comment by SleeplessByte** [comment]
@ddnexus your examples after my last reaction look good to me. Yes, I'd rather deal with it directly as well :) and I also agree on you of not adding a check. 

I think you got this!

**Comment by checkraiser** [comment]
We could add a named argument like `(collection, page:, items:, type: :collection)` with `collection` by default. That makes the interface consistent and easy to use.

**Comment by ddnexus** [comment]
> That makes the interface consistent and easy to use.
...but besides adding the need of one more argument, it adds also the need of a condition to check what is in that argument, which is the very thing we are trying to avoid here
BTW, thank you.

**Comment by ddnexus** [comment]
Implemented in `pagy-extra v0.2.0`.
- [array extra doc](https://ddnexus.github.io/pagy/pagy-extras/array)
- [how-to reference](https://ddnexus.github.io/pagy/how-to#paginate-an-array)

**Comment by ddnexus** [comment]
@grosser: worried about your fingers when writing an extra `-extras` in your Gemfile? :)

**Comment by grosser** [comment]
1 more gem that needs to be in sync and pagination seems to be the core
feature of the library ...
already got extra because I'm using bootstrap, but that feels like more of
a "should be in extra gem" to me

**Comment by ddnexus** [comment]
> 1 more gem that needs to be in sync and pagination seems to be the core
feature of the library ...

@grosser You might be right on this one ;). Thanks for the feedback.

Currently, the criteria applied to put features in the extras gem is just "everything is not strictly needed to make it work", but I will considering moving the `pagy-extras` into the `pagy` repo, and let the user require the extra s/he needs, reducing it to one gem with some extras not loaded by default.

It should make thing simpler for everybody.

**Comment by grosser** [comment]
yeah, would be simpler to not deal with 2 gems :)
FYI I usually use "they" to avoid "s/he"

**Comment by ddnexus** [comment]
"they" is a smarter choice, but "s/he" is kind of original :)
