### ISSUE TITLE
summary sentence

### ISSUE THREAD

**Issue by m-abdurrehman** [ddnexus/pagy#307]
Is there any way/support to have some sort of summary sentence? like

Showing 1 to 10 of 97 results
Showing 1 to 10 of 97 total
etc.

If not, I think its good to add this so user know the state with some stats

**Comment by ddnexus** [comment]
You know, I spent a lot of time to write a very detailed doc, and it would be very nice if the users would at least try to search before just asking, don't you think?

https://ddnexus.github.io/pagy/api/frontend

**Comment by benkoshy** [comment]
@m-abdurrehman thank you for posting the issue.  

* does this method do what you are after: https://ddnexus.github.io/pagy/api/frontend#pagy_infopagy-pagy_id--item_name--i18n_key- or please otherwise do shed some light on what you are trying to do.

* more importantly, if the above method does what you require, I would be very, very interested to hear your point of view on how things can be improved (e.g. whether documentation or otherwise).

chrs

Ben

**Comment by m-abdurrehman** [comment]
@benkoshy thanks for sharing it, I missed it, it worked!

If you do not mind, please do share a link or page where I can play around with different styles of pagination controls in different front ends.

Just my feeling, documentation can be improved by using words commonly used(I mean words dictionary) and more examples

Thanks again @benkoshy , and also @ddnexus for your great work and time.

Another issue, I am having in my project is that only text is clickable(leads to next page when using with `tailwind`)
I used pagy in an other project with `bootstrap` and whole `li` was clickable.

Not sure if I am missing something or it is by design

DOM/UI when using **bootstrap**

![tailwind](https://user-images.githubusercontent.com/59817964/122194883-4a88a580-ceaf-11eb-8ed4-9f640b82d081.png)


DOM/UI when using **tailwind**

![bootstrap](https://user-images.githubusercontent.com/59817964/122194869-46f51e80-ceaf-11eb-8193-573e2540dede.png)

**Comment by benkoshy** [comment]
Hi @m-abdurrehman 

### (a) different front ends with pagination controls: 

> If you do not mind, please do share a link or page where I can play around with different styles of pagination controls in different front ends.

Try using this repository here: https://github.com/benkoshy/pagy-rails

> documentation can be improved by using words commonly used(I mean words dictionary) and more examples

### (b) improvements suggested:

Can you please elaborate on your ideas here?

### (c) tailwind issue with links: i will check this out

> Another issue, I am having in my project is that only text is clickable(leads to next page when using with tailwind)
I used pagy in an other project with bootstrap and whole li was clickable.

I will investigate this and get back to you.

### (d) arabic knowledge?

am curious, but is there chance you know some Arabic?  If so, would you be able to add the missing key words here: https://github.com/ddnexus/pagy/issues/295?

**Comment by benkoshy** [comment]
@m-abdurrehman I was unable to get the container which contains the link to be clickable - with pure CSS 

Are you able to get it working? this might help: https://github.com/tailwindlabs/tailwindcss/issues/1041#issuecomment-513760267 

If not, then I wonder if it is work a new pagy front end tail wind template, rather than simply apply styles to the standard template?

**Comment by m-abdurrehman** [comment]
@benkoshy Thanks for your detailed responses.
I have little knowledge of Arabic but I can check with someone if I can help with this.

Regarding, Arabic words translation, if words context is also explain(may be as in a sentence or in image where it is being used) for the translator that would help him/her to pick the correct word

I will check my tailwind issue as per your suggestion

**Comment by benkoshy** [comment]
> Regarding, Arabic words translation, if words context is also explain(may be as in a sentence or in image where it is being used) for the translator that would help him/her to pick the correct word

The context is as below:

![image](https://user-images.githubusercontent.com/15097447/122664474-f6e6c680-d1e4-11eb-9026-fc73f84e542c.png)

If interested here are the instructions: 

1. Get this branch here: https://github.com/ddnexus/pagy/tree/add-arabic-locale
2. Go to this file:  `lib/locales/ar.yml` and add in the missing keys (check with someone who knows good Arabic).
3. Send in a PR.
