### ISSUE TITLE
Documentation needed for Searching across multiple models with Searchkick that all needed to be paginated together

### ISSUE THREAD

**Issue by leemcalilly** [ddnexus/pagy#319]
# Documentation Issue

- [X] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference/report/post that solves this problem
   
   - [X] The documentation is missing
   - [ ] I am providing the link of the documentation page/document displaying the issue

### Description
I was blocked on this issue until someone on Stackoverflow showed me that I needed to add `Searchkick.extend Pagy::Searchkick` to my Pagy initializer in order to search across multiple models and paginate them all together with Pagy. The solution and detailed description of my code can be found here:

https://stackoverflow.com/questions/68041398/how-to-paginate-multiple-models-with-the-pagy-gem-in-rails/68124989#68124989

Once I added `Searchkick.extend Pagy::Searchkick` to `initializers/pagy.rb` everything with Pagy and Searchkick worked as expected and described in the other documentation.
...

Thank you!

**Comment by ddnexus** [comment]
Sorry you got blocked on that. If you need fast answers (0-6 hours reply) you can also use the [Gitter Chat Support](https://gitter.im/ruby-pagy/Lobby).

Thank you for your report! I will fix it right away.
