### ISSUE TITLE
pagy*_nav_js methods do not provide a non-JavaScript version of the links

### ISSUE THREAD

**Issue by nomis** [ddnexus/pagy#321]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference/report/post that solves this problem
- [x] I did install/upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)

### Ruby/Rails/Sinatra/... Versions

* Ruby 2.5.1
* Rails 6.1.1
* Pagy 4.10.1

### Description

None of the `pagy*_nav_js` methods includes a non-JavaScript version of the links, so there is no fallback to HTML for web browsers without JavaScript support (or with JavaScript disabled). The "combo" version has working Back/Next links but the page selection doesn't work because it requires JavaScript.

I want to take advantage of the JavaScript navigation without losing basic HTML compatibility. The `nav` elements should contain normal links that are then replaced by JavaScript at runtime.

### Steps to reproduce the issue using the provided support

Using the standard `pagy_nav_js` function:
```
<%== pagy_nav_js(...) %>
```

The HTML output does not contain any content within the `nav` element, only data attributes for use by javaScript code:
```
<nav class="pagy-njs pagy-nav-js pagination" aria-label="pager" data-pagy-json="[&quot;nav&quot;,{&quot;before&quot;:&quot;\u003cspan class=\&quot;page prev disabled\&quot;\u003e\u0026lsaquo;\u0026nbsp;Prev\u003c/span\u003e &quot;,&quot;link&quot;:&quot;\u003cspan class=\&quot;page\&quot;\u003e\u003ca href=\&quot;/?page=__pagy_page__\&quot;   \u003e__pagy_page__\u003c/a\u003e\u003c/span\u003e &quot;,&quot;active&quot;:&quot;\u003cspan class=\&quot;page active\&quot;\u003e1\u003c/span\u003e &quot;,&quot;gap&quot;:&quot;\u003cspan class=\&quot;page gap\&quot;\u003e\u0026hellip;\u003c/span\u003e &quot;,&quot;after&quot;:&quot;\u003cspan class=\&quot;page next\&quot;\u003e\u003ca href=\&quot;/?page=2\&quot;   rel=\&quot;next\&quot; aria-label=\&quot;next\&quot;\u003eNext\u0026nbsp;\u0026rsaquo;\u003c/a\u003e\u003c/span\u003e&quot;},{&quot;0&quot;:[&quot;1&quot;,2,3,4,5,&quot;gap&quot;,117,118,119,120]},&quot;page&quot;]"></nav>
```

**Comment by ddnexus** [comment]
Hi @nomis 

> I want to take advantage of the JavaScript navigation without losing basic HTML compatibility.

What about:
```erb
<noscript><%== pagy_nav(@pagy)</noscript>
```

> The nav elements should contain normal links that are then replaced by JavaScript at runtime.

That would require 4 or 5 times the CPU and memory used for the current js helpers. It would be a huge waste of resources for all the apps that require javascript (probably a good 95%) because it would have to compute the plain html version even without ever using it.

Using a `noscript` is manual but limits the waste exclusively to the apps that really need it. And if you really want to have it all with minimal performance loss, you could implement your own solution, for example detecting javascript at the first request, storing a flag in the session, and serving js or non-js helpers based on the flag in all the next requests.

Please, let me know if that solves the issue.

**Comment by nomis** [comment]
Yes, `noscript` will do. The documentation could state that the JavaScript versions have no HTML equivalent if JavaScript is unavailable.

**Comment by ddnexus** [comment]
Yeah, there is space for improvement at least adding a code example in the "How To" section.  

Thank you @nomis

**Comment by ddnexus** [comment]
Added 71871016
