### ISSUE TITLE
Add: link to documentation under "about" section

### ISSUE THREAD

**Issue by benkoshy** [ddnexus/pagy#327]
### Suggested PR:

Most Github repositories find an easy to click link to the documentation under the "About" section. It's a very small thing, but I would really like it. i think others would too. Here is the suggested link: https://ddnexus.github.io/pagy/index#gsc.tab=0

![image](https://user-images.githubusercontent.com/15097447/129987528-7c85da2a-4cb1-49c7-abb8-1465f4620a49.png)

### How to add link:

(This is a github specific issue, I cannot myself make a PR for this).

![image](https://user-images.githubusercontent.com/15097447/129987817-0bb1c85e-e5e9-46e3-8883-c4da955a1ec1.png)

thx for the work on the gem!

**Comment by ddnexus** [comment]
Done! Thank you!
