### ISSUE TITLE
Uninitialized constant Pagy::VARS in pagy 5.0+

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#340]
_Not a real issue, but some people don't read changelogs!_ 😄

The `Pagy::VARS` has been renamed `Pagy::DEFAULT` since version `5.0.0`.

The fix is a simple search and replace, hovewer it's not the only one needed, so please check the [CHANGELOG](https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md).

Thank you

**Comment by PedroAugustoRamalhoDuarte** [comment]
Link for new initializer file template: https://github.com/ddnexus/pagy/blob/master/lib/config/pagy.rb
