### ISSUE TITLE
Rails internal params in metadata links

### ISSUE THREAD

**Issue by klausmeyer** [ddnexus/pagy#341]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [x] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked from one branch of the [Pagy Rails App](https://github.com/benkoshy/pagy-rails)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Versions

* Rails 6.1.4.1
* Pagy 5.1.2

### Description

Upgrading from 5.0.1 to version 5.1.2 of this gem causes one of our apps to generate JSON-API responses with links containing internal rails params in the query string.

### Steps to reproduce the issue using the provided support

* Run the following ruby-script: [my-problem.rb](https://gist.github.com/klausmeyer/2accc9aebbd3e60a7af74ad8cb5ac20f)
* Inspect the output:

Expected:

```json
{"data":[],"meta":{"first_url":"/?page=1","last_url":"/?page=1"}}
```

Actual:

```diff
- {"data":[],"meta":{"first_url":"/?page=1","last_url":"/?page=1"}}
+ {"data":[],"meta":{"first_url":"/?controller=test\u0026action=index\u0026page=1","last_url":"/?controller=test\u0026action=index\u0026page=1"}}
```

**Comment by fabian-as** [comment]
I'm afraid this bug reappeared in version 43.x. Do you mind having a look at it, @ddnexus?

**Comment by ddnexus** [comment]
What version are you using? Because it reappeared for a day (or maybe a few hours), and it has been squashed immediately. Please, ensure to use the latest version.
