### ISSUE TITLE
Multiplicated navs with `hotwired/turbo` cache

### ISSUE THREAD

**Issue by Gee-Bee** [ddnexus/pagy#350]
Prerequisites:
- Rails app with `hotwired/turbo` / `turbolinks`
- `_js` nav 

Steps to reproduce the problem:
1. open a page with a nav
2. click a link (navigate to another page with `turbo`)
3. use browser's `back` button - there are two navs on a page now
4. go back to step 2. to see more navs

Problem didn't exist in version `4.11`, because the content of the `nav` element was emptied [here](https://github.com/ddnexus/pagy/blob/b941ab3a186bb59a7ef9ae1a4e3b34e8a453e7da/lib/javascripts/pagy.js#L48).
This was removed in `5.0.0`.

Is this change intentional? If that's the case, maybe there should be some information in the docs about the need of empty the `nav` element manually using `turbo:before-cache` event?

**Comment by ddnexus** [comment]
It was unintentionally merged during a cleanup! Fix released in 5.6.4. Thank you!

**Comment by benkoshy** [comment]
I did not notice the reversion on the demo app.
