### ISSUE TITLE
Error on Mac M1

### ISSUE THREAD

**Issue by jahatten** [ddnexus/pagy#352]
Setting up my new computer and can't run my app: I get this error:

/Library/Ruby/Gems/2.6.0/gems/pagy-3.14.0/lib/pagy.rb:10:in `dirname': method name must be a Symbol but FalseClass is given (ArgumentError)

Any thoughts?

Tried different versions but didn't help.

Thanks

**Comment by ddnexus** [comment]
Are you using 3.14 instead of 5.6.6 because you are trying different versions or you really want to use that version? (FYI 5.6.6 works on ruby 2.5+).

You should follow the issue template: with it either you will find the problem by yourself, or you will provide a reproducible error.

**Comment by ddnexus** [comment]
Please, open a code issue following the template. Thanks.
