### ISSUE TITLE
Use count(:all) for AR

### ISSUE THREAD

**Issue by espen** [ddnexus/pagy#36]
When specifying which columns to retrieve using .select in Active Record it causes an issue when using .count as it will use all the columns from the select. Instead '*' should be used by setting :all.

Code example: https://github.com/espen/pagy_count_bug/blob/master/app/controllers/users_controller.rb

Failing test: https://github.com/espen/pagy_count_bug/blob/master/test/controllers/users_controller_test.rb

```
Error:
UsersControllerTest#test_shows_users:
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function count(bigint, character varying) does not exist
LINE 1: SELECT COUNT(id, name) FROM "users"
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT COUNT(id, name) FROM "users"
    app/controllers/users_controller.rb:6:in `index'
    test/controllers/users_controller_test.rb:5:in `block in <class:UsersControllerTest>'
```

Suggestion, use .count(:all) for AR in https://github.com/ddnexus/pagy/blob/master/lib/pagy/backend.rb#L21

**Comment by ddnexus** [comment]
PostgreSQL?

**Comment by espen** [comment]
Yes, I haven't tried MySQL so not sure if it differs. It works with SQLite but haven't checked what is going on there.

**Comment by ddnexus** [comment]
MySQL works... it's a known issue of PG, however it looks like the change wouldn't break anything.

**Comment by ddnexus** [comment]
pushed to rubygem (v0.8.2)
