### ISSUE TITLE
Regression in query strings in links from 5.9.1 to 5.9.2

### ISSUE THREAD

**Issue by davidwessman** [ddnexus/pagy#363]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [ ] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [x] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked from one branch of the [Pagy Rails App](https://github.com/benkoshy/pagy-rails)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Ruby|Rails|Sinatra|... Versions

Rails 5.2 (our app)
Rails 6.1 (standalone example)

### Description

When using pagy/extras/headers to get pagination-data in REST-api, the parameters are incorrectly escaped in 5.9.2.

5.9.1: `<http://www.example.com/?page=1&items=10>; rel=\"first\", <http://www.example.com/?page=1&items=10>; rel=\"last\"`
5.9.2: `<http://www.example.com/?page=1&amp;items=10>; rel=\"first\", <http://www.example.com/?page=1&amp;items=10>; rel=\"last\"`

### Steps to reproduce the issue using the provided support

`ruby pagy_bare_rails.rb`

<details>
  <summary>pagy_bare_rails.rb</summary>
  
```ruby
# frozen_string_literal: true

# Self-contained, bare rails app, usable to play with pagy
# and/or easily reproduce any pagy issue.

# Edit this file as you need

# USAGE:
#     ruby pagy_bare_rails.rb

# NOTICE: if you get any installation error(s) with the following setup
# temporarily remove `pagy/Gemfile` and `pagy/Gemfile.lock` from the repository
# because they may interfere with the bundler/inline.

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  # Debuggers
  gem 'debug'

  # gem 'debase'
  # gem 'ruby-debug-ide'

  gem 'pagy', '5.9.2'

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 6.1'
  gem 'actionpack'
  gem 'railties'
end

# Set up debugging tools
require "debug" ## etc

# pagy initializer - add your requirements here:
# https://ddnexus.github.io/pagy/extras
# https://ddnexus.github.io/pagy/api/backend

# Edit this section as you need
require 'pagy/extras/metadata'
require 'pagy/extras/overflow'
require 'pagy/extras/trim'
require 'pagy/extras/headers'
require 'pagy/extras/items'

Pagy::DEFAULT[:trim_extra] = false
Pagy::DEFAULT[:items] = 20
Pagy::DEFAULT[:metadata] = %i[first_url last_url]
Pagy::DEFAULT[:overflow] = :empty_page

# Rails set up:
require 'action_controller/railtie'
require 'active_record'

require 'minitest/autorun' # runs tests automatically

class TestApp < Rails::Application # :nodoc:
  config.root = __dir__
  config.hosts << 'www.example.com'
  config.hosts << 'example.org'
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index', as: 'test'
  end
end

class Record < ActiveRecord::Base; end # :nodoc:

class TestController < ActionController::Base # :nodoc:
  include Rails.application.routes.url_helpers

  include Pagy::Backend

  def index
    meta, _records = pagy(Record.none, items: 10)

    pagy_headers_merge(meta)

    render json: { data: [], meta: pagy_metadata(meta) }
  end

  ## override pagy methods if you need to here:
  # def pagy_get_items(collection, pagy)
  #  collection.limit(1)
  # end
end

class TestControllerTest < ActionDispatch::IntegrationTest # :nodoc:
  # Request helpers: https://api.rubyonrails.org/v6.1.4/classes/ActionDispatch/Integration/RequestHelpers.html
  # Available assertions: https://guides.rubyonrails.org/testing.html#available-assertions
  # Rails assertions: https://guides.rubyonrails.org/testing.html#rails-specific-assertions

  test 'pagy link parameters' do
    get '/'

    link = response.header['Link']
    assert_not_nil(link)
    assert_match('?page=1&items=10', link)
  end

  private

  def app
    Rails.application
  end
end
```

</details>

Thank you for a great gem 🙂, please let me know if I can do anything else to help.

**Comment by ddnexus** [comment]
Right! I changed also the test, overlooking that it should not be escaped in the headers.

Thank you for the perfect report!

**Comment by ddnexus** [comment]
I actually did not change the header test: there were no test cases for multiple params, so it didn't detect the problem. Added.
