### ISSUE TITLE
Use explicit meilisearch method

### ISSUE THREAD

**Issue by excid3** [ddnexus/pagy#366]
I've got an app using Ransack and it provides a `search` method that conflicts with Meilisearch.

In the meilisearch extra, this calls `search` directly which in our case is the Ransack search method.
https://github.com/ddnexus/pagy/blob/8d37ace7b4b699c59e0509f5f9fd3cd42db63d83/lib/pagy/extras/meilisearch.rb#L38

Meilisearch provides an `ms_search` and aliases it as `search` to prevent conflicts:
https://github.com/meilisearch/meilisearch-rails/blob/main/lib/meilisearch-rails.rb#L308

Would you accept a PR changing the Meilisearch extra to directly use `ms_search` so that it avoids conflicts automatically?

**Comment by ddnexus** [comment]
@excid3 Thanks for the report.

I just pushed version `5.10.0` that allows you to use:

```rb
Pagy::DEFAULT[:meilisearch_search] = :ms_search
```
which should cover also any custom methods that you may want to use in its place.

Commit 7ed8f6b1564537212716ff39e229e59f60e55f9e
