### ISSUE TITLE
Meilisearch page calculation is wrong?

### ISSUE THREAD

**Issue by excid3** [ddnexus/pagy#368]
Using `passive` mode for paginating Meilisearch results, we have to calculate the page ahead of time.

This calculation seems to be off by one page, because it doesn't take into account that the offset already has the first page removed since we have to pre-calculate that before calling `ms_search`
https://github.com/ddnexus/pagy/blob/8d37ace7b4b699c59e0509f5f9fd3cd42db63d83/lib/pagy/extras/meilisearch.rb#L22

I think this should be one of these instead?
```ruby
 vars[:page]  = [(results.raw_answer['offset'] + vars[:items]) / vars[:items], 1].max
# or
 vars[:page]  = [results.raw_answer['offset'] / vars[:items], 0].max + 1
```

This isn't an issue with `active` mode because Meilisearch handles the page calculation ahead of time.

**Comment by excid3** [comment]
An example controller action we had for calculating the page and seeing pagy's page off by one:

```ruby
    page = [params[:page].to_i, 1].max
    limit = Pagy::DEFAULT[:items]
    offset = (page - 1) * Pagy::DEFAULT[:items]
    p page, limit, offset #=> 4, 20, 60

    @records = Record.ms_search("*", { limit: limit, offset: offset })
    @pagy = Pagy.new_from_meilisearch(@episodes)

    p @pagy.page #=> 3
```

**Comment by ddnexus** [comment]
@excid3 I relayed on the test (containing a wrong expectation) when I reviewed the contribution. Sorry for that.

The fix is simple though:

https://github.com/ddnexus/pagy/blob/ccc8bc5ac90bff44c14857d280bf7964daaa34b3/lib/pagy/extras/meilisearch.rb#L22
