### ISSUE TITLE
Includes and joins ignored with meilisearch extra

### ISSUE THREAD

**Issue by coder2000** [ddnexus/pagy#378]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [ ] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked from one branch of the [Pagy Rails App](https://github.com/benkoshy/pagy-rails)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Ruby|Rails|Sinatra|... Versions
Ruby 3.1.0
Rails 7.0.2

### Description
Using `includes` with meilisearch extra doesn't execute the same queries and results in N+1.

### Steps to reproduce the issue using the provided support
Use `Model.includes` with `pagy_search`

Thank you!

**Comment by benkoshy** [comment]
Here is a very incomplete ruby script which might serve as a starting point to further investigate the issue: I beg the patience of the pagy community because it is not complete - unfortunately i am constrained. but hopefully it will save time for anyone researching this issue:

1. Ensure sql lite is installed.
2. `docker pull getmeili/meilisearch:latest # Fetch the latest version of Meilisearch image from Docker Hub`
4. `docker run -it --rm -p 7700:7700 getmeili/meilisearch:latest ./meilisearch -aster-key=password`
5. run the ruby script: `ruby pagy_bare_rails.rb` in a separate daemon

### Notes:
* Not sure how we can get rails console access given the script above. anyone know?
* Not sure how we can test whether N + 1 is actually occurring. Worse case scenario is that a basic rails app can be quite easily created with the script below to actually via rails console:

```ruby
# frozen_string_literal: true

# Self-contained, bare rails app, usable to play with pagy
# and/or easily reproduce any pagy issue.

# Edit this file as you need

# USAGE:
#     ruby pagy_bare_rails.rb

# NOTICE: if you get any installation error(s) with the following setup
# temporarily remove `pagy/Gemfile` and `pagy/Gemfile.lock` from the repository
# because they may interfere with the bundler/inline.

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  # Debuggers
  # gem 'debug'

  # gem 'debase'
  # gem 'ruby-debug-ide'

  # gem 'pagy'            # <--install from rubygems
  gem 'pagy', path: '../' # <-- use the local repo

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 6.1'
  gem 'actionpack'
  gem 'railties'
  gem 'meilisearch-rails'
  gem 'sqlite3'
  gem 'byebug'
end

# Set up debugging tools
# require "debug" ## etc

require "byebug" ## etc

# pagy initializer - add your requirements here:
# https://ddnexus.github.io/pagy/extras
# https://ddnexus.github.io/pagy/api/backend

require 'pagy/extras/meilisearch'


# Edit this section as you need
require 'pagy/extras/meilisearch'
require 'pagy/extras/metadata'

Pagy::DEFAULT[:trim_extra] = false
Pagy::DEFAULT[:items] = 20
Pagy::DEFAULT[:metadata] = %i[first_url last_url]
Pagy::DEFAULT[:overflow] = :empty_page

# Rails set up:
require 'action_controller/railtie'
require 'active_record'

require 'minitest/autorun' # runs tests automatically

class TestApp < Rails::Application # :nodoc:
  config.root = __dir__
  config.hosts << 'www.example.com'
  config.hosts << 'example.org'
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index', as: 'test'
  end

  MeiliSearch::Rails.configuration = {
    meilisearch_host: 'http://localhost:7700', # example: http://localhost:7700
    meilisearch_api_key: 'password',
  }
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")


ActiveRecord::Base.connection.create_table(:authors) do |t|
  t.text :name
end


ActiveRecord::Base.connection.create_table(:books) do |t|
  t.text :name
  t.references :author, foreign_key: true
end

class Author < ActiveRecord::Base
  include MeiliSearch::Rails
  extend Pagy::Meilisearch

  has_many :books

  meilisearch do
    attribute :name # only the attributes 'title', and 'author' will be sent to Meilisearch
    # all attributes will be sent to Meilisearch if block is left empty
  end
end

class Book < ActiveRecord::Base
  include MeiliSearch::Rails
  extend Pagy::Meilisearch

  belongs_to :author

  meilisearch do
    attribute :name
  end
end # :nodoc:

1.upto(11) do |i|
  Author.create(name: i)
end

Author.all.each_with_index do |author, i|
  Book.create(author: author, name: i)
end

Book.reindex!

class TestController < ActionController::Base # :nodoc:
  include Rails.application.routes.url_helpers
  include Pagy::Backend

  def index
    results         = Book.includes(:author).pagy_search("*")
    @pagy, @results = pagy_meilisearch(results, items: 10)

    @results.each do |r|
      r
    end

    render json: { data: [], meta: pagy_metadata(meta) }
  end

  ## override pagy methods if you need to here:
  # def pagy_get_items(collection, pagy)
  #  collection.limit(1)
  # end
end

class TestControllerTest < ActionDispatch::IntegrationTest # :nodoc:
  # Request helpers: https://api.rubyonrails.org/v6.1.4/classes/ActionDispatch/Integration/RequestHelpers.html
  # Available assertions: https://guides.rubyonrails.org/testing.html#available-assertions
  # Rails assertions: https://guides.rubyonrails.org/testing.html#rails-specific-assertions

  test 'pagy json output - example' do
    get '/'
    assert_equal response.parsed_body, { 'data' => [], 'meta' => { 'first_url' => '/?page=1', 'last_url' => '/?page=1' } }
  end

  def test_my_pagy_problem_here
    assert false
  end

  private

  def app
    Rails.application
  end
end

# or use rack to test:
class BugTest < Minitest::Test # :nodoc:
  include Rack::Test::Methods

  def test_my_pagy_problem_again
    get '/'
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by ddnexus** [comment]
Thank you @benkoshy. I cannot connect with the service. I see it in the terminal ut no way to make the connection from the app.

```
/usr/local/bundle/gems/meilisearch-0.18.1/lib/meilisearch/http_request.rb:107:in `rescue in send_request': An error occurred while trying to connect to the MeiliSearch instance: Failed to open TCP connection to 0.0.0.0:7700 (Connection refused - connect(2) for 0.0.0.0:7700) (MeiliSearch::CommunicationError)
 ```

@coder2000 I have no time to prepare any setup right now. Could you provide a minimal rails app to work on it? Thank you.

**Comment by benkoshy** [comment]
> Thank you @benkoshy. I cannot connect with the service. I see it in the terminal ut no way to make the connection from the app. I tried different setup (docker compose)...
> 
> ```
> /usr/local/bundle/gems/meilisearch-0.18.1/lib/meilisearch/http_request.rb:107:in `rescue in send_request': An error occurred while trying to connect to the MeiliSearch instance: Failed to open TCP connection to 0.0.0.0:7700 (Connection refused - connect(2) for 0.0.0.0:7700) (MeiliSearch::CommunicationError)
> ```

That's bizarre. 

I ran meilesearch in one terminal window and then ran the ruby script in another without problem. I set the password as password and it worked fine here not sure why it's not working on another machine? I could reproduce the alleged bug though.

**Comment by benkoshy** [comment]
Sorry there's a typing mistake when setting the master key.  Maybe that caused the connection error?

**Comment by ddnexus** [comment]
No problem with the typo, it was not that because I already fixed it. It was a stupid naming conflict with my automatic docker setup. I didn't have time to investigate, now after running my setup again with the right name and it works. Thank you Ben!

**Comment by ddnexus** [comment]
OK, I've got a min to try it. You can set it up easily by simply adding a line after the extend:

```
extend  Pagy::Meilisearch
ActiveRecord_Relation.include Pagy::Meilisearch  # <--- makes it work also for includes
```

I will add that to the docs

**Comment by ddnexus** [comment]
@coder2000 I forgot: you should also use it a bit differently than when you call it on the model (in order to avoid to fire the includes queries twice):

```
# calling it on the model
results         = Author.pagy_search(params[:q])
@pagy, @results = pagy_meilisearch(results, items: 10)

# calling it on the includes AR relation
@pagy, @results = pagy_meilisearch(Author.includes(:books).pagy_search(params[:q]), items: 10)
```

Please, let me know if that works
