### ISSUE TITLE
`pagy_bootstrap_combo_nav_js` page selector is rendered as disabled button

### ISSUE THREAD

**Issue by adas172002** [ddnexus/pagy#381]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [ ] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [ ] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked from one branch of the [Pagy Rails App](https://github.com/benkoshy/pagy-rails)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Ruby|Rails|Sinatra|… Versions
ruby 2.7.3, ror 7.0.2.3 with `importmap-rails` gem, bootstrap 5.1.3 installed via official `bootstrap` gem w/o jQuery
...

### Description
`pagy_bootstrap_combo_nav_js` is rendering the following HTML code, with page selector input disabled

```
<div class="pagy-combo-input btn btn-primary disabled" style="white-space: nowrap;">
   <label>Page <input type="number" min="1" max="26" value="6" class="text-primary" style="padding: 0; border: none; text-align: center; width: 3rem;"> of 26</label>
</div>
```

### Steps to reproduce the issue using the provided support
I found no similar issues here.

**Comment by benkoshy** [comment]
Right. Apologies,  I had forgotten about it. 

I'll post a fix shortly.

**Comment by benkoshy** [comment]
![image](https://user-images.githubusercontent.com/15097447/160721625-640448e9-2531-4f26-b450-75877cf3049a.png)

Can you please confirm that you are not trying to go to a page before page 1?

**Comment by ddnexus** [comment]
@adas172002 Where is the code support required to post a code issue?

You have 8 different way to pick from! Please, pick one, attach it to this issue and I will reopen it.

Thank you.
