### ISSUE TITLE
Prev button doesn't appear

### ISSUE THREAD

**Issue by tilipim123** [ddnexus/pagy#382]
Using pagy and stimulus and passing a link extra
 

    <%== pagy_nav(@pagy, link_extra: 'data-action="click->table#searchPagy"') %> 

when press next button in page 1 i'm getting this 

    < 2 ... 6 7 8 9 10 11 12 13 14 ... 23 Next >

Prev button is not appearing

[![enter image description here][1]][1]

link.call when 1 return nil

  [1]: https://i.stack.imgur.com/R6coJ.png

**Comment by ddnexus** [comment]
Here is what the `Pagy::Console` gives me for page 2:

```ruby
pagy = Pagy.new(count: 100, page: 2)
pagy_nav(pagy)
````

```html
<nav class="pagy-nav pagination" aria-label="pager">
  <span class="page prev">
    <a href="http://www.example.com/subdir?page=1" 
       data-action="click->table#searchPagy" 
       rel="prev" 
       aria-label="previous">&lsaquo;&nbsp;Prev</a>
  </span>
  <span class="page">
    <a href="http://www.example.com/subdir?page=1" 
       data-action="click->table#searchPagy" 
       rel="prev">1</a>
  </span>
  <span class="page active">2</span> 
  <span class="page">
    <a href="http://www.example.com/subdir?page=3" 
       data-action="click->table#searchPagy" 
       rel="next">3</a>
  </span> 
  <span class="page">
    <a href="http://www.example.com/subdir?page=4" 
       data-action="click->table#searchPagy">4</a>
  </span>
  <span class="page">
    <a href="http://www.example.com/subdir?page=5" 
       data-action="click->table#searchPagy">5</a>
  </span> 
  <span class="page next">
    <a href="http://www.example.com/subdir?page=3" 
       data-action="click->table#searchPagy" 
       rel="next" aria-label="next">Next&nbsp;&rsaquo;</a>
  </span>
</nav>
```

As you can see the page 1 is correctly printed.

I have no idea how you managed to get that, so I am not able to reproduce your issue.

Please, pick one of the 8 ways indicated in the issue template to supply a code support, and the issue will get reopened.

Thank you
