### ISSUE TITLE
Pagy with esbuild

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [ddnexus/pagy#383]
# Documentation Issue

- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
   
   - [ ] The documentation is missing
   - [x] I am providing the link of the documentation page|document displaying the issue

### Description
Hello, i trying to update my ruby on rails old app to use esbuild as default js transpile, but i cannot make pagy works. I try to follow this docs (https://github.com/ddnexus/pagy/tree/master/lib/javascripts), but i cannot make it works.

package.json
```json
  "scripts": {
    "build": "NODE_PATH=\\\"$(bundle show 'pagy')/lib/javascripts\\\" esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds"
  }
```

application.js
```js
// Entry point for the build script in your package.json

import "@hotwired/turbo-rails"
import './controllers'
import './modules/jquery'
import 'select2'
import 'jquery-mask-plugin'
import * as bootstrap from "bootstrap"

let popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
let popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})

import './modules/global'

import Pagy from "pagy-module";
window.addEventListener("turbo:load", Pagy.init);
```
Error
```
23:07:24 js.1   | [DEPRECATED] use `bundle info pagy` instead of `bundle show pagy`
23:07:24 js.1   | ✘ [ERROR] Could not resolve "pagy-module"
23:07:24 js.1   | 
23:07:24 js.1   |     app/javascript/application.js:17:17:
23:07:24 js.1   |       17 │ import Pagy from "pagy-module";
23:07:24 js.1   |          ╵                  ~~~~~~~~~~~~~
23:07:24 js.1   | 
23:07:24 js.1   |   You can mark the path "pagy-module" as external to exclude it from the bundle, which will remove this error.

```
...

Thank you!

**Comment by benkoshy** [comment]
@PedroAugustoRamalhoDuarte 

It is difficult to reproduce your issue. Would you be opposed to studying the following repo (https://github.com/benkoshy/pagy-esbuild) and/or reproducing your problem?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks @benkoshy , it was my bad, when a copy the command to my IDE adds some \ in command. I change my package.json to yours and it working.
 I will make a PR trying to solve the DEPRECATED bundle info command
