### ISSUE TITLE
Docs refer to a tailwind extra but the 5.10.1 gem does not have this 

### ISSUE THREAD

**Issue by craic** [ddnexus/pagy#387]
# Documentation Issue

- [x ] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
   
   - [ ] The documentation is missing
   - [ x] I am providing the link of the documentation page|document displaying the issue

### Description

The docs refer to a tailwind extra :
https://ddnexus.github.io/pagy/extras#gsc.tab=0

but this does not exist in 
~/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/pagy-5.10.1/lib/pagy/extras

so 
require 'pagy/extras/tailwind'
in pagy.rb prevents the app starting up

The detail page (https://ddnexus.github.io/pagy/extras/tailwind.html#gsc.tab=0) reads as though you should copy and paste the styles listed into another file - but it is not clear to me exactly where these should go

If you can point me in the right direction then I will be happy to update the docs

thanks

...

Thank you!

**Comment by benkoshy** [comment]
> The detail page (https://ddnexus.github.io/pagy/extras/tailwind.html#gsc.tab=0) reads as though you should copy and paste the styles listed into another file - but it is not clear to me exactly where these should go

It really depends on your set up, and what framework you are using: 

- If you're using webpacker, try this: https://github.com/benkoshy/pagy-rails/commit/c78f6a9988597140dc3f848e546347b63dd5cbe9
- If you're using sprockets: put it in your `app/assets)/stylesheets/tailwind.css` and ensure that file is included in your manifest file.
- Or if you're using [css bundling rails](https://github.com/rails/cssbundling-rails):
> How do I import relative CSS files with Tailwind?
> If you want to use @import statements as part of your Tailwind application.js file, you need to [configure Tailwind to use postcss and then postcss-import](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports). But you should also consider simply referring to your other CSS files directly, instead of bundling them all into one big file. It's better for caching, and it's simpler to setup. You can refer to other CSS files by expanding the stylesheet_link_tag in application.html.erb like so: <%= stylesheet_link_tag "application", "other", "styles", "data-turbo-track": "reload" %>.

> If you can point me in the right direction then I will be happy to update the docs
> thanks

If many other people ask them same question, I would favour the adding to the docs (and bearing the maintenance burden), but till that time, I wouldn't worry about making a PR.

**Comment by ddnexus** [comment]
Thanks for your report.

> The detail page (https://ddnexus.github.io/pagy/extras/tailwind.html#gsc.tab=0) reads as though you should copy and paste the styles listed into another file - but it is not clear to me exactly where these should go

Indeed the detail page says **it is not an extra**, so we should correct the extra list and state it there too.

You can paste and edit that content in any css file that your app uses, wherever it is in your app.

**Comment by ddnexus** [comment]
06c313cf39400bd64041961fee62f865aa8cce72
