### ISSUE TITLE
no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by sai1024** [ddnexus/pagy#391]
no implicit conversion of Symbol into Integer

**Comment by sai1024** [comment]
database: mongodb
ruby: 3.0.3
rails: 6.2.1

**Comment by ddnexus** [comment]
Mongoid doesn't like ,collection.count(:all)
https://github.com/ddnexus/pagy/blob/9be18148cfa3298435c7f94b86618a2ea451a28f/lib/pagy/backend.rb#L21

You should override it https://ddnexus.github.io/pagy/how-to.html#override-pagy-methods
