### ISSUE TITLE
Documentation and Pagy config pointing to renamed file/module Shared

### ISSUE THREAD

**Issue by djpremier** [ddnexus/pagy#398]
# Documentation Issue

- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
   
   - [ ] The documentation is missing
   - [x] I am providing the link of the documentation page|document displaying the issue

### Description
In this commit (https://github.com/ddnexus/pagy/commit/89b9bf6570b57fc5f2ab1f9935cd964f9e14b028), the `pagy/extra/shared` has been renamed to `pagy/extra/frontend_helpers`, but in documentation and in pagy config file the value is still the old one

In documentation of Extras -> Methods (https://ddnexus.github.io/pagy/extras#methods):
![image](https://user-images.githubusercontent.com/17091381/180093851-c0233534-4186-42fc-a80b-5304e4f0b237.png)

In configuration (https://github.com/ddnexus/pagy/blob/master/lib/config/pagy.rb#L103-L104):
![image](https://user-images.githubusercontent.com/17091381/180094054-eb9fb66a-a196-40e4-b154-57dd0d188f34.png)

...

Thank you!

**Comment by djpremier** [comment]
This generate error if activated:
` /usr/local/bundle/ruby/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in 'require': cannot load such file -- pagy/extras/shared (LoadError)`

**Comment by benkoshy** [comment]
@djpremier nice work - you have spotted and solved the problem. If you put in a PR, you would win the day. Feel free to do so, or otherwise LMK and I can do it for you.
