### ISSUE TITLE
Feature request: Adding the ability to override the base URL

### ISSUE THREAD

**Issue by elliotlarson** [ddnexus/pagy#401]
## Description

I have a couple of turbo frames with paginated collections on the same page.  For each of the collections, I'd like to be able to tell pagy to point to a different resource endpoint.  Something like:

```ruby
@pagy_foos, @foos = pagy(Foo.all, url: foos_url)
@pagy_bars, @bars = pagy(Bar.all, url: bars_url)
```

It looks like the `pagy_url_for` helper does this at the end:

```ruby
"#{request.base_url if absolute}#{request.path}#{query_string}#{vars[:fragment]}"
```

Really what I'm hoping for is something like this (I think): 

```ruby
"#{vars[:url] || request.base_url if absolute}#{vars[:path] || request.path}#{query_string}#{vars[:fragment]}"
```

... so that the `base_url` or the `path` is overridable. 

The idea is that I'd like to be able to easily override the base path or url for the pagy links so that I could update my turbo frame by hitting different index end points for each, even though they both got initially loaded on a different page.

**Comment by benkoshy** [comment]
> The idea is that I'd like to be able to easily override the base path or url for the pagy links so that I could update my turbo frame by hitting different index end points for each, even though they both got initially loaded on a different page.

Would you pls be able to elaborate on your use-case with a basic example?

```rb
<%= turbo_frame_tag "foos" do %>
     <%== pagy_nav(@pagy, ...) %>
<% end %>

# what is the behaviour you want?
# why?
```

The reason I am asking is to ensure we avoid the [XY problem](https://benkoshy.github.io/2019/06/24/what-is-the-xy-problem.html)

(This sounds like a feature request more than it does a bug. Would you be opposed to moving it to a Github Discussion thread?)

**Comment by elliotlarson** [comment]
Yeah, totally a feature request.  I put "Feature request" in the title because I wasn't quite sure how else to identify it as such.  I'm cool moving to a GitHub discussion.  Sorry for my noobness, Are you saying "let's close this and start a new thread instead", or are you saying, "are you cool with me making this a discussion thread instead" (assuming you can move this without having to manually copy stuff over)?

**Comment by benkoshy** [comment]
> Are you saying "let's close this and start a new thread instead"

Yes, I would strongly recommend this course of action.

**Comment by elliotlarson** [comment]
Feature request discussion: https://github.com/ddnexus/pagy/discussions/402

**Comment by MarchandMD** [comment]
this discussion 404s

**Comment by ddnexus** [comment]
Sorry, the discussion has likely been deleted in a cleanup. 

The feature has been implemented by adding the `:request_path` variable.
