### ISSUE TITLE
Reduce items minimum to 0 and possibly return empty array from pagy_get_items if items: 0 is specified

### ISSUE THREAD

**Issue by edeesis** [ddnexus/pagy#406]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [x] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [ ] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked of [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Ruby|Rails|Sinatra|... Versions

Ruby 3.1.2
Rails 6.1.5

### Description

We would like to be able to send a `items` parameter of 0 and have it skip evaluating an ActiveRecord query and instead return an empty Array. If it helps, we're trying to evaluate the count of the query without getting the actual results.

While we would be happy to override the [pagy_get_items](https://github.com/ddnexus/pagy/blob/master/lib/pagy/backend.rb#L28) method for that, the items parameter is set to a [minimum of 1](https://github.com/ddnexus/pagy/blob/master/lib/pagy.rb#L101), so it throws a VariableError when we try this.

### Steps to reproduce the issue using the provided support

```ruby
Loading development environment (Rails 6.1.5)
irb(main):001:0> require 'pagy/console'
=> true
irb(main):002:0> include Pagy::Console
=> Object
irb(main):003:0> pagy_extras :items
Required extras: :items
=> nil                                                                                    
irb(main):004:0> pagy, items = pagy([1, 2, 3], items: 0)
```

Thank you!

**Comment by ddnexus** [comment]
@edeesis So, what would you need the pagy object for, if you already know that the items to paginate would be none?

If you really need a pagy object with no items, you can pass `count: 0` and you will get the `pagy` and `items` set to what you are asking.

**Comment by ddnexus** [comment]
@edeesis Is this still an issue after my previous comment?

**Comment by edeesis** [comment]
Hey. I'll go ahead and close this. We ended up working around it in our own way.

Thanks!
