### ISSUE TITLE
THe i18n extra doesn't work 

### ISSUE THREAD

**Issue by rebelwarrior** [ddnexus/pagy#41]
Whenever I require the file in my rails app:
```
=> Booting Puma
=> Rails 5.1.6 application starting in development
=> Run `rails server -h` for more startup options
Exiting
org/jruby/ext/pathname/RubyPathname.java:195:in `initialize': no implicit conversion of nil into String (TypeError)
```
if I don't require the i18n extra the error goes away. 

What could be causing this?

**Comment by rebelwarrior** [comment]
I added the locale file form the gem to my locales too (just in case). Didn't help.

**Comment by ddnexus** [comment]
Hi @rebelwarrior. I just tried it and it is a stupid bug introduced by the last refactoring of I18n.
There are still no tests for the extras: that is why that happened. Sorry for that. Working on the fix now.

**Comment by ddnexus** [comment]
Done. Pushed v0.8.5 to rubygem. @rebelwarrior just update the gem and it should be solved. Thanks.
