### ISSUE TITLE
`ArgumentError` when using `pagy_bootstrap_nav_js` with `countless` under Ruby 3

### ISSUE THREAD

**Issue by hvanhonacker** [ddnexus/pagy#410]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [ ] Plain ruby file that can run as `ruby my-problem.rb`
   - [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [x] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [ ] Link of my own branch forked from pagy, which contains an added test file  
   - [ ] Link of my own branch forked of [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)
   - [ ] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [ ] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Versions

- Ruby 3.1.2p20
- Rails 6.1.7
- Pagy 5.10.1

### Description

Under Ruby 3, when using `pagy/extras/bootstrap` and `pagy/extras/countless`, calling `pagy_bootstrap_nav_js` raises the following error:

Using Ruby 3: 

```
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
lib/pagy.rb:47:in `series'
```

### Steps to reproduce the issue using the provided support

Using Ruby 3, run: 

```ruby
# frozen_string_literal: true

# Self-contained, bare rails app, usable to play with pagy
# and/or easily reproduce any pagy issue.

# Edit this file as you need

# USAGE:
#     ruby pagy_bare_rails.rb

# NOTICE: if you get any installation error(s) with the following setup
# temporarily remove `pagy/Gemfile` and `pagy/Gemfile.lock` from the repository
# because they may interfere with the bundler/inline.

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  # Debuggers
  # gem 'byebug'

  # gem 'debase'
  # gem 'ruby-debug-ide'

  # gem 'pagy'            # <--install from rubygems
  gem 'pagy', path: '../' # <-- use the local repo

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 6.1'
  gem 'actionpack'
  gem 'railties'
end

# Set up debugging tools
# require 'byebug' ## etc

# pagy initializer - add your requirements here:
# https://ddnexus.github.io/pagy/extras
# https://ddnexus.github.io/pagy/api/backend

# Edit this section as you need
# require 'pagy/extras/metadata'
# require 'pagy/extras/overflow'
# require 'pagy/extras/trim'
require 'pagy/extras/bootstrap'
require 'pagy/extras/countless'

# Pagy::DEFAULT[:trim_extra] = false
# Pagy::DEFAULT[:items] = 20
# Pagy::DEFAULT[:metadata] = %i[first_url last_url]
# Pagy::DEFAULT[:overflow] = :empty_page

# Rails set up:
require 'action_controller/railtie'
require 'active_record'

require 'minitest/autorun' # runs tests automatically

class TestApp < Rails::Application # :nodoc:
  config.root = __dir__
  config.hosts << 'www.example.com'
  config.hosts << 'example.org'
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index', as: 'test'
  end
end

class Record < ActiveRecord::Base; end # :nodoc:

class TestController < ActionController::Base # :nodoc:
  include Rails.application.routes.url_helpers

  include Pagy::Backend
  include Pagy::Frontend

  def index
    meta, _records = pagy_countless(Record.none, items: 10)
    render html: pagy_bootstrap_nav_js(meta)
  end

  ## override pagy methods if you need to here:
  # def pagy_get_items(collection, pagy)
  #  collection.limit(1)
  # end
end

# or use rack to test:
class BugTest < Minitest::Test # :nodoc:
  include Rack::Test::Methods

  def test_pagy_bootstrap_nav_js_with_countless
    get '/'

    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end

```

**Comment by ddnexus** [comment]
02013d426fdd56c366332fc450bd63197a86762c
