### ISSUE TITLE
Pagy::VariableError (expected :page >= 1; got "-11"): i got the error minus value pass in page pagination 

### ISSUE THREAD

**Issue by bhavesh-vadhvana** [ddnexus/pagy#414]
# Code Issue
- [x] I researched through the [documentation](https://ddnexus.github.io/pagy/), the [pagy issues](https://github.com/ddnexus/pagy/issues) and a known Search Engine, and there is no reference|report|post|video that solves this problem
- [x] I did install|upgraded to the latest version of pagy (or the latest `3.*` for pagy legacy)
- [x] I am providing at least one of the following working and self-contained code support that can reproduce this issue:
   
   - [x] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/api/console)
   - [x] Plain ruby file that can run as `ruby my-problem.rb`
   - [x] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)
   - [x] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)
   - [x] Link of my own branch forked from pagy, which contains an added test file  
   - [x] Link of my own branch forked of [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)
   - [x] Link of a standalone `docker image` downloadable from a docker repository (e.g. dockerhub.com)
   - [x] `docker-compose` file that can be run with `docker-compose up` (and doesn't need to be built because it uses only docker images and no local context)

### Ruby|Rails|Sinatra|... Versions

...

### Description

...

### Steps to reproduce the issue using the provided support

...

Thank you!

**Comment by benkoshy** [comment]
@bhavesh hi i appreciate the 

I don't see a reproducible sample where I can replicate the error? How can I solve it without the sample?

**Comment by bhavesh-vadhvana** [comment]
i have send this img in pass the URL in page -11 value in got the errors














---- On Thu, 08 Dec 2022 15:45:34 +0530 Ben Koshy ***@***.***> wrote ---





https://github.com/bhavesh hi i appreciate the msg

I don't see a reproducible sample where I can replicate the error? How can I solve it without the sample?

**Comment by benkoshy** [comment]
Screenshot is no good. 


Can you reproduce here: https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb
