### ISSUE TITLE
Docs additions

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#419]
Integrate with retype the docs addition made by #404 ~~#411~~, #417.

**Comment by benkoshy** [comment]
* #404 is done and improved with: https://github.com/benkoshy/pagy/commit/de415a56ace0d5f901bcb3c05f1aa460b28e3ce9 on the retype branch.

The others to follow.

**Comment by benkoshy** [comment]
* Was reviewing #411 - and the [following commit 02013d426fdd56c366332fc450bd63197a86762c](https://github.com/ddnexus/pagy/commit/02013d426fdd56c366332fc450bd63197a86762c) - my understanding is that countless cannot support javascript_combo navs?
* What documentation changes should accompany this PR? (It wasn't altogether clear to me) - the following?

```diff
-     The `pagy_info` helper, which uses the total `count` is not supported.
+     The `pagy_info` and all the `*_combo_nav_js` helpers that use the total `count` are not supported.
```

And then a change log entry?

Pointer much appreciated.

Ben

**Comment by ddnexus** [comment]
The commit adds test for `nav_js`, not `combo_nav_js` as mentioned in the description  (which indeed is cot supported by countless).

I overlooked the description and focused only on the commit. We have to sort this out.

Maybe @hvanhonacker can clarify that.

**Comment by ddnexus** [comment]
OK, I got a minute and it looks like there's just a typo in the description of #411.

Now I remember looking at the #410 and reproducing the error... indeed this is a fix for `*nav_js` and the `*combo_nav_js` has nothing to do with it.

So back to the only doc to change: there is no docs affected. My bad indicating this PR. Please, skip #411.

Thanks

**Comment by benkoshy** [comment]
chrs - that leaves only #417 remaining.

**Comment by ddnexus** [comment]
"chrs"??? 🤔

**Comment by ddnexus** [comment]
#417 b5f64f5e99425d3820935a836e721f5cc314cb8b
