### ISSUE TITLE
Returns blank with ransack

### ISSUE THREAD

**Issue by amanullahtanweer** [ddnexus/pagy#42]
Result with pagy gem returns blank array [] if number of `records` are equal to pagination `items`

For eg: if i have 20 records in database and pagination items are set to 20 per pages, it returns blank array.

Sample Code

```
@q = assets.ransack(params[:q])
@pagy, @assets = pagy(@q.result)
```

**Comment by ddnexus** [comment]
Hi. That is a bug already fixed quite a number of versions ago. (see #15). Please update the Gemfile to the last version in rubygems, and don't forget to read the CHANGELOG for eventual breaking changes. Thanks.
