### ISSUE TITLE
Docs: Add How To entry for "Paginate multiple collections in the same action"

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#451]
#450 is a recurring problem that is not directly documented.

We should add:

- A simple explanation and example.
- A link to [this post](https://www.imaginarycloud.com/blog/how-to-paginate-ruby-on-rails-apps-with-pagy) for a complete example.
- The alternative suggestion for using [turbo frames](https://turbo.hotwired.dev/handbook/frames)

Also link the text "paginate different collections in the same action" in the [Customize the page param](https://ddnexus.github.io/pagy/docs/how-to/#customize-the-page-param) to the new entry.

**Comment by benkoshy** [comment]
Agreed this needs a fuller treatment via Rails + documentation.  I think I replicated similar functionality in one of my apps.  The same to be said about infinite pagination. Both deserve an example on pagy-rails.

**Comment by ddnexus** [comment]
Documentation: [Paginate multiple independent actions](https://ddnexus.github.io/pagy/docs/how-to/#paginate-multiple-independent-collections)
