### ISSUE TITLE
Docs: Typo on I18n Extra page

### ISSUE THREAD

**Issue by Birdie0** [ddnexus/pagy#459]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

In [initializer](https://github.com/ddnexus/pagy/blob/master/docs/extras/i18n.md#synopsis) section it tells to require `pagy/extras/headers` instead of `pagy/extras/i18n`.

**Comment by benkoshy** [comment]
Fixed with #463.  @Birdie0 Thank you for your contribution :pray:

 If I've missed the mark, please feel free to open.
