### ISSUE TITLE
Pagy and ActiveModelSerializer Question

### ISSUE THREAD

**Issue by KevinColemanInc** [ddnexus/pagy#46]
I am trying to figure out the best way to use Pagy with [active_model_serializers](https://github.com/rails-api/active_model_serializers).

With Kaminari, the object I am trying to present knows meta information about how it was serializered, such as number of pages or what is the next page.

In the controller, I can do:

```
def index
  users = User.all.page(params[:page)
  render json: users
end
```

and the serializers can ask the presentation object (`users`), how many pages it is and what the records are.

With `pagy`, we have 2 presentation objects, which adds complexity to the controllers and view layers.

```
def index
  pagy, users = pagy(User.all)
  render json: users,
         pagy: pagy
end
```

Then in my adapter, I need to look at the `option` variable instead of the object that is presented to determine that pagination meta data.

```
  def serialize
    serialized_hash = if options.key?(:root) && options[:root].nil?
                        serialized_hash = serializer_attributes
                      else
                        { root => serializer_attributes }
                      end
    build_meta
    serialized_hash[meta_key] = meta unless meta.blank?
    serialized_hash
  end

  def build_meta
    self.meta ||= { }
    self.meta.merge!(pagination_attributes) if include_pagination_attributes?
  end

  def pagination_attributes
    obj = serializer.object
    {
      pagination: {
        current_page: obj.page,
        next_page:    obj.next,
        prev_page:    obj.prev,
        total_pages:  obj.pages,
        total_count:  obj.count
      }
    }
  end
```

I totally get you want to avoid adding pagination logic to `active_record` models.  But having two presentation objects (`pagy` and `records`) instead of one increases complexity in the view and controller layers.,

I am thinking about having a Frankenstein presenter object, that combines the `Pagy` instance with the `active_record_relation` to combine them into one interface, instead of two.

Is there a cleaner solution here?

**Comment by ddnexus** [comment]
This is interesting. I will analyze the options available and I will let you know ASAP.

**Comment by ddnexus** [comment]
@KevinColemanInc I am a bit tight with time right now but I would like to get this issue solved ASAP, so your help would be great. Could you prepare a minimal app that shows the problem and your implementation of the solution? I could just clone the repo and give you a good answer quickly. Thanks.

**Comment by ddnexus** [comment]
@KevinColemanInc I have also a few questions, so could we have an [interactive chat](https://gitter.im/ruby-pagy/Lobby) any time soon?

**Comment by ddnexus** [comment]
If I understand it correctly, it looks like the only thing you need is adding a few methods to the paginated collection object. What about adding this to your application controller:

```ruby
    def pagy_extended(collection, vars={})
      pagy, paginated = pagy(collection, vars)
      { current_page: pagy.page,
        next_page:    pagy.next,
        prev_page:    pagy.prev,
        total_pages:  pagy.pages,
        total_count:  pagy.count }.each do |meth, val|
        paginated.define_singleton_method(meth){ val }
      end
      return pagy, paginated
    end
```
then you can use it in place of the vanilla `pagy` method:

```ruby
def index
  _, users = pagy_extended(User.all)
  render json: users
end

**Comment by KevinColemanInc** [comment]
To future people,
I ended up adding this to by `ApplicationController`

```

  def paginate(results, options={})
    pagy, records = if results.is_a? Array
      pagy_array(results, options)
    else
      pagy(results, options)
    end

    records.define_singleton_method(:pagy){ pagy }
    records
  end
```

and in my controllers, I can just do as I did with Kaminari:

```
render json: paginate(users)
```

In my active model serializer adapter, I access pagy via `serializer.object.pagy` to attach the serializer meta data to the response.

**Comment by ddnexus** [comment]
@KevinColemanInc Glad that you got it working.

What is the reason you didn't use the way I suggested? I thought that would have saved you the need to manually attach the serializer meta data.

BTW, in the `pagy_extended` I returned also the pagy object, so that same method could be used for serialization and for regular pagination.

**Comment by KevinColemanInc** [comment]
I made a few changes, so I am not specifically sure what you are asking about.

I prefer having a single interface for paginating enumerable objects, so I don't have to think is this an array or is this an AR relation.

I think creating that pagination hash should stay in the adapter class, because it seems more of a view layer concern than a controller.

90% of our controller endpoints use `active_model_serializers`, so having to defined 2 variables is unnecessary boiler plate.  Personally, I am not a huge fan of ruby's multi-return feature, because its not very explicit what is being returned or the order of the response.

For the controllers that render HTML, I will probably stick with what the docs recommend though.
