### ISSUE TITLE
Docs: Arel extra is missing from pagy.rb

### ISSUE THREAD

**Issue by Birdie0** [ddnexus/pagy#460]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

Configuration file [pagy.rb](https://github.com/ddnexus/pagy/blob/master/lib/config/pagy.rb) is missing mentioning of [Arel Extra](https://ddnexus.github.io/pagy/docs/extras/arel/).

**Comment by benkoshy** [comment]
Thank you for your contribution!

Closing in light of #462. Please re-open if I have missed the mark.

**Comment by Birdie0** [comment]
Thanks! Maybe also add `See https://ddnexus.github.io/pagy/docs/extras/arel` line for consistency?
