### ISSUE TITLE
Bug: Pagy seems to ignore #limit scope

### ISSUE THREAD

**Issue by cappe** [ddnexus/pagy#461]
### Before submitting...

- [X] I upgraded to the latest version of pagy
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### I am providing...

- [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console)

- [ ] Plain ruby file that can run as `ruby my-problem.rb`

- [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)

- [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)

- [ ] Link of my own branch forked from pagy, which contains an added test file

- [ ] Link of my own branch forked from [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)

- [X] A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

### Description

When using ActiveRecord (with Rails), Pagy seems to unscope/reset `#limit` scope:

```
class UsersController < ApplicationController
  def index
    @pagy, @users = pagy(User)
    @pagy_limited, @users_limited = pagy(User.limit(2))
  end
end
```
The `@users_limited` returns up to `Pagy::DEFAULT[:items]` amount of items. Intuitively, it should return up to 2 items.

I cannot wrap my head around it if it's intended this way or not. To me it feels dangerous as I'd _need_ to know that it behaves this way.

Here's a minimal project that reproduces the behavior, just `docker compose up`: [https://github.com/cappe/pagy-bug-report-scoping](https://github.com/cappe/pagy-bug-report-scoping)

**Comment by benkoshy** [comment]
Not sure if this is something that pagy can solve:

```rb
scope = User.limit(1)
scope.limit(100) # will come out with 100 records, not 1
```

**Comment by ddnexus** [comment]
> The @users_limited returns up to Pagy::DEFAULT[:items] amount of items. Intuitively, it should return up to 2 items.Pagy just applies the limit to whichever scope you are paginating, hence it basically reset the AR limit to the `:items` variable.

**Comment by ddnexus** [comment]
Added [warning info](https://ddnexus.github.io/pagy/docs/how-to/#control-the-items-per-page) to the how-to docs

**Comment by cappe** [comment]
@benkoshy @ddnexus Thank you for taking time to answer, and adding the warning in the docs.

I think the AR behavior for (multiple) limits makes sense. When done by the developer, it's usually somewhat visible and explicit. However, when Pagy does it, it's behind the scenes. I may know that Pagy (or pagination in general) is basically limit + offset but the next person may not (especially newcomers).

> hence it basically reset the AR limit to the `:items` variable.

If I use limit in my code, I should be confident it to be applied, not reset behind the scenes.

**Comment by ddnexus** [comment]
> If I use limit in my code, I should be confident it to be applied, not reset behind the scenes.

OK. So the alternative would be ignoring the `:items` if the collection is an ActiveRecord AND the collection has a set `limit`.

If you want to do it automatically, it would mean checking that 2 conditions at each request, which would be an expensive performance hit

**Comment by cappe** [comment]
Not too ideal either. I guess having the warning in the docs is enough. Considering use cases for using limit along with pagination isn't too common anyway. Thanks for helping sorting this out.
