### ISSUE TITLE
no headers created?

### ISSUE THREAD

**Issue by MarieDomoscio** [ddnexus/pagy#53]
I am trying to switch from will_paginate to pagy, but pagy does not seem to add headers to the response to a request.
With will_paginate, I have:
![image](https://user-images.githubusercontent.com/19777055/41666475-e927766a-74aa-11e8-92a8-857d44137758.png)

Is there any equivalent with pagy to get that information?

I added include Pagy::Backend to my ApplicationController, and I am using ruby 2.3.0. The views are kept really simple, for example for my model "content", it looks like:
"json.array!(@contents) do |content|
  json.extract! content, :id, :uid, :created_at, :updated_at, :name, :content_url, :format
end"

**Comment by ddnexus** [comment]
Hi Marie,
Pagy doesn't currently add any header, however there are 2 gems that support Pagy and are specific for API pagination that you might find useful:

- https://github.com/davidcelis/api-pagination
- https://github.com/IcaliaLabs/pager-api

Besides that, we are always available to discuss any useful addition to Pagy. What would you like to have specifically from Pagy?

**Comment by MarieDomoscio** [comment]
I would have liked to have information about how many pages there are, and the number of elements in the collection. Api-pagination works perfectly for that indeed.
