### ISSUE TITLE
count not working when collection request has "distinct"

### ISSUE THREAD

**Issue by MarieS1415** [ddnexus/pagy#54]
Hello,
I get my collection with the following request:
> @contents = Content.select("distinct on (contents.name) contents.*")
This request is working and does the expected behavior when run in console.

And I would like to paginate it using api-pagination and pagy:
> @contents = paginate @contents

This triggers the following error:
PG::SyntaxError: ERROR: syntax error at or near "on" LINE 1: SELECT COUNT(distinct on (contents.name) contents.*) FROM "c... ^ : SELECT COUNT(distinct on (contents.name) contents.*) FROM "contents"

But I cannot see which line it comes from.

**Comment by ddnexus** [comment]
It probably come from [here](https://github.com/ddnexus/pagy/blob/32d0afc85c0ebe1fa2a9bd4cc37569417f45b683/lib/pagy/backend.rb#L20).

Please, try to do:

```ruby
@contents = Content.select("distinct on (contents.name) contents.*"
@contents.count(:all)
```
and if that is the culprit it should raise the same error.
Please, let me know.

**Comment by ddnexus** [comment]
BTW, I suppose that `paginate @contents` comes from `api-pagination`. Please, could you try:

```ruby
collection = Content.select("distinct on (contents.name) contents.*"
@pagy, @contents = pagy(collection)
```

And see if it raises the same error?

**Comment by MarieS1415** [comment]
The code

> @contents = Content.select("distinct on (contents.name) contents.*"
@contents.count(:all)

is working correctly.

The second piece of code is working correctly too, however using it, I loose the headers of api-pagination.

I was using will_paginate before pagy, with api-pagination, and it was not raising this error. It is possible that pagy and api-pagination are not working together the same way?

**Comment by ddnexus** [comment]
> The second piece of code is working correctly too, however using it, I loose the headers of api-pagination.

That means that pagy has no problems with your collection, so it might be either a problem of configuration or a possible bug of `api-pagination`.

It would probably be useful to post the problem as an issue of `api-pagination`.

**Comment by ddnexus** [comment]
It looks like the api-pagination issue has been solved.
