### ISSUE TITLE
Bug: "warning: the following paths have collided" when cloning the repo

### ISSUE THREAD

**Issue by tagliala** [ddnexus/pagy#541]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

```
$ git clone https://github.com/ddnexus/pagy.git
Cloning into 'pagy'...
remote: Enumerating objects: 29136, done.
remote: Counting objects: 100% (8802/8802), done.
remote: Compressing objects: 100% (1172/1172), done.
remote: Total 29136 (delta 4445), reused 8398 (delta 4075), pack-reused 20334
Receiving objects: 100% (29136/29136), 13.15 MiB | 8.93 MiB/s, done.
Resolving deltas: 100% (17022/17022), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '.idea/runConfigurations/Pagy_App.xml'
  '.idea/runConfigurations/pagy_app.xml'
```

This happens on macOS because it is a case insensitive file system, so `Pagy_App.xml` and `pagy_app.xml` are the same file

This has been introduced with d4c3004, when `pagy.xml` has been renamed to `pagy_app.xml`

**Comment by ddnexus** [comment]
Thank you for the report.

It looks like a new version of RubyMine updated the naming... I will have to check which one is the right one and delete the unused one.

**Comment by tagliala** [comment]
Thanks
