### ISSUE TITLE
total of elements in headers not correct

### ISSUE THREAD

**Issue by MarieS1415** [ddnexus/pagy#55]
Hello,

I am using api_pagination and pagy, and one of the collection I want to paginate is created with a join: therefore the count does not render the correct number of elements. I used to fix it when I used will_paginate by adding a parameter "total_entries" to the paginate function of api_pagination, but it is not working anymore.

`@contents = paginate @contents, total_entries: @contents.count(:id)`

I assume that pagy does not give the possibility to overwrite the count, is it the case?

Thank you !

**Comment by ddnexus** [comment]
Hi @MarieS1415 
Pagy can actually override any param. If you create a `Pagy` instance with `Pagy.new` you should pass the required `:count` variable, and if you are using the `pagy` controller method you can pass the count with the vars hash. For example:

```ruby
# instead of 
pagy(collection)
# pass an explicit count
pagy(collection, count: your_count)
```
Just guessing from your example, but did you try something like the following?

```ruby
@contents = paginate @contents, count: @contents.count(:id)
```

**Comment by MarieS1415** [comment]
I just tried your option, and it still does not take it into account...

**Comment by ddnexus** [comment]
Just checked and it looks like `api_pagination` doesn't merge the `:count` options [here](https://github.com/davidcelis/api-pagination/blob/289716e3d19d210365b69d4fee99e86f55b0f65a/lib/api-pagination.rb#L68). Open an `api_pagination` issue would probably be useful. Thanks.

**Comment by MarieS1415** [comment]
It has been done just there : [`https://github.com/davidcelis/api-pagination/issues/106#issuecomment-401877989`](https://github.com/davidcelis/api-pagination/issues/106#issuecomment-401877989).
Thanks!
