### ISSUE TITLE
Bug: Inconsistent Pagination Behavior with Specific Pagy Size Configuration

### ISSUE THREAD

**Issue by Hangman2arb** [ddnexus/pagy#558]
### Before submitting...

- [X] I upgraded to the latest version of pagy
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### I am providing...

- [ ] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console)

- [ ] Plain ruby file that can run as `ruby my-problem.rb`

- [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)

- [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)

- [ ] Link of my own branch forked from pagy, which contains an added test file

- [ ] Link of my own branch forked from [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)

- [ ] A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

### Description

I am encountering an unusual and inconsistent behavior when using the Pagy gem for pagination in a Rails application. I have set the Pagy size configuration to `[1,0,0,1]` with the expectation that it would display only the first page, the last page, the current page, and the navigation links to the next and previous pages, without any intermediate pages.

Here is the code snippet setting the Pagy size configuration in the initializer:

```ruby
Pagy::DEFAULT[:size] = [1,0,0,1]
```

However, this is not the behavior that I am observing. While navigating through the paginated pages, I have found that, on specific pages (such as 3, 4, 17, and 18 out of 20 total pages), additional intermediate page numbers are unexpectedly appearing in the pagination navigation. Here are examples of the inconsistent behavior I am experiencing:

On page 3:
```html
<nav class="pagy-nav pagination">
  <!-- Expected only 1, 3, and 20 to be displayed, but 2 is also displayed -->
  <span class="page"><a href="/customers?page=1">1</a></span>
  <span class="page"><a href="/customers?page=2" rel="prev">2</a></span>
  <span class="page active">3</span>
  <span class="page gap">…</span>
  <span class="page"><a href="/customers?page=20">20</a></span>
</nav>
```

On page 4:
```html
<nav class="pagy-nav pagination">
  <!-- Correctly displays only 1, 4, and 20 -->
  <span class="page"><a href="/customers?page=1">1</a></span>
  <span class="page gap">…</span>
  <span class="page active">4</span>
  <span class="page gap">…</span>
  <span class="page"><a href="/customers?page=20">20</a></span>
</nav>
```

On page 18:
```html
<nav class="pagy-nav pagination">
  <!-- Expected only 1, 18, and 20 to be displayed, but 19 is also displayed -->
  <span class="page"><a href="/customers?page=1">1</a></span>
  <span class="page gap">…</span>
  <span class="page active">18</span>
  <span class="page"><a href="/customers?page=19" rel="next">19</a></span>
  <span class="page"><a href="/customers?page=20">20</a></span>
</nav>
```

I have ensured that there is no additional Pagy configuration in the controller or view that might be overriding the default configuration, and I have also checked the behavior in different browsers to rule out caching issues.

I am unsure if this is a bug within Pagy or if there is an aspect of the configuration that I might be overlooking. Any insights or guidance on how to achieve the expected behavior consistently across all pages would be greatly appreciated.

**Comment by Hangman2arb** [comment]
I have been investigating the inconsistent pagination behavior further and I believe I have located a potential area in the codebase where the issue may be originating.

The behavior I observed was inconsistent pagination, especially on specific pages (e.g., page 4 with a `size` configuration of `[1,1,1,1]`). The inconsistency is characterized by the unexpected appearance of additional page numbers in the pagination series.

Upon closer examination of the `series` method within Pagy, I observed the following fragment of code which seems to be responsible for determining whether a `:gap` should be inserted in the series of pages:

```ruby
if (left_gap_end - left_gap_start).positive?
  series.push(*start...left_gap_start, :gap)
  start = left_gap_end + 1
end
if (right_gap_end - right_gap_start).positive?
  series.push(*start...right_gap_start, :gap)
  start = right_gap_end + 1
end
```

In the specific scenario when I am on page 4 and the `size` is `[1,1,1,1]`, the variables `left_gap_start` and `left_gap_end` both equate to 2, resulting in a difference of 0. Since the condition for inserting a `:gap` is that this difference be positive, no `:gap` is inserted in this case, leading to the unexpected display of page number 2 in the pagination series.

The variable values in this scenario are as follows:
- `left_gap_start` = 2
- `left_gap_end` = 2
- `right_gap_start` = 6
- `right_gap_end` = 549

Given this, it appears that the logic may not be handling cases where the difference between `left_gap_end` and `left_gap_start` (or `right_gap_end` and `right_gap_start`) is 0. Adjusting this logic to correctly handle such edge cases might resolve the inconsistent pagination behavior observed.

I hope this additional information proves helpful in identifying and resolving the issue. Please let me know if further details or clarification are needed.

**Comment by ddnexus** [comment]
Thank you for the detailed report. I will look into it ASAP.

**Comment by Hangman2arb** [comment]
Hi @ddnexus,

Thank you for your prompt response and clarification. Based on your explanation, I understand that the `:gap` is replaced with the actual page number when the length of the gap is only one page. Is there any configuration or workaround available that could prevent this behavior and maintain the `:gap` symbol even when there is only one page missing in the series? Additionally, is there a way to directly hide the `:gap`?

I appreciate your time and assistance on this matter.

**Comment by ddnexus** [comment]
You cannot actually "prevent" the gap string, but you can change it (e. g. with a space or an empty string) in the i18n dictionary files.

However, that would not change the logic that replaces it with a page number when the gap page is only one.

If you really need that you should override the `series` method with your own logic.

IIRC you are the 3rd person asking that so far, so it looks like it's probably simpler to keep it like it is ATM, or... open a feature request discussion and see how it goes.

**Comment by ddnexus** [comment]
@Hangman2arb is this still an issue?

**Comment by ddnexus** [comment]
Closed due to inactivity.
