### ISSUE TITLE
Bulma extra

### ISSUE THREAD

**Issue by enzinia** [ddnexus/pagy#56]
Hello!

Have idea to add [Bulma CSS framework](https://bulma.io/) extra for it [pagination](https://bulma.io/documentation/components/pagination/) component. Helper, templates, just like a Bootstrap one.
I use Bulma in my projects and it will be great to have official extra for it.

What do you think @ddnexus, is it necessary?

**Comment by ddnexus** [comment]
@enzinia if you could submit a pull request it would be very welcome. Please, let me know if I can help. Thanks.
