### ISSUE TITLE
Bug: Alias for an aggregate result is removed

### ISSUE THREAD

**Issue by AbhayVAshokan** [ddnexus/pagy#642]
### Before submitting...

- [X] I upgraded to the latest version of pagy
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### I am providing...

- [X] Simple step by step list that would work in IRB with the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console)

- [ ] Plain ruby file that can run as `ruby my-problem.rb`

- [ ] Edited copy of the single file [pagy_standalone_app.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone_app.ru)

- [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)

- [ ] Link of my own branch forked from pagy, which contains an added test file

- [ ] Link of my own branch forked from [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)

- [ ] A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

### Description

The following are the two ActiveRecord models that are used for describing the below issue:

```rb
# models/page.rb
class Page < ApplicationRecord
  has_many :blocks
end

# models/block.rb
class Block < ApplicationRecord
  belongs_to :page
end
```

Let's say, I need to fetch the name of all the `pages` along with the number of blocks in each page, and sort them in the descending order of number of blocks. Here is the ActiveRecord query that I execute:

```rb
pages_and_block_counts = Page
  .left_joins(:blocks).select("pages.name, COUNT(blocks.id) AS blocks_count")
  .group("pages.id")
  .order("blocks_count DESC") # Notice that the blocks_count is referenced from line 2.
```

**Pagination**

Pagination using Kaminari will correctly execute the query and return the expected result.

```rb
paginated_result = pages_and_block_counts.page(1).per(2) # 1 and 2 are arbitrary values chosen randomly.

# SELECT pages.name, COUNT(blocks.id) AS blocks_count FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id" ORDER BY blocks_count DESC LIMIT $1 OFFSET $2  [["LIMIT", 2], ["OFFSET", 0]]
```

Pagination using pagy:

```rb
pagy(pages_and_block_counts)

# SELECT COUNT(*) AS "count_all", "pages"."id" AS "pages_id" FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id" ORDER BY blocks_count DESC

# PG::UndefinedColumn: ERROR:  column "blocks_count" does not exist (ActiveRecord::StatementInvalid)
# LINE 1: ... BY "pages"."id" ORDER BY blocks_cou..
```

If you notice closely, this query starts with `SELECT COUNT(*) as count_all` instead of the expected `SELECT COUNT(blocks.id) AS blocks_count`. This missing alias is thrown as an error in the order method.

**Workaround**: Remove the aliasing to execute multiple SQL queries.

```rb
pages_and_block_counts = Page.left_joins(:blocks).select("pages.name, COUNT(blocks.id)").group("pages.id").order("COUNT(blocks.id) DESC")
pagy(pages_and_block_counts)

# Page Count (1.0ms)  SELECT COUNT(*) AS "count_all", "pages"."id" AS "pages_id" FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id" ORDER BY COUNT(blocks.id) DESC
# Page Load (2.8ms)  SELECT pages.name, COUNT(blocks.id) FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id" /* loading for pp */ ORDER BY COUNT(blocks.id) DESC LIMIT $1 OFFSET $2  [["LIMIT", 11], ["OFFSET", 0]]
````

**Comment by ddnexus** [comment]
@AbhayVAshokan Thank you for the report and the solution ;)

Pagy strives to be as agnostic as possible, hence it "shouldn't" know much about ActiveRecord, and it does not by design.

However, since AR is overwhelmingly used in most apps, pagy tries to be as "AR friendly" as possible, as you can notice in the code that it runs on ANY collection in order to get the collection count:

https://github.com/ddnexus/pagy/blob/42b99f80a87304248bf29e14e7f0d3cacc6e978c/lib/pagy/backend.rb#L21

That's hardly a one-size-fits-all solution, but it works in an overwhelmingly number of cases. Indeed you may need to  override the method with apps using other ORMs (usually by simply removing the `:all` argument). In cases where the `collection.count(:all)` does not work, you can pass your own count to the helper as explained [here](https://ddnexus.github.io/pagy/docs/how-to/#custom-count-for-custom-scopes).

What would be the right statement to get the right count from the `pages_and_block_counts` in your alias case?

**Comment by ddnexus** [comment]
I can consider the possibility to add a `:count_args` pagy variable, which could be used to pass the arguments to the `count`. Defaut `count__args: [:all]`. That would allow things like:

```ruby
@pagy, @records = pagy(my_collection, count_args: ['age']) 
```

or set its default to an empty array, for the ORMs that use count with no argument.

Would that be helpful also in your case?

**Comment by AbhayVAshokan** [comment]
Thank you for the prompt responses. I am assuming that `count` is used to set the upper limit during pagination. In my case setting count as `Page.count` gets the work done.

That said, we might need to look at why `collection.count(:all)` overrides the SQL query itself. `count` is an internal abstraction that shouldn't interfere with the query itself. 

> Would that be helpful also in your case?

Yes, passing arguments to `count` will definitely be helpful. Again, it will be better if the custom aliases are not overriden.

**Comment by ddnexus** [comment]
I am a bit rusty on ActiveRecord, and I forgot why we have to add `:all` to the statement in the past, but there was some problem with not passing anything to `count` AFAIR.

It's just a matter of picking the right default at this point, since `:count_args` will definitely be part of the incoming 7.0.

Maybe things changed more recently and we could remove `:all`?

**Comment by ddnexus** [comment]
@benkoshy ?

**Comment by AbhayVAshokan** [comment]
Passing `:all` arg to the `count` method is necessary. The original query can have custom select statements. The `COUNT` operation will not perform correctly in all these situations. 

For instance, in my example, a `count` without `:all` will try to perform `COUNT(pages.name, COUNT(blocks.id) AS blocks_count) AS "count_pages_name_count_blocks_id_as_blocks_count"` and fail miserably.

**Comment by AbhayVAshokan** [comment]
I took some time to understand the problem better. I think this is how I should write a custom count operation:

```diff
- pagy(pages_and_block_counts)
+ count = pages_and_block_counts.unscope(:order).count(:all).size
+ pagy(pages_and_block_counts, count: count)
```

1. Remove the `order` query.
2. Perform a `count(:all)` operation.
3. Since `count(:all)` returns a hash, perform a `size` operation.

This will execute two SQL queries 
```SQL
  Page Count (1.1ms)  SELECT COUNT(*) AS "count_all", "pages"."id" AS "pages_id" FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id"
  Page Load (0.8ms)  SELECT pages.name, COUNT(blocks.id) AS blocks_count FROM "pages" LEFT OUTER JOIN "blocks" ON "blocks"."deleted_at" IS NULL AND "blocks"."page_id" = "pages"."id" GROUP BY "pages"."id" /* loading for pp */ ORDER BY "pages"."sequence" ASC, blocks_count DESC LIMIT $1 OFFSET $2  [["LIMIT", 11], ["OFFSET", 0]]
```

I am contented with the workaround in the issue description. It also performs two SQL queries.

Adding a `count_args` will not be helpful in my case :(

**Comment by ddnexus** [comment]
OK, so the `:all` IS necessary, but it may not work with "custom select statements", or group, order etc., right? That's a quite old AR problem AFAIR.

Does Kaminari return the right count (i.e. the right number of pages) automatically? If it does it would be nice to know how.

> It also performs two SQL queries

Standard pagination requires knowing the count, and unluckily the count doesn't come with the results in most DBs, but requires an extra query.

If avoiding one query is a priority, `Pagy::Countless` can help (if your pagination requirements can accommodate its limitations).

> I am contented with the workaround in the issue description

If the count is right, it looks the simplest solution to me!

**Comment by ddnexus** [comment]
[Pagy::Countless](https://ddnexus.github.io/pagy/docs/api/countless/)
[Countless extra](https://ddnexus.github.io/pagy/docs/extras/countless/)
