### ISSUE TITLE
Docs: 7.0 has an undocumented breaking change for active page styling

### ISSUE THREAD

**Issue by bb** [ddnexus/pagy#646]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

In Pagy < 7, the HTML for the active page link was like `<span class="page active">5</span>`.
With v7 or more specifically with https://github.com/ddnexus/pagy/commit/88ff10ec5fa44096f079f2838d9df93c3b68dbcc#diff-809433e4eccc6a2abd4873c74189da89e579dd8e514d4a62d725c424bcfce8e4R18, it changed to `<span class="page active"><a role="link" aria-disabled="true" aria-current="page">5</a></span>`.

This breaks the Tailwind example because `.pagy-nav .page a` (in  https://github.com/ddnexus/pagy/blob/master/docs/extras/tailwind.md?plain=1#L49) and `.pagy-nav .page.active` (in https://github.com/ddnexus/pagy/blob/master/docs/extras/tailwind.md?plain=1#L50) are matching different nested elements, resulting in something which looks like a button within a button.

A possible solution might be to change the first rule from `.pagy-nav .page a` to `.pagy-nav .page a[href]`.

Other places are also likely to be affected, e.g. the JS nav a few lines below.

**Comment by benkoshy** [comment]
Thanks for the report.

![styling_problem_1](https://github.com/ddnexus/pagy/assets/15097447/43d8c2ee-2530-4e75-8eee-71f7dc2698bc)

Looks like it is an issue with the second styles too:

![styling_problem](https://github.com/ddnexus/pagy/assets/15097447/2c25685d-26b7-4146-93d8-1a3164ab246b)

Your suggestions look good too:

![looks_good](https://github.com/ddnexus/pagy/assets/15097447/317fb758-f7cb-4aa3-bf82-a5ef9cde0276)

I"ll x2 check with the JS styles and post a PR later on crediting you - or you can copy the commit directly.

**Comment by ddnexus** [comment]
I am documenting the change in the CHANGELOG as we speak.

**Comment by ddnexus** [comment]
Thanks to everybody. I decided to refactor the style and it's really short and simple to change to anything you want now.

You can see it [here](https://ddnexus.github.io/pagy/docs/extras/tailwind/).

The recommended fix is actually... switching to the new style rules, and change what you need by just editing the classes in the `@apply` lines. It covers all nav helpers in just a few LOC.

Thanks

**Comment by bb** [comment]
Thank you very much! The new rules look much better than my quickfix 🤩

**Comment by ddnexus** [comment]
@bb Your quick fix was perfectly functional with the old rules. The problem was that they were a bit convoluted and overlapping, hence the refactoring.
