### ISSUE TITLE
Docs: https://ddnexus.github.io/pagy/quick-start/#configure

### ISSUE THREAD

**Issue by luiseduardoaugusto** [ddnexus/pagy#668]
### Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

Pagy.rb is 404.
It doesnt redirect to download file

**Comment by ddnexus** [comment]
Thank you!
