### ISSUE TITLE
Bug: Missing initializer in documentation

### ISSUE THREAD

**Issue by ACPK** [ddnexus/pagy#669]
### Before submitting...

- [X] I upgraded to the latest version of pagy
- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### I am providing...

- [X] Simple snippet that would work **"as-is" in vanilla IRB (no rails console) without invoking any external/non-pagy code or gem!** (You may find the [Pagy::Console](https://ddnexus.github.io/pagy/docs/api/console) helpful)

- [ ] Plain ruby file that can run as `ruby my-problem.rb`
- [ ] Edited copy of the single file [pagy_standalone.ru](https://github.com/ddnexus/pagy/blob/master/apps/pagy_standalone.ru)

- [ ] Edited copy of the single file [pagy_bare_rails.rb](https://github.com/ddnexus/pagy/blob/master/apps/pagy_bare_rails.rb)

- [ ] Link of my own branch forked from pagy, which contains an added test file
- [ ] Link of my own branch forked from  [any of the rails apps listed here.](https://github.com/stars/benkoshy/lists/rails-demo-apps-for-pagy)

- [ ] A `docker-compose` file that uses only docker images and no local context and runs with `docker-compose up`

### Description

The link to the initializer in the documentation is broken. https://ddnexus.github.io/pagy/quick-start/#configure

Page.rb goes to: https://ddnexus.github.io/lib/config/pagy.rb

**Comment by ddnexus** [comment]
Thank you!
