### ISSUE TITLE
Docs: lost section about wrap existing pagination with pagy_calendar

### ISSUE THREAD

**Issue by axlekb** [ddnexus/pagy#693]
### 👀 Before submitting...

- [X] I searched through the [Documentation](https://ddnexus.github.io/pagy/)
- [X] I searched through the [Issues](https://github.com/ddnexus/pagy/issues)
- [X] I searched through the [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

### Description

There's a link in the [calendar extra docs](https://ddnexus.github.io/pagy/docs/extras/calendar/) (Image 1) to an example, but that section appears to be missing (Image 2).  

### Image 1:
![image](https://github.com/ddnexus/pagy/assets/2972314/725271d2-3203-4920-ae3f-4b7425b207b9)

### Image 2:
![image](https://github.com/ddnexus/pagy/assets/2972314/c2e5e614-fc60-46c8-99a3-5c70cf412538)

**Comment by ddnexus** [comment]
Thank you!
