### ISSUE TITLE
Last page 'prev' nav inactive when using Out Of Range Extra

### ISSUE THREAD

**Issue by cseelus** [ddnexus/pagy#70]
Just a minor thing: When using `Pagy::VARS[:out_of_range_mode] = :last_page` the `prev` link is disabled on pages which are out of range and the last page is shown instead. Tested with the `pagy_nav` and `pagy_nav_compact` helper.

**Comment by ddnexus** [comment]
Not so minor: it looks like a bug :)
Thanks

**Comment by ddnexus** [comment]
It should work as expected now (in `dev`)

**Comment by cseelus** [comment]
Quick as always, thanks!
