### ISSUE TITLE
Cursor based pagination

### ISSUE THREAD

**Issue by plurtech** [ddnexus/pagy#77]
The problem I'm facing with pagination is described by Twitter's Documentation here:
https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines

So essentially if new records are created between fetching page 1 and page 2, page 2 will contain duplicate records.

Does pagy have a solution? Or can there be a cursor based pagination solution like that of Twitter's

**Comment by ddnexus** [comment]
Hi @plurtech,
it looks like the problem and solution you are describing is a very specific case of chunk-retrieving, where new records are continuously added at the beginning of the collection, and are always ordered by a specific field (i.e. numeric incremented `id` in this case). 

That solution doesn't even have a concept of page number, but only prev/next chunk and it is probably better served by a continuous pagination tool than a standard navigation bar.

Pagy is an agnostic pagination system that offers metrics and UI helpers for standard numbered-page navigation. It looks like it is not the right tool for that specific chunk-retrieving case.
