### ISSUE TITLE
nav-bootstrap-compact in bootstrap 3.

### ISSUE THREAD

**Issue by Tolchi** [ddnexus/pagy#86]
<img width="319" alt="screen shot 2018-09-21 at 12 57 08" src="https://user-images.githubusercontent.com/310909/45874574-eab44d00-bd9d-11e8-9be8-0baf2dfb9989.png">
page count in compact-input is not shown due to its color.

It's because the input field inherits its color from the btn-primary class (which is #fff) 

**However bootstrap 4 doesn't have this issue**

_Originally posted by @serghost in https://github.com/ddnexus/pagy/pull/83#issuecomment-423482108_

**Comment by ddnexus** [comment]
I added a `text-primary` class to the input element: it should have the advantage of not being an hard-coded element style but a class which should change the text color according to the theme.
