### ISSUE TITLE
OutOfRangeError when out_of_range_mode is set to :empty_page

### ISSUE THREAD

**Issue by trevorrjohn** [ddnexus/pagy#98]
I have my `:out_of_range_mode` set to `:empty_page`, however I am seeing it always raise an error when I use the backend `#pagy` method. 

I dug into the code and see that the `:out_of_range_mode` is not checked here: https://github.com/ddnexus/pagy/blob/master/lib/pagy.rb#L26. 

Shouldn't there be some conditional here to check if that error should be raised or am I misunderstanding how this should work.

**Comment by ddnexus** [comment]
Did you require the extra?

**Comment by trevorrjohn** [comment]
🤦‍♂️
